
extern zend_class_entry *qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions);

PHP_METHOD(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions, swap);
PHP_METHOD(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions, qRegisterNormalizedMetaType_QSslPreSharedKeyAuthenticator);
PHP_METHOD(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions, qRegisterNormalizedMetaType_QSslPreSharedKeyAuthenticator_ptr);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_qregisternormalizedmetatype_qsslpresharedkeyauthenticator, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_qregisternormalizedmetatype_qsslpresharedkeyauthenticator_ptr, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_method_entry) {
	PHP_ME(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions, swap, arginfo_qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions, qRegisterNormalizedMetaType_QSslPreSharedKeyAuthenticator, arginfo_qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_qregisternormalizedmetatype_qsslpresharedkeyauthenticator, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslpresharedkeyauthenticatorFunctions_QSslpresharedkeyauthenticatorFunctions, qRegisterNormalizedMetaType_QSslPreSharedKeyAuthenticator_ptr, arginfo_qt_network_qsslpresharedkeyauthenticatorfunctions_qsslpresharedkeyauthenticatorfunctions_qregisternormalizedmetatype_qsslpresharedkeyauthenticator_ptr, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
