
extern zend_class_entry *qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection);

PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, cursor);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, setCursor);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, format);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, setFormat);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_cursor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_setcursor, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_format, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_setformat, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_method_entry) {
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, cursor, arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_cursor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, setCursor, arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_setcursor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, format, arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_format, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutSelection_QAbstractTextDocumentLayoutSelection, setFormat, arginfo_qt_gui_qabstracttextdocumentlayoutselection_qabstracttextdocumentlayoutselection_setformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
