// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Widgets\QStyle;

class QStyle
{
    public static function staticMetaObject() -> int
    {
        return qstyle_static_meta_object();
    }

    public static function tr(var s, var c = null, int n = -1) -> string
    {
        var result;

        let result = qstyle_tr(s, c, n);

        return result;
    }

    public static function new_() -> int
    {
        return qstyle_new();
    }

    public static function name(int handle) -> string
    {
        var result;

        let result = qstyle_name(handle);

        return result;
    }

    public static function polish(int handle, int widget) -> void
    {
        qstyle_polish(handle, widget);
    }

    public static function unpolish(int handle, int widget) -> void
    {
        qstyle_unpolish(handle, widget);
    }

    public static function polishQApplication(int handle, int application) -> void
    {
        qstyle_polish_q_application(handle, application);
    }

    public static function unpolishQApplication(int handle, int application) -> void
    {
        qstyle_unpolish_q_application(handle, application);
    }

    public static function polishQPalette(int handle, int palette) -> void
    {
        qstyle_polish_q_palette(handle, palette);
    }

    public static function itemTextRect(int handle, int fm, int rX, int rY, int rWidth, int rHeight, int flags, bool enabled, string text) -> array
    {
        var result;

        let result = qstyle_item_text_rect(handle, fm, rX, rY, rWidth, rHeight, flags, enabled, text);

        return result;
    }

    public static function itemPixmapRect(int handle, int rX, int rY, int rWidth, int rHeight, int flags, int pixmap) -> array
    {
        var result;

        let result = qstyle_item_pixmap_rect(handle, rX, rY, rWidth, rHeight, flags, pixmap);

        return result;
    }

    public static function drawItemText(int handle, int painter, int rectX, int rectY, int rectWidth, int rectHeight, int flags, int pal, bool enabled, string text, var textRole = null) -> void
    {
        qstyle_draw_item_text(handle, painter, rectX, rectY, rectWidth, rectHeight, flags, pal, enabled, text, textRole);
    }

    public static function drawItemPixmap(int handle, int painter, int rectX, int rectY, int rectWidth, int rectHeight, int alignment, int pixmap) -> void
    {
        qstyle_draw_item_pixmap(handle, painter, rectX, rectY, rectWidth, rectHeight, alignment, pixmap);
    }

    public static function standardPalette(int handle) -> int
    {
        return qstyle_standard_palette(handle);
    }

    public static function drawPrimitive(int handle, int pe, int opt, int p, int w = 0) -> void
    {
        qstyle_draw_primitive(handle, pe, opt, p, w);
    }

    public static function drawControl(int handle, int element, int opt, int p, int w = 0) -> void
    {
        qstyle_draw_control(handle, element, opt, p, w);
    }

    public static function subElementRect(int handle, int subElement, int option, int widget = 0) -> array
    {
        var result;

        let result = qstyle_sub_element_rect(handle, subElement, option, widget);

        return result;
    }

    public static function drawComplexControl(int handle, int cc, int opt, int p, int widget = 0) -> void
    {
        qstyle_draw_complex_control(handle, cc, opt, p, widget);
    }

    public static function hitTestComplexControl(int handle, int cc, int opt, int ptX, int ptY, int widget = 0) -> int
    {
        return qstyle_hit_test_complex_control(handle, cc, opt, ptX, ptY, widget);
    }

    public static function subControlRect(int handle, int cc, int opt, int sc, int widget = 0) -> array
    {
        var result;

        let result = qstyle_sub_control_rect(handle, cc, opt, sc, widget);

        return result;
    }

    public static function pixelMetric(int handle, int metric, int option = 0, int widget = 0) -> int
    {
        return qstyle_pixel_metric(handle, metric, option, widget);
    }

    public static function sizeFromContents(int handle, int ct, int opt, int contentsSizeWidth, int contentsSizeHeight, int w = 0) -> array
    {
        var result;

        let result = qstyle_size_from_contents(handle, ct, opt, contentsSizeWidth, contentsSizeHeight, w);

        return result;
    }

    public static function styleHint(int handle, int stylehint, int opt = 0, int widget = 0, int returnData = 0) -> int
    {
        return qstyle_style_hint(handle, stylehint, opt, widget, returnData);
    }

    public static function standardPixmap(int handle, int standardPixmap, int opt = 0, int widget = 0) -> int
    {
        return qstyle_standard_pixmap(handle, standardPixmap, opt, widget);
    }

    public static function standardIcon(int handle, int standardIcon, int option = 0, int widget = 0) -> int
    {
        return qstyle_standard_icon(handle, standardIcon, option, widget);
    }

    public static function generatedIconPixmap(int handle, int iconMode, int pixmap, int opt) -> int
    {
        return qstyle_generated_icon_pixmap(handle, iconMode, pixmap, opt);
    }

    public static function visualRect(int direction, int boundingRectX, int boundingRectY, int boundingRectWidth, int boundingRectHeight, int logicalRectX, int logicalRectY, int logicalRectWidth, int logicalRectHeight) -> array
    {
        var result;

        let result = qstyle_visual_rect(direction, boundingRectX, boundingRectY, boundingRectWidth, boundingRectHeight, logicalRectX, logicalRectY, logicalRectWidth, logicalRectHeight);

        return result;
    }

    public static function visualPos(int direction, int boundingRectX, int boundingRectY, int boundingRectWidth, int boundingRectHeight, int logicalPosX, int logicalPosY) -> array
    {
        var result;

        let result = qstyle_visual_pos(direction, boundingRectX, boundingRectY, boundingRectWidth, boundingRectHeight, logicalPosX, logicalPosY);

        return result;
    }

    public static function sliderPositionFromValue(int min, int max, int val, int space, bool upsideDown = false) -> int
    {
        return qstyle_slider_position_from_value(min, max, val, space, upsideDown);
    }

    public static function sliderValueFromPosition(int min, int max, int pos, int space, bool upsideDown = false) -> int
    {
        return qstyle_slider_value_from_position(min, max, pos, space, upsideDown);
    }

    public static function visualAlignment(int direction, int alignment) -> int
    {
        return qstyle_visual_alignment(direction, alignment);
    }

    public static function alignedRect(int direction, int alignment, int sizeWidth, int sizeHeight, int rectangleX, int rectangleY, int rectangleWidth, int rectangleHeight) -> array
    {
        var result;

        let result = qstyle_aligned_rect(direction, alignment, sizeWidth, sizeHeight, rectangleX, rectangleY, rectangleWidth, rectangleHeight);

        return result;
    }

    public static function layoutSpacing(int handle, int control1, int control2, int orientation, int option = 0, int widget = 0) -> int
    {
        return qstyle_layout_spacing(handle, control1, control2, orientation, option, widget);
    }

    public static function combinedLayoutSpacing(int handle, int controls1, int controls2, int orientation, int option = 0, int widget = 0) -> int
    {
        return qstyle_combined_layout_spacing(handle, controls1, controls2, orientation, option, widget);
    }

    public static function proxy(int handle) -> int
    {
        return qstyle_proxy(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template QStyle(QStylePrivate & dd)

}
