
extern zend_class_entry *qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent);

PHP_METHOD(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, new_);
PHP_METHOD(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, clone_);
PHP_METHOD(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, newQByteArray);
PHP_METHOD(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, propertyName);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_clone_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_newqbytearray, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_propertyname, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_method_entry) {
	PHP_ME(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, new_, arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, clone_, arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_clone_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, newQByteArray, arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_newqbytearray, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QDynamicPropertyChangeEvent_QDynamicPropertyChangeEvent, propertyName, arginfo_qt_core_qdynamicpropertychangeevent_qdynamicpropertychangeevent_propertyname, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
