// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Widgets\QScrollerpropertiesFunctions;

class QScrollerpropertiesFunctions
{
    public static function qRegisterNormalizedMetaType_QScrollerProperties__OvershootPolicy(string arg0) -> int
    {
        return qscrollerpropertiesfunctions_q_register_normalized_meta_type__q_scroller_properties___overshoot_policy(arg0);
    }

    public static function qRegisterNormalizedMetaType_QScrollerProperties__FrameRates(string arg0) -> int
    {
        return qscrollerpropertiesfunctions_q_register_normalized_meta_type__q_scroller_properties___frame_rates(arg0);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName)
    // @reserved template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName)

}
