
extern zend_class_entry *qt_sql_qsqldrivercreatorbase_qsqldrivercreatorbase_ce;

ZEPHIR_INIT_CLASS(Qt_Sql_QSqlDriverCreatorBase_QSqlDriverCreatorBase);

PHP_METHOD(Qt_Sql_QSqlDriverCreatorBase_QSqlDriverCreatorBase, createObject);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_sql_qsqldrivercreatorbase_qsqldrivercreatorbase_createobject, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_sql_qsqldrivercreatorbase_qsqldrivercreatorbase_method_entry) {
	PHP_ME(Qt_Sql_QSqlDriverCreatorBase_QSqlDriverCreatorBase, createObject, arginfo_qt_sql_qsqldrivercreatorbase_qsqldrivercreatorbase_createobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
