
extern zend_class_entry *qt_widgets_qsliderfunctions_qsliderfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QSliderFunctions_QSliderFunctions);

PHP_METHOD(Qt_Widgets_QSliderFunctions_QSliderFunctions, qt_qsliderStyleOption);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qsliderfunctions_qsliderfunctions_qt_qsliderstyleoption, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, slider, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qsliderfunctions_qsliderfunctions_method_entry) {
	PHP_ME(Qt_Widgets_QSliderFunctions_QSliderFunctions, qt_qsliderStyleOption, arginfo_qt_widgets_qsliderfunctions_qsliderfunctions_qt_qsliderstyleoption, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
