
extern zend_class_entry *qt_core_qstringencoder_qstringencoder_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QStringEncoder_QStringEncoder);

PHP_METHOD(Qt_Core_QStringEncoder_QStringEncoder, new_);
PHP_METHOD(Qt_Core_QStringEncoder_QStringEncoder, newQStringConverterEncodingQStringConverterBaseFlags);
PHP_METHOD(Qt_Core_QStringEncoder_QStringEncoder, newQAnyStringViewQStringConverterBaseFlags);
PHP_METHOD(Qt_Core_QStringEncoder_QStringEncoder, requiredSpace);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qstringencoder_qstringencoder_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qstringencoder_qstringencoder_newqstringconverterencodingqstringconverterbaseflags, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, encoding, IS_LONG, 0)
	ZEND_ARG_INFO(0, flags)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qstringencoder_qstringencoder_newqanystringviewqstringconverterbaseflags, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
	ZEND_ARG_INFO(0, flags)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qstringencoder_qstringencoder_requiredspace, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, inputLength, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qstringencoder_qstringencoder_method_entry) {
	PHP_ME(Qt_Core_QStringEncoder_QStringEncoder, new_, arginfo_qt_core_qstringencoder_qstringencoder_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QStringEncoder_QStringEncoder, newQStringConverterEncodingQStringConverterBaseFlags, arginfo_qt_core_qstringencoder_qstringencoder_newqstringconverterencodingqstringconverterbaseflags, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QStringEncoder_QStringEncoder, newQAnyStringViewQStringConverterBaseFlags, arginfo_qt_core_qstringencoder_qstringencoder_newqanystringviewqstringconverterbaseflags, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QStringEncoder_QStringEncoder, requiredSpace, arginfo_qt_core_qstringencoder_qstringencoder_requiredspace, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
