
extern zend_class_entry *qt_sql_qsqlrelationaltablemodelfunctions_qsqlrelationaltablemodelfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Sql_QSqlrelationaltablemodelFunctions_QSqlrelationaltablemodelFunctions);

PHP_METHOD(Qt_Sql_QSqlrelationaltablemodelFunctions_QSqlrelationaltablemodelFunctions, swap);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_sql_qsqlrelationaltablemodelfunctions_qsqlrelationaltablemodelfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_sql_qsqlrelationaltablemodelfunctions_qsqlrelationaltablemodelfunctions_method_entry) {
	PHP_ME(Qt_Sql_QSqlrelationaltablemodelFunctions_QSqlrelationaltablemodelFunctions, swap, arginfo_qt_sql_qsqlrelationaltablemodelfunctions_qsqlrelationaltablemodelfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
