
extern zend_class_entry *qt_gui_qaccessibleattributesinterface_qaccessibleattributesinterface_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleAttributesInterface_QAccessibleAttributesInterface);

PHP_METHOD(Qt_Gui_QAccessibleAttributesInterface_QAccessibleAttributesInterface, attributeKeys);
PHP_METHOD(Qt_Gui_QAccessibleAttributesInterface_QAccessibleAttributesInterface, attributeValue);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleattributesinterface_qaccessibleattributesinterface_attributekeys, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_gui_qaccessibleattributesinterface_qaccessibleattributesinterface_attributevalue, 0, 0, 2)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, key, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibleattributesinterface_qaccessibleattributesinterface_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleAttributesInterface_QAccessibleAttributesInterface, attributeKeys, arginfo_qt_gui_qaccessibleattributesinterface_qaccessibleattributesinterface_attributekeys, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleAttributesInterface_QAccessibleAttributesInterface, attributeValue, arginfo_qt_gui_qaccessibleattributesinterface_qaccessibleattributesinterface_attributevalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
