
extern zend_class_entry *qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_ce;

ZEPHIR_INIT_CLASS(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier);

PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, new_);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, acquire);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, release);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, wait);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, currentCount);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, releaseUnlessLast);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_acquire, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_release, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_wait, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_currentcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_releaseunlesslast, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_method_entry) {
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, new_, arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, acquire, arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_acquire, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, release, arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_release, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, wait, arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_wait, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, currentCount, arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_currentcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBarrier_QtConcurrentThreadEngineBarrier, releaseUnlessLast, arginfo_qt_concurrent_qtconcurrentthreadenginebarrier_qtconcurrentthreadenginebarrier_releaseunlesslast, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
