
extern zend_class_entry *qt_opengl_qopengldebugfunctions_qopengldebugfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpengldebugFunctions_QOpengldebugFunctions);

PHP_METHOD(Qt_OpenGL_QOpengldebugFunctions_QOpengldebugFunctions, swap);
PHP_METHOD(Qt_OpenGL_QOpengldebugFunctions_QOpengldebugFunctions, qRegisterNormalizedMetaType_QOpenGLDebugMessage);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopengldebugfunctions_qopengldebugfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopengldebugfunctions_qopengldebugfunctions_qregisternormalizedmetatype_qopengldebugmessage, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopengldebugfunctions_qopengldebugfunctions_method_entry) {
	PHP_ME(Qt_OpenGL_QOpengldebugFunctions_QOpengldebugFunctions, swap, arginfo_qt_opengl_qopengldebugfunctions_qopengldebugfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpengldebugFunctions_QOpengldebugFunctions, qRegisterNormalizedMetaType_QOpenGLDebugMessage, arginfo_qt_opengl_qopengldebugfunctions_qopengldebugfunctions_qregisternormalizedmetatype_qopengldebugmessage, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
