
extern zend_class_entry *qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions);

PHP_METHOD(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions, swap);
PHP_METHOD(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions, qRegisterNormalizedMetaType_QNetworkRequest);
PHP_METHOD(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions, qRegisterNormalizedMetaType_QNetworkRequest__RedirectPolicy);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_qregisternormalizedmetatype_qnetworkrequest, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_qregisternormalizedmetatype_qnetworkrequest__redirectpolicy, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_method_entry) {
	PHP_ME(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions, swap, arginfo_qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions, qRegisterNormalizedMetaType_QNetworkRequest, arginfo_qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_qregisternormalizedmetatype_qnetworkrequest, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QNetworkrequestFunctions_QNetworkrequestFunctions, qRegisterNormalizedMetaType_QNetworkRequest__RedirectPolicy, arginfo_qt_network_qnetworkrequestfunctions_qnetworkrequestfunctions_qregisternormalizedmetatype_qnetworkrequest__redirectpolicy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
