
extern zend_class_entry *qt_gui_qnativeinterfaceqwaylandapplication_qnativeinterfaceqwaylandapplication_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QNativeInterfaceQWaylandApplication_QNativeInterfaceQWaylandApplication);

PHP_METHOD(Qt_Gui_QNativeInterfaceQWaylandApplication_QNativeInterfaceQWaylandApplication, new_);
PHP_METHOD(Qt_Gui_QNativeInterfaceQWaylandApplication_QNativeInterfaceQWaylandApplication, lastInputSerial);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qnativeinterfaceqwaylandapplication_qnativeinterfaceqwaylandapplication_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qnativeinterfaceqwaylandapplication_qnativeinterfaceqwaylandapplication_lastinputserial, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qnativeinterfaceqwaylandapplication_qnativeinterfaceqwaylandapplication_method_entry) {
	PHP_ME(Qt_Gui_QNativeInterfaceQWaylandApplication_QNativeInterfaceQWaylandApplication, new_, arginfo_qt_gui_qnativeinterfaceqwaylandapplication_qnativeinterfaceqwaylandapplication_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QNativeInterfaceQWaylandApplication_QNativeInterfaceQWaylandApplication, lastInputSerial, arginfo_qt_gui_qnativeinterfaceqwaylandapplication_qnativeinterfaceqwaylandapplication_lastinputserial, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
