
extern zend_class_entry *qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_ce;

ZEPHIR_INIT_CLASS(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher);

PHP_METHOD(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, staticMetaObject);
PHP_METHOD(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, tr);
PHP_METHOD(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, new_);
PHP_METHOD(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, waitForFinished);
PHP_METHOD(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, finished);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_tr, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, s)
	ZEND_ARG_INFO(0, c)
	ZEND_ARG_TYPE_INFO(0, n, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, call, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, parent_, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_waitforfinished, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_finished, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, self_, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_method_entry) {
	PHP_ME(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, staticMetaObject, arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, tr, arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_tr, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, new_, arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, waitForFinished, arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_waitforfinished, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDBusPendingCallWatcher_QDBusPendingCallWatcher, finished, arginfo_qt_dbus_qdbuspendingcallwatcher_qdbuspendingcallwatcher_finished, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
