
extern zend_class_entry *qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions);

PHP_METHOD(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, swap);
PHP_METHOD(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, qRegisterNormalizedMetaType_QDeadlineTimer);
PHP_METHOD(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, compareThreeWay);
PHP_METHOD(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, comparesEqual);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_qregisternormalizedmetatype_qdeadlinetimer, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_comparethreeway, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_method_entry) {
	PHP_ME(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, swap, arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, qRegisterNormalizedMetaType_QDeadlineTimer, arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_qregisternormalizedmetatype_qdeadlinetimer, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, compareThreeWay, arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_comparethreeway, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QDeadlinetimerFunctions_QDeadlinetimerFunctions, comparesEqual, arginfo_qt_core_qdeadlinetimerfunctions_qdeadlinetimerfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
