
extern zend_class_entry *qt_dbus_qdbusargumentfunctions_qdbusargumentfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_DBus_QDbusargumentFunctions_QDbusargumentFunctions);

PHP_METHOD(Qt_DBus_QDbusargumentFunctions_QDbusargumentFunctions, swap);
PHP_METHOD(Qt_DBus_QDbusargumentFunctions_QDbusargumentFunctions, qRegisterNormalizedMetaType_QDBusArgument);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusargumentfunctions_qdbusargumentfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusargumentfunctions_qdbusargumentfunctions_qregisternormalizedmetatype_qdbusargument, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_dbus_qdbusargumentfunctions_qdbusargumentfunctions_method_entry) {
	PHP_ME(Qt_DBus_QDbusargumentFunctions_QDbusargumentFunctions, swap, arginfo_qt_dbus_qdbusargumentfunctions_qdbusargumentfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusargumentFunctions_QDbusargumentFunctions, qRegisterNormalizedMetaType_QDBusArgument, arginfo_qt_dbus_qdbusargumentfunctions_qdbusargumentfunctions_qregisternormalizedmetatype_qdbusargument, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
