
extern zend_class_entry *qt_core_qpluginfunctions_qpluginfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QPluginFunctions_QPluginFunctions);

PHP_METHOD(Qt_Core_QPluginFunctions_QPluginFunctions, qPluginArchRequirements);
PHP_METHOD(Qt_Core_QPluginFunctions_QPluginFunctions, qRegisterStaticPluginFunction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpluginfunctions_qpluginfunctions_qpluginarchrequirements, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpluginfunctions_qpluginfunctions_qregisterstaticpluginfunction, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, staticPlugin, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qpluginfunctions_qpluginfunctions_method_entry) {
	PHP_ME(Qt_Core_QPluginFunctions_QPluginFunctions, qPluginArchRequirements, arginfo_qt_core_qpluginfunctions_qpluginfunctions_qpluginarchrequirements, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPluginFunctions_QPluginFunctions, qRegisterStaticPluginFunction, arginfo_qt_core_qpluginfunctions_qpluginfunctions_qregisterstaticpluginfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
