
extern zend_class_entry *qt_core_qxmlstreamfunctions_qxmlstreamfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions);

PHP_METHOD(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqual);
PHP_METHOD(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqualQXmlStreamNamespaceDeclarationQXmlStreamNamespaceDeclaration);
PHP_METHOD(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqualQXmlStreamNotationDeclarationQXmlStreamNotationDeclaration);
PHP_METHOD(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqualQXmlStreamEntityDeclarationQXmlStreamEntityDeclaration);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequalqxmlstreamnamespacedeclarationqxmlstreamnamespacedeclaration, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequalqxmlstreamnotationdeclarationqxmlstreamnotationdeclaration, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequalqxmlstreamentitydeclarationqxmlstreamentitydeclaration, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qxmlstreamfunctions_qxmlstreamfunctions_method_entry) {
	PHP_ME(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqual, arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqualQXmlStreamNamespaceDeclarationQXmlStreamNamespaceDeclaration, arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequalqxmlstreamnamespacedeclarationqxmlstreamnamespacedeclaration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqualQXmlStreamNotationDeclarationQXmlStreamNotationDeclaration, arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequalqxmlstreamnotationdeclarationqxmlstreamnotationdeclaration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlstreamFunctions_QXmlstreamFunctions, comparesEqualQXmlStreamEntityDeclarationQXmlStreamEntityDeclaration, arginfo_qt_core_qxmlstreamfunctions_qxmlstreamfunctions_comparesequalqxmlstreamentitydeclarationqxmlstreamentitydeclaration, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
