
extern zend_class_entry *qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent);

PHP_METHOD(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, new_);
PHP_METHOD(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, clone_);
PHP_METHOD(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, newQString);
PHP_METHOD(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, href);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_clone_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_newqstring, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, href, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_href, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_method_entry) {
	PHP_ME(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, new_, arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, clone_, arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_clone_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, newQString, arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_newqstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QWhatsThisClickedEvent_QWhatsThisClickedEvent, href, arginfo_qt_gui_qwhatsthisclickedevent_qwhatsthisclickedevent_href, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
