
extern zend_class_entry *qt_core_qelapsedtimerfunctions_qelapsedtimerfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QElapsedtimerFunctions_QElapsedtimerFunctions);

PHP_METHOD(Qt_Core_QElapsedtimerFunctions_QElapsedtimerFunctions, compareThreeWay);
PHP_METHOD(Qt_Core_QElapsedtimerFunctions_QElapsedtimerFunctions, comparesEqual);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qelapsedtimerfunctions_qelapsedtimerfunctions_comparethreeway, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qelapsedtimerfunctions_qelapsedtimerfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qelapsedtimerfunctions_qelapsedtimerfunctions_method_entry) {
	PHP_ME(Qt_Core_QElapsedtimerFunctions_QElapsedtimerFunctions, compareThreeWay, arginfo_qt_core_qelapsedtimerfunctions_qelapsedtimerfunctions_comparethreeway, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QElapsedtimerFunctions_QElapsedtimerFunctions, comparesEqual, arginfo_qt_core_qelapsedtimerfunctions_qelapsedtimerfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
