
extern zend_class_entry *qt_core_qvariantfunctions_qvariantfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QVariantFunctions_QVariantFunctions);

PHP_METHOD(Qt_Core_QVariantFunctions_QVariantFunctions, swap);
PHP_METHOD(Qt_Core_QVariantFunctions_QVariantFunctions, comparesEqual);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qvariantfunctions_qvariantfunctions_swap, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qvariantfunctions_qvariantfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, a)
	ZEND_ARG_INFO(0, b)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qvariantfunctions_qvariantfunctions_method_entry) {
	PHP_ME(Qt_Core_QVariantFunctions_QVariantFunctions, swap, arginfo_qt_core_qvariantfunctions_qvariantfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QVariantFunctions_QVariantFunctions, comparesEqual, arginfo_qt_core_qvariantfunctions_qvariantfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
