
extern zend_class_entry *qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions);

PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix2x2);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix2x3);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix2x4);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix3x2);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix3x3);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix3x4);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix4x2);
PHP_METHOD(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix4x3);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix2x2, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix2x3, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix2x4, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix3x2, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix3x3, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix3x4, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix4x2, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix4x3, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_method_entry) {
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix2x2, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix2x2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix2x3, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix2x3, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix2x4, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix2x4, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix3x2, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix3x2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix3x3, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix3x3, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix3x4, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix3x4, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix4x2, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix4x2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QGenericmatrixFunctions_QGenericmatrixFunctions, qRegisterNormalizedMetaType_QMatrix4x3, arginfo_qt_gui_qgenericmatrixfunctions_qgenericmatrixfunctions_qregisternormalizedmetatype_qmatrix4x3, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
