
extern zend_class_entry *qt_network_qssldiffiehellmanparametersfunctions_qssldiffiehellmanparametersfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QSsldiffiehellmanparametersFunctions_QSsldiffiehellmanparametersFunctions);

PHP_METHOD(Qt_Network_QSsldiffiehellmanparametersFunctions_QSsldiffiehellmanparametersFunctions, qHash);
PHP_METHOD(Qt_Network_QSsldiffiehellmanparametersFunctions_QSsldiffiehellmanparametersFunctions, swap);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparametersfunctions_qssldiffiehellmanparametersfunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, dhparam, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparametersfunctions_qssldiffiehellmanparametersfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qssldiffiehellmanparametersfunctions_qssldiffiehellmanparametersfunctions_method_entry) {
	PHP_ME(Qt_Network_QSsldiffiehellmanparametersFunctions_QSsldiffiehellmanparametersFunctions, qHash, arginfo_qt_network_qssldiffiehellmanparametersfunctions_qssldiffiehellmanparametersfunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSsldiffiehellmanparametersFunctions_QSsldiffiehellmanparametersFunctions, swap, arginfo_qt_network_qssldiffiehellmanparametersfunctions_qssldiffiehellmanparametersfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
