
extern zend_class_entry *qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result);

PHP_METHOD(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, decoded);
PHP_METHOD(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, setDecoded);
PHP_METHOD(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, decodingStatus);
PHP_METHOD(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, setDecodingStatus);
PHP_METHOD(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, swap);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_decoded, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_setdecoded, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_decodingstatus, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_setdecodingstatus, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_method_entry) {
	PHP_ME(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, decoded, arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_decoded, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, setDecoded, arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_setdecoded, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, decodingStatus, arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_decodingstatus, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, setDecodingStatus, arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_setdecodingstatus, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QByteArrayFromBase64Result_QByteArrayFromBase64Result, swap, arginfo_qt_core_qbytearrayfrombase64result_qbytearrayfrombase64result_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
