
extern zend_class_entry *qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_ce;

ZEPHIR_INIT_CLASS(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult);

PHP_METHOD(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, errorMessage);
PHP_METHOD(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, setErrorMessage);
PHP_METHOD(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, errorLine);
PHP_METHOD(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, setErrorLine);
PHP_METHOD(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, errorColumn);
PHP_METHOD(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, setErrorColumn);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_errormessage, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_seterrormessage, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_errorline, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_seterrorline, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_errorcolumn, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_seterrorcolumn, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_method_entry) {
	PHP_ME(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, errorMessage, arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_errormessage, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, setErrorMessage, arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_seterrormessage, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, errorLine, arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_errorline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, setErrorLine, arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_seterrorline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, errorColumn, arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_errorcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentParseResult_QDomDocumentParseResult, setErrorColumn, arginfo_qt_xml_qdomdocumentparseresult_qdomdocumentparseresult_seterrorcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
