
extern zend_class_entry *qt_network_qnetworkreplyfunctions_qnetworkreplyfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QNetworkreplyFunctions_QNetworkreplyFunctions);

PHP_METHOD(Qt_Network_QNetworkreplyFunctions_QNetworkreplyFunctions, qRegisterNormalizedMetaType_QNetworkReply__NetworkError);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkreplyfunctions_qnetworkreplyfunctions_qregisternormalizedmetatype_qnetworkreply__networkerror, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qnetworkreplyfunctions_qnetworkreplyfunctions_method_entry) {
	PHP_ME(Qt_Network_QNetworkreplyFunctions_QNetworkreplyFunctions, qRegisterNormalizedMetaType_QNetworkReply__NetworkError, arginfo_qt_network_qnetworkreplyfunctions_qnetworkreplyfunctions_qregisternormalizedmetatype_qnetworkreply__networkerror, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
