
extern zend_class_entry *qt_opengl_qopenglversionfunctionsstorage_qopenglversionfunctionsstorage_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenGLVersionFunctionsStorage_QOpenGLVersionFunctionsStorage);

PHP_METHOD(Qt_OpenGL_QOpenGLVersionFunctionsStorage_QOpenGLVersionFunctionsStorage, new_);
PHP_METHOD(Qt_OpenGL_QOpenGLVersionFunctionsStorage_QOpenGLVersionFunctionsStorage, backend);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionfunctionsstorage_qopenglversionfunctionsstorage_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionfunctionsstorage_qopenglversionfunctionsstorage_backend, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, context, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglversionfunctionsstorage_qopenglversionfunctionsstorage_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenGLVersionFunctionsStorage_QOpenGLVersionFunctionsStorage, new_, arginfo_qt_opengl_qopenglversionfunctionsstorage_qopenglversionfunctionsstorage_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVersionFunctionsStorage_QOpenGLVersionFunctionsStorage, backend, arginfo_qt_opengl_qopenglversionfunctionsstorage_qopenglversionfunctionsstorage_backend, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
