
extern zend_class_entry *qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions);

PHP_METHOD(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, swap);
PHP_METHOD(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, swapQNetworkInterfaceQNetworkInterface);
PHP_METHOD(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, qRegisterNormalizedMetaType_QNetworkAddressEntry);
PHP_METHOD(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, qRegisterNormalizedMetaType_QNetworkInterface);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_swapqnetworkinterfaceqnetworkinterface, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_qregisternormalizedmetatype_qnetworkaddressentry, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_qregisternormalizedmetatype_qnetworkinterface, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_method_entry) {
	PHP_ME(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, swap, arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, swapQNetworkInterfaceQNetworkInterface, arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_swapqnetworkinterfaceqnetworkinterface, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, qRegisterNormalizedMetaType_QNetworkAddressEntry, arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_qregisternormalizedmetatype_qnetworkaddressentry, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QNetworkinterfaceFunctions_QNetworkinterfaceFunctions, qRegisterNormalizedMetaType_QNetworkInterface, arginfo_qt_network_qnetworkinterfacefunctions_qnetworkinterfacefunctions_qregisternormalizedmetatype_qnetworkinterface, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
