
extern zend_class_entry *qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant);

PHP_METHOD(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant, new_);
PHP_METHOD(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant, variant);
PHP_METHOD(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant, setVariant);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_variant, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_setvariant, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_method_entry) {
	PHP_ME(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant, new_, arginfo_qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant, variant, arginfo_qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_variant, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleHintReturnVariant_QStyleHintReturnVariant, setVariant, arginfo_qt_widgets_qstylehintreturnvariant_qstylehintreturnvariant_setvariant, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
