
extern zend_class_entry *qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation);

PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, fileName);
PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, functionName);
PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, line);
PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, setLine);
PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, column);
PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, setColumn);
PHP_METHOD(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, new_);

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_filename, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_functionname, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_line, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_setline, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_column, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_setcolumn, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_method_entry) {
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, fileName, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_filename, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, functionName, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_functionname, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, line, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_line, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, setLine, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_setline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, column, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_column, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, setColumn, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_setcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPropertyBindingSourceLocation_QPropertyBindingSourceLocation, new_, arginfo_qt_core_qpropertybindingsourcelocation_qpropertybindingsourcelocation_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
