
extern zend_class_entry *qt_core_qlocationpermission_qlocationpermission_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QLocationPermission_QLocationPermission);

PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, staticMetaObject);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, qt_check_for_QGADGET_macro);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, setAccuracy);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, accuracy);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, setAvailability);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, availability);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, new_);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, newQLocationPermission);
PHP_METHOD(Qt_Core_QLocationPermission_QLocationPermission, swap);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_qt_check_for_qgadget_macro, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_setaccuracy, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, accuracy, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_accuracy, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_setavailability, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, availability, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_availability, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_newqlocationpermission, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlocationpermission_qlocationpermission_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qlocationpermission_qlocationpermission_method_entry) {
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, staticMetaObject, arginfo_qt_core_qlocationpermission_qlocationpermission_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, qt_check_for_QGADGET_macro, arginfo_qt_core_qlocationpermission_qlocationpermission_qt_check_for_qgadget_macro, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, setAccuracy, arginfo_qt_core_qlocationpermission_qlocationpermission_setaccuracy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, accuracy, arginfo_qt_core_qlocationpermission_qlocationpermission_accuracy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, setAvailability, arginfo_qt_core_qlocationpermission_qlocationpermission_setavailability, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, availability, arginfo_qt_core_qlocationpermission_qlocationpermission_availability, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, new_, arginfo_qt_core_qlocationpermission_qlocationpermission_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, newQLocationPermission, arginfo_qt_core_qlocationpermission_qlocationpermission_newqlocationpermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLocationPermission_QLocationPermission, swap, arginfo_qt_core_qlocationpermission_qlocationpermission_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
