// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Widgets\QStyleHintReturnVariant;

class QStyleHintReturnVariant
{
    public static function new_() -> int
    {
        return qstylehintreturnvariant_new();
    }

    public static function variant(int handle) -> var
    {
        var result;

        let result = qstylehintreturnvariant_variant(handle);

        return result;
    }

    public static function setVariant(int handle, var value) -> void
    {
        qstylehintreturnvariant_set_variant(handle, value);
    }
}
