// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QVersionnumberFunctions;

class QVersionnumberFunctions
{
    public static function qHash(int key, int seed = 0) -> int
    {
        return qversionnumberfunctions_q_hash(key, seed);
    }

    public static function qRegisterNormalizedMetaType_QVersionNumber(string arg0) -> int
    {
        return qversionnumberfunctions_q_register_normalized_meta_type__q_version_number(arg0);
    }

    public static function compareThreeWay(int lhs, int rhs) -> int
    {
        return qversionnumberfunctions_compare_three_way(lhs, rhs);
    }

    public static function comparesEqual(int lhs, int rhs) -> bool
    {
        int r;

        let r = qversionnumberfunctions_compares_equal(lhs, rhs);

        return r == 1;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName)
    // @reserved stream QDataStream & operator<<(QDataStream & out, const QVersionNumber & version)
    // @reserved stream QDataStream & operator>>(QDataStream & in, QVersionNumber & version)
    // @reserved stream QDebug operator<<(QDebug, const QVersionNumber & version)
    // @reserved operator bool operator>=(const QVersionNumber & lhs, const QVersionNumber & rhs)
    // @reserved operator bool operator<=(const QVersionNumber & lhs, const QVersionNumber & rhs)
    // @reserved operator bool operator>(const QVersionNumber & lhs, const QVersionNumber & rhs)
    // @reserved operator bool operator<(const QVersionNumber & lhs, const QVersionNumber & rhs)
    // @reserved operator bool operator!=(const QVersionNumber & lhs, const QVersionNumber & rhs)
    // @reserved operator bool operator==(const QVersionNumber & lhs, const QVersionNumber & rhs)
    // @reserved operator QVersionNumber::It::difference_type operator-(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved operator QVersionNumber::It operator-(QVersionNumber::It it, QVersionNumber::It::difference_type n)
    // @reserved operator QVersionNumber::It operator+(QVersionNumber::It::difference_type n, QVersionNumber::It it)
    // @reserved operator QVersionNumber::It operator+(QVersionNumber::It it, QVersionNumber::It::difference_type n)
    // @reserved operator bool operator>=(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved operator bool operator>(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved operator bool operator<=(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved operator bool operator<(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved operator bool operator!=(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved operator bool operator==(QVersionNumber::It lhs, QVersionNumber::It rhs)
    // @reserved template Qt::strong_ordering compareThreeWay(const QVersionNumber::It & lhs, const QVersionNumber::It & rhs)
    // @reserved template bool comparesEqual(const QVersionNumber::It & lhs, const QVersionNumber::It & rhs)

}
