
extern zend_class_entry *qt_network_qsslellipticcurvefunctions_qsslellipticcurvefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QSslellipticcurveFunctions_QSslellipticcurveFunctions);

PHP_METHOD(Qt_Network_QSslellipticcurveFunctions_QSslellipticcurveFunctions, qHash);
PHP_METHOD(Qt_Network_QSslellipticcurveFunctions_QSslellipticcurveFunctions, qRegisterNormalizedMetaType_QSslEllipticCurve);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslellipticcurvefunctions_qsslellipticcurvefunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, curve, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslellipticcurvefunctions_qsslellipticcurvefunctions_qregisternormalizedmetatype_qsslellipticcurve, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qsslellipticcurvefunctions_qsslellipticcurvefunctions_method_entry) {
	PHP_ME(Qt_Network_QSslellipticcurveFunctions_QSslellipticcurveFunctions, qHash, arginfo_qt_network_qsslellipticcurvefunctions_qsslellipticcurvefunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslellipticcurveFunctions_QSslellipticcurveFunctions, qRegisterNormalizedMetaType_QSslEllipticCurve, arginfo_qt_network_qsslellipticcurvefunctions_qsslellipticcurvefunctions_qregisternormalizedmetatype_qsslellipticcurve, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
