
extern zend_class_entry *qt_core_qcalendarpermission_qcalendarpermission_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QCalendarPermission_QCalendarPermission);

PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, staticMetaObject);
PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, qt_check_for_QGADGET_macro);
PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, setAccessMode);
PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, accessMode);
PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, new_);
PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, newQCalendarPermission);
PHP_METHOD(Qt_Core_QCalendarPermission_QCalendarPermission, swap);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_qt_check_for_qgadget_macro, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_setaccessmode, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, mode, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_accessmode, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_newqcalendarpermission, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcalendarpermission_qcalendarpermission_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qcalendarpermission_qcalendarpermission_method_entry) {
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, staticMetaObject, arginfo_qt_core_qcalendarpermission_qcalendarpermission_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, qt_check_for_QGADGET_macro, arginfo_qt_core_qcalendarpermission_qcalendarpermission_qt_check_for_qgadget_macro, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, setAccessMode, arginfo_qt_core_qcalendarpermission_qcalendarpermission_setaccessmode, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, accessMode, arginfo_qt_core_qcalendarpermission_qcalendarpermission_accessmode, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, new_, arginfo_qt_core_qcalendarpermission_qcalendarpermission_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, newQCalendarPermission, arginfo_qt_core_qcalendarpermission_qcalendarpermission_newqcalendarpermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCalendarPermission_QCalendarPermission, swap, arginfo_qt_core_qcalendarpermission_qcalendarpermission_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
