
extern zend_class_entry *qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions);

PHP_METHOD(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, initializeOpenGLFunctions);
PHP_METHOD(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, new_);
PHP_METHOD(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, isInitialized);
PHP_METHOD(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, setOwningContext);
PHP_METHOD(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, owningContext);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_initializeopenglfunctions, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_isinitialized, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_setowningcontext, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, context, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_owningcontext, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_method_entry) {
	PHP_ME(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, initializeOpenGLFunctions, arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_initializeopenglfunctions, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, new_, arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, isInitialized, arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_isinitialized, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, setOwningContext, arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_setowningcontext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QAbstractOpenGLFunctions_QAbstractOpenGLFunctions, owningContext, arginfo_qt_opengl_qabstractopenglfunctions_qabstractopenglfunctions_owningcontext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
