// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Widgets\QStyleOptionSlider;

class QStyleOptionSlider
{
    public static function orientation(int handle) -> int
    {
        return qstyleoptionslider_orientation(handle);
    }

    public static function setOrientation(int handle, int value) -> void
    {
        qstyleoptionslider_set_orientation(handle, value);
    }

    public static function minimum(int handle) -> int
    {
        return qstyleoptionslider_minimum(handle);
    }

    public static function setMinimum(int handle, int value) -> void
    {
        qstyleoptionslider_set_minimum(handle, value);
    }

    public static function maximum(int handle) -> int
    {
        return qstyleoptionslider_maximum(handle);
    }

    public static function setMaximum(int handle, int value) -> void
    {
        qstyleoptionslider_set_maximum(handle, value);
    }

    public static function tickPosition(int handle) -> int
    {
        return qstyleoptionslider_tick_position(handle);
    }

    public static function setTickPosition(int handle, int value) -> void
    {
        qstyleoptionslider_set_tick_position(handle, value);
    }

    public static function tickInterval(int handle) -> int
    {
        return qstyleoptionslider_tick_interval(handle);
    }

    public static function setTickInterval(int handle, int value) -> void
    {
        qstyleoptionslider_set_tick_interval(handle, value);
    }

    public static function upsideDown(int handle) -> bool
    {
        int r;

        let r = qstyleoptionslider_upside_down(handle);

        return r == 1;
    }

    public static function setUpsideDown(int handle, bool value) -> void
    {
        qstyleoptionslider_set_upside_down(handle, value);
    }

    public static function sliderPosition(int handle) -> int
    {
        return qstyleoptionslider_slider_position(handle);
    }

    public static function setSliderPosition(int handle, int value) -> void
    {
        qstyleoptionslider_set_slider_position(handle, value);
    }

    public static function sliderValue(int handle) -> int
    {
        return qstyleoptionslider_slider_value(handle);
    }

    public static function setSliderValue(int handle, int value) -> void
    {
        qstyleoptionslider_set_slider_value(handle, value);
    }

    public static function singleStep(int handle) -> int
    {
        return qstyleoptionslider_single_step(handle);
    }

    public static function setSingleStep(int handle, int value) -> void
    {
        qstyleoptionslider_set_single_step(handle, value);
    }

    public static function pageStep(int handle) -> int
    {
        return qstyleoptionslider_page_step(handle);
    }

    public static function setPageStep(int handle, int value) -> void
    {
        qstyleoptionslider_set_page_step(handle, value);
    }

    public static function notchTarget(int handle) -> double
    {
        return qstyleoptionslider_notch_target(handle);
    }

    public static function setNotchTarget(int handle, double value) -> void
    {
        qstyleoptionslider_set_notch_target(handle, value);
    }

    public static function dialWrapping(int handle) -> bool
    {
        int r;

        let r = qstyleoptionslider_dial_wrapping(handle);

        return r == 1;
    }

    public static function setDialWrapping(int handle, bool value) -> void
    {
        qstyleoptionslider_set_dial_wrapping(handle, value);
    }

    public static function keyboardModifiers(int handle) -> int
    {
        return qstyleoptionslider_keyboard_modifiers(handle);
    }

    public static function setKeyboardModifiers(int handle, int value) -> void
    {
        qstyleoptionslider_set_keyboard_modifiers(handle, value);
    }

    public static function new_() -> int
    {
        return qstyleoptionslider_new();
    }

    public static function newQStyleOptionSlider(int other) -> int
    {
        return qstyleoptionslider_new_q_style_option_slider(other);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved operator QStyleOptionSlider & operator=(const QStyleOptionSlider &)
    // @reserved unreachable QStyleOptionSlider(int version)

}
