
extern zend_class_entry *qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported);

PHP_METHOD(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, new_);
PHP_METHOD(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, MacOSSonoma);
PHP_METHOD(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, MacOSSequoia);
PHP_METHOD(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, Android14);
PHP_METHOD(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, Windows11_23H2);
PHP_METHOD(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, Windows11_24H2);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_macossonoma, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_macossequoia, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_android14, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_windows11_23h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_windows11_24h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_method_entry) {
	PHP_ME(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, new_, arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, MacOSSonoma, arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_macossonoma, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, MacOSSequoia, arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_macossequoia, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, Android14, arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_android14, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, Windows11_23H2, arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_windows11_23h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersionUnexported_QOperatingSystemVersionUnexported, Windows11_24H2, arginfo_qt_core_qoperatingsystemversionunexported_qoperatingsystemversionunexported_windows11_24h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
