
extern zend_class_entry *qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator);

PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, new_);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, isValid);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, hasNext);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, next);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, peekNext);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, regularExpression);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, matchType);
PHP_METHOD(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, matchOptions);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_isvalid, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_hasnext, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_next, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_peeknext, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_regularexpression, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_matchtype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_matchoptions, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_method_entry) {
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, new_, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, isValid, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_isvalid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, hasNext, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_hasnext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, next, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_next, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, peekNext, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_peeknext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, regularExpression, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_regularexpression, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, matchType, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_matchtype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularExpressionMatchIterator_QRegularExpressionMatchIterator, matchOptions, arginfo_qt_core_qregularexpressionmatchiterator_qregularexpressionmatchiterator_matchoptions, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
