
extern zend_class_entry *qt_opengl_qopenglfunctions_3_0_corebackend_qopenglfunctions_3_0_corebackend_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenGLFunctions_3_0_CoreBackend_QOpenGLFunctions_3_0_CoreBackend);

PHP_METHOD(Qt_OpenGL_QOpenGLFunctions_3_0_CoreBackend_QOpenGLFunctions_3_0_CoreBackend, new_);
PHP_METHOD(Qt_OpenGL_QOpenGLFunctions_3_0_CoreBackend_QOpenGLFunctions_3_0_CoreBackend, versionStatus);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglfunctions_3_0_corebackend_qopenglfunctions_3_0_corebackend_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, c, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglfunctions_3_0_corebackend_qopenglfunctions_3_0_corebackend_versionstatus, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglfunctions_3_0_corebackend_qopenglfunctions_3_0_corebackend_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenGLFunctions_3_0_CoreBackend_QOpenGLFunctions_3_0_CoreBackend, new_, arginfo_qt_opengl_qopenglfunctions_3_0_corebackend_qopenglfunctions_3_0_corebackend_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFunctions_3_0_CoreBackend_QOpenGLFunctions_3_0_CoreBackend, versionStatus, arginfo_qt_opengl_qopenglfunctions_3_0_corebackend_qopenglfunctions_3_0_corebackend_versionstatus, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
