
extern zend_class_entry *qt_core_qcborarrayconstiterator_qcborarrayconstiterator_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QCborArrayConstIterator_QCborArrayConstIterator);

PHP_METHOD(Qt_Core_QCborArrayConstIterator_QCborArrayConstIterator, new_);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborarrayconstiterator_qcborarrayconstiterator_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qcborarrayconstiterator_qcborarrayconstiterator_method_entry) {
	PHP_ME(Qt_Core_QCborArrayConstIterator_QCborArrayConstIterator, new_, arginfo_qt_core_qcborarrayconstiterator_qcborarrayconstiterator_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
