
extern zend_class_entry *qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions);

PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWay);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqual);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQByteArrayView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQByteArrayView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQStringViewQLatin1StringView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQStringViewQLatin1StringView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQStringView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQStringView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQChar);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQChar);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQLatin1StringView);
PHP_METHOD(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQLatin1StringView);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreeway, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqbytearrayview, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqbytearrayview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqstringviewqlatin1stringview, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqstringviewqlatin1stringview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqstringview, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqstringview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqchar, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqchar, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqlatin1stringview, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, s1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, s2, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqlatin1stringview, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, s1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, s2, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_method_entry) {
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWay, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreeway, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqual, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQByteArrayView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqbytearrayview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQByteArrayView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqbytearrayview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQStringViewQLatin1StringView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqstringviewqlatin1stringview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQStringViewQLatin1StringView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqstringviewqlatin1stringview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQStringView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqstringview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQStringView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqstringview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQChar, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqchar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQChar, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqchar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, compareThreeWayQLatin1StringViewQLatin1StringView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparethreewayqlatin1stringviewqlatin1stringview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QLatin1stringviewFunctions_QLatin1stringviewFunctions, comparesEqualQLatin1StringViewQLatin1StringView, arginfo_qt_core_qlatin1stringviewfunctions_qlatin1stringviewfunctions_comparesequalqlatin1stringviewqlatin1stringview, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
