
extern zend_class_entry *qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord);

PHP_METHOD(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, new_);
PHP_METHOD(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, newQDnsDomainNameRecord);
PHP_METHOD(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, swap);
PHP_METHOD(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, name);
PHP_METHOD(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, timeToLive);
PHP_METHOD(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, value);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_newqdnsdomainnamerecord, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_name, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_timetolive, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_value, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_method_entry) {
	PHP_ME(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, new_, arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, newQDnsDomainNameRecord, arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_newqdnsdomainnamerecord, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, swap, arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, name, arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_name, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, timeToLive, arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_timetolive, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsDomainNameRecord_QDnsDomainNameRecord, value, arginfo_qt_network_qdnsdomainnamerecord_qdnsdomainnamerecord_value, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
