
extern zend_class_entry *qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent);

PHP_METHOD(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, new_);
PHP_METHOD(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, clone_);
PHP_METHOD(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, newQPlatformSurfaceEventSurfaceEventType);
PHP_METHOD(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, surfaceEventType);
PHP_METHOD(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, m_surfaceEventType);
PHP_METHOD(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, setM_surfaceEventType);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_clone_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_newqplatformsurfaceeventsurfaceeventtype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, surfaceEventType, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_surfaceeventtype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_m_surfaceeventtype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_setm_surfaceeventtype, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_method_entry) {
	PHP_ME(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, new_, arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, clone_, arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_clone_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, newQPlatformSurfaceEventSurfaceEventType, arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_newqplatformsurfaceeventsurfaceeventtype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, surfaceEventType, arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_surfaceeventtype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, m_surfaceEventType, arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_m_surfaceeventtype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPlatformSurfaceEvent_QPlatformSurfaceEvent, setM_surfaceEventType, arginfo_qt_gui_qplatformsurfaceevent_qplatformsurfaceevent_setm_surfaceeventtype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
