/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qexception.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQException : public QException {
public:
    PhpQtQException() : QException() {}
    PhpQtQException(const QException & p0) : QException(p0) {}
    ~PhpQtQException();
    void raise() const noexcept(noexcept(std::declval<const PhpQtQException &>().QException::raise())) override;
    QException * clone() const noexcept(noexcept(std::declval<const PhpQtQException &>().QException::clone())) override;
    const char * what() const noexcept(noexcept(std::declval<const PhpQtQException &>().std::exception::what())) override;
    static const char *const kOverridable[];
};
