/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_CORE_QCONCATENATETABLESPROXYMODEL_H
#define PHPQT_CORE_QCONCATENATETABLESPROXYMODEL_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Core\QConcatenateTablesProxyModel staticMetaObject() -> int */
zend_long phpqt_qconcatenatetablesproxymodel_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Core\QConcatenateTablesProxyModel tr(var s, var c = null, int n = -1) -> string */
void phpqt_qconcatenatetablesproxymodel_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QConcatenateTablesProxyModel(QObject * parent) */
/*@zep Core\QConcatenateTablesProxyModel new(int parent = 0) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_new(zval *p_parent);

/*@ast QList<QAbstractItemModel *> sourceModels() const */
/*@zep Core\QConcatenateTablesProxyModel sourceModels(int handle) -> array */
void phpqt_qconcatenatetablesproxymodel_source_models(zval *return_value, zval *p_handle);

/*@ast void addSourceModel(QAbstractItemModel * sourceModel) */
/*@zep Core\QConcatenateTablesProxyModel addSourceModel(int handle, int sourceModel) -> void */
void phpqt_qconcatenatetablesproxymodel_add_source_model(zval *p_handle, zval *p_sourceModel);

/*@ast void removeSourceModel(QAbstractItemModel * sourceModel) */
/*@zep Core\QConcatenateTablesProxyModel removeSourceModel(int handle, int sourceModel) -> void */
void phpqt_qconcatenatetablesproxymodel_remove_source_model(zval *p_handle, zval *p_sourceModel);

/*@ast QModelIndex mapFromSource(const QModelIndex & sourceIndex) const */
/*@zep Core\QConcatenateTablesProxyModel mapFromSource(int handle, int sourceIndex) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_map_from_source(zval *p_handle, zval *p_sourceIndex);

/*@ast QModelIndex mapToSource(const QModelIndex & proxyIndex) const */
/*@zep Core\QConcatenateTablesProxyModel mapToSource(int handle, int proxyIndex) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_map_to_source(zval *p_handle, zval *p_proxyIndex);

/*@ast QVariant data(const QModelIndex & index, int role) const */
/*@zep Core\QConcatenateTablesProxyModel data(int handle, int index, var role = null) -> var */
void phpqt_qconcatenatetablesproxymodel_data(zval *return_value, zval *p_handle, zval *p_index, zval *p_role);

/*@ast bool setData(const QModelIndex & index, const QVariant & value, int role) */
/*@zep Core\QConcatenateTablesProxyModel setData(int handle, int index, var value, var role = null) -> bool */
zend_long phpqt_qconcatenatetablesproxymodel_set_data(zval *p_handle, zval *p_index, zval *p_value, zval *p_role);

/*@ast QMap<int, QVariant> itemData(const QModelIndex & proxyIndex) const */
/*@zep Core\QConcatenateTablesProxyModel itemData(int handle, int proxyIndex) -> array */
void phpqt_qconcatenatetablesproxymodel_item_data(zval *return_value, zval *p_handle, zval *p_proxyIndex);

/*@ast bool setItemData(const QModelIndex & index, const QMap<int, QVariant> & roles) */
/*@zep Core\QConcatenateTablesProxyModel setItemData(int handle, int index, array roles) -> bool */
zend_long phpqt_qconcatenatetablesproxymodel_set_item_data(zval *p_handle, zval *p_index, zval *p_roles);

/*@ast Qt::ItemFlags flags(const QModelIndex & index) const */
/*@zep Core\QConcatenateTablesProxyModel flags(int handle, int index) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_flags(zval *p_handle, zval *p_index);

/*@ast QModelIndex index(int row, int column, const QModelIndex & parent) const */
/*@zep Core\QConcatenateTablesProxyModel index(int handle, int row, int column, var parent = null) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_index(zval *p_handle, zval *p_row, zval *p_column, zval *p_parent);

/*@ast QModelIndex parent(const QModelIndex & index) const */
/*@zep Core\QConcatenateTablesProxyModel parent(int handle, int index) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_parent(zval *p_handle, zval *p_index);

/*@ast int rowCount(const QModelIndex & parent) const */
/*@zep Core\QConcatenateTablesProxyModel rowCount(int handle, var parent = null) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_row_count(zval *p_handle, zval *p_parent);

/*@ast QVariant headerData(int section, Qt::Orientation orientation, int role) const */
/*@zep Core\QConcatenateTablesProxyModel headerData(int handle, int section, int orientation, var role = null) -> var */
void phpqt_qconcatenatetablesproxymodel_header_data(zval *return_value, zval *p_handle, zval *p_section, zval *p_orientation, zval *p_role);

/*@ast int columnCount(const QModelIndex & parent) const */
/*@zep Core\QConcatenateTablesProxyModel columnCount(int handle, var parent = null) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_column_count(zval *p_handle, zval *p_parent);

/*@ast QStringList mimeTypes() const */
/*@zep Core\QConcatenateTablesProxyModel mimeTypes(int handle) -> array */
void phpqt_qconcatenatetablesproxymodel_mime_types(zval *return_value, zval *p_handle);

/*@ast QMimeData * mimeData(const QModelIndexList & indexes) const */
/*@zep Core\QConcatenateTablesProxyModel mimeData(int handle, array indexes) -> int */
zend_long phpqt_qconcatenatetablesproxymodel_mime_data(zval *p_handle, zval *p_indexes);

/*@ast bool canDropMimeData(const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) const */
/*@zep Core\QConcatenateTablesProxyModel canDropMimeData(int handle, int data, int action, int row, int column, int parent) -> bool */
zend_long phpqt_qconcatenatetablesproxymodel_can_drop_mime_data(zval *p_handle, zval *p_data, zval *p_action, zval *p_row, zval *p_column, zval *p_parent);

/*@ast bool dropMimeData(const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) */
/*@zep Core\QConcatenateTablesProxyModel dropMimeData(int handle, int data, int action, int row, int column, int parent) -> bool */
zend_long phpqt_qconcatenatetablesproxymodel_drop_mime_data(zval *p_handle, zval *p_data, zval *p_action, zval *p_row, zval *p_column, zval *p_parent);

/*@ast QSize span(const QModelIndex & index) const */
/*@zep Core\QConcatenateTablesProxyModel span(int handle, int index) -> array */
void phpqt_qconcatenatetablesproxymodel_span(zval *return_value, zval *p_handle, zval *p_index);

/*@override Core\QConcatenateTablesProxyModel data QVariant data(const QModelIndex & index, int role) const */
/*@override Core\QConcatenateTablesProxyModel setData bool setData(const QModelIndex & index, const QVariant & value, int role) */
/*@override Core\QConcatenateTablesProxyModel itemData QMap<int, QVariant> itemData(const QModelIndex & proxyIndex) const */
/*@override Core\QConcatenateTablesProxyModel setItemData bool setItemData(const QModelIndex & index, const QMap<int, QVariant> & roles) */
/*@override Core\QConcatenateTablesProxyModel flags Qt::ItemFlags flags(const QModelIndex & index) const */
/*@override Core\QConcatenateTablesProxyModel index QModelIndex index(int row, int column, const QModelIndex & parent) const */
/*@override Core\QConcatenateTablesProxyModel parent QModelIndex parent(const QModelIndex & index) const */
/*@override Core\QConcatenateTablesProxyModel rowCount int rowCount(const QModelIndex & parent) const */
/*@override Core\QConcatenateTablesProxyModel headerData QVariant headerData(int section, Qt::Orientation orientation, int role) const */
/*@override Core\QConcatenateTablesProxyModel columnCount int columnCount(const QModelIndex & parent) const */
/*@override Core\QConcatenateTablesProxyModel mimeTypes QStringList mimeTypes() const */
/*@override Core\QConcatenateTablesProxyModel mimeData QMimeData * mimeData(const QModelIndexList & indexes) const */
/*@override Core\QConcatenateTablesProxyModel canDropMimeData bool canDropMimeData(const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) const */
/*@override Core\QConcatenateTablesProxyModel dropMimeData bool dropMimeData(const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) */
/*@override Core\QConcatenateTablesProxyModel span QSize span(const QModelIndex & index) const */
/*@override Core\QConcatenateTablesProxyModel sibling QModelIndex sibling(int row, int column, const QModelIndex & idx) const */
/*@override Core\QConcatenateTablesProxyModel hasChildren bool hasChildren(const QModelIndex & parent) const */
/*@override Core\QConcatenateTablesProxyModel setHeaderData bool setHeaderData(int section, Qt::Orientation orientation, const QVariant & value, int role) */
/*@override Core\QConcatenateTablesProxyModel clearItemData bool clearItemData(const QModelIndex & index) */
/*@override Core\QConcatenateTablesProxyModel supportedDropActions Qt::DropActions supportedDropActions() const */
/*@override Core\QConcatenateTablesProxyModel supportedDragActions Qt::DropActions supportedDragActions() const */
/*@override Core\QConcatenateTablesProxyModel insertRows bool insertRows(int row, int count, const QModelIndex & parent) */
/*@override Core\QConcatenateTablesProxyModel insertColumns bool insertColumns(int column, int count, const QModelIndex & parent) */
/*@override Core\QConcatenateTablesProxyModel removeRows bool removeRows(int row, int count, const QModelIndex & parent) */
/*@override Core\QConcatenateTablesProxyModel removeColumns bool removeColumns(int column, int count, const QModelIndex & parent) */
/*@override Core\QConcatenateTablesProxyModel moveRows bool moveRows(const QModelIndex & sourceParent, int sourceRow, int count, const QModelIndex & destinationParent, int destinationChild) */
/*@override Core\QConcatenateTablesProxyModel moveColumns bool moveColumns(const QModelIndex & sourceParent, int sourceColumn, int count, const QModelIndex & destinationParent, int destinationChild) */
/*@override Core\QConcatenateTablesProxyModel fetchMore void fetchMore(const QModelIndex & parent) */
/*@override Core\QConcatenateTablesProxyModel canFetchMore bool canFetchMore(const QModelIndex & parent) const */
/*@override Core\QConcatenateTablesProxyModel sort void sort(int column, Qt::SortOrder order) */
/*@override Core\QConcatenateTablesProxyModel buddy QModelIndex buddy(const QModelIndex & index) const */
/*@override Core\QConcatenateTablesProxyModel match QModelIndexList match(const QModelIndex & start, int role, const QVariant & value, int hits, Qt::MatchFlags flags) const */
/*@override Core\QConcatenateTablesProxyModel roleNames QHash<int, QByteArray> roleNames() const */
/*@override Core\QConcatenateTablesProxyModel multiData void multiData(const QModelIndex & index, QModelRoleDataSpan roleDataSpan) const */
/*@override Core\QConcatenateTablesProxyModel submit bool submit() */
/*@override Core\QConcatenateTablesProxyModel revert void revert() */
/*@override Core\QConcatenateTablesProxyModel resetInternalData void resetInternalData() */
/*@override Core\QConcatenateTablesProxyModel event bool event(QEvent * event) */
/*@override Core\QConcatenateTablesProxyModel eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Core\QConcatenateTablesProxyModel timerEvent void timerEvent(QTimerEvent * event) */
/*@override Core\QConcatenateTablesProxyModel childEvent void childEvent(QChildEvent * event) */
/*@override Core\QConcatenateTablesProxyModel customEvent void customEvent(QEvent * event) */
/*@override Core\QConcatenateTablesProxyModel connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Core\QConcatenateTablesProxyModel disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
