/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_CORE_QJSONOBJECTFUNCTIONS_H
#define PHPQT_CORE_QJSONOBJECTFUNCTIONS_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast void swap(QJsonObject & value1, QJsonObject & value2) */
/*@zep Core\QJsonobjectFunctions swap(int value1, int value2) -> void */
void phpqt_qjsonobjectfunctions_swap(zval *p_value1, zval *p_value2);

/*@ast size_t qHash(const QJsonObject & object, size_t seed) */
/*@zep Core\QJsonobjectFunctions qHash(int object, int seed = 0) -> int */
zend_long phpqt_qjsonobjectfunctions_q_hash(zval *p_object, zval *p_seed);

/*@ast bool comparesEqual(const QJsonObject & lhs, const QJsonValueConstRef & rhs) */
/*@zep Core\QJsonobjectFunctions comparesEqual(int lhs, int rhs) -> bool */
zend_long phpqt_qjsonobjectfunctions_compares_equal(zval *p_lhs, zval *p_rhs);

/*@ast bool comparesEqual(const QJsonObject & lhs, const QJsonValue & rhs) */
/*@zep Core\QJsonobjectFunctions comparesEqualQJsonObjectQJsonValue(int lhs, int rhs) -> bool */
zend_long phpqt_qjsonobjectfunctions_compares_equal_q_json_object_q_json_value(zval *p_lhs, zval *p_rhs);

/*@ast bool comparesEqual(const QJsonObject & lhs, const QJsonObject & rhs) */
/*@zep Core\QJsonobjectFunctions comparesEqualQJsonObjectQJsonObject(int lhs, int rhs) -> bool */
zend_long phpqt_qjsonobjectfunctions_compares_equal_q_json_object_q_json_object(zval *p_lhs, zval *p_rhs);

/*@reserved Core\QJsonobjectFunctions stream QDebug operator<<(QDebug, const QJsonObject &) */
/*@reserved Core\QJsonobjectFunctions stream QDataStream & operator<<(QDataStream &, const QJsonObject &) */
/*@reserved Core\QJsonobjectFunctions stream QDataStream & operator>>(QDataStream &, QJsonObject &) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonValueConstRef & lhs, const QJsonObject & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonValueConstRef & lhs, const QJsonObject & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject & lhs, const QJsonValueConstRef & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject & lhs, const QJsonValueConstRef & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonValue & lhs, const QJsonObject & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonValue & lhs, const QJsonObject & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject & lhs, const QJsonValue & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject & lhs, const QJsonValue & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject & lhs, const QJsonObject & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject & lhs, const QJsonObject & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>=(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<=(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions iterator Qt::strong_ordering compareThreeWay(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions iterator bool comparesEqual(const QJsonObject::const_iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>=(const QJsonObject::const_iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<=(const QJsonObject::const_iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>(const QJsonObject::const_iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<(const QJsonObject::const_iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject::const_iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject::const_iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>=(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<=(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions iterator Qt::strong_ordering compareThreeWay(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions iterator bool comparesEqual(const QJsonObject::iterator & lhs, const QJsonObject::const_iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>=(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<=(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator>(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator<(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator!=(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions operator bool operator==(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions iterator Qt::strong_ordering compareThreeWay(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */
/*@reserved Core\QJsonobjectFunctions iterator bool comparesEqual(const QJsonObject::iterator & lhs, const QJsonObject::iterator & rhs) */

#ifdef __cplusplus
}
#endif
#endif
