/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_CORE_QALGORITHMSFUNCTIONS_H
#define PHPQT_CORE_QALGORITHMSFUNCTIONS_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast uint qPopulationCount(quint32 v) */
/*@zep Core\QAlgorithmsFunctions qPopulationCount(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_population_count(zval *p_v);

/*@ast uint qPopulationCount(quint8 v) */
/*@zep Core\QAlgorithmsFunctions qPopulationCountQuint8(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_population_count_quint8(zval *p_v);

/*@ast uint qPopulationCount(quint16 v) */
/*@zep Core\QAlgorithmsFunctions qPopulationCountQuint16(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_population_count_quint16(zval *p_v);

/*@ast uint qPopulationCount(quint64 v) */
/*@zep Core\QAlgorithmsFunctions qPopulationCountQuint64(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_population_count_quint64(zval *p_v);

/*@ast uint qPopulationCount(long unsigned int v) */
/*@zep Core\QAlgorithmsFunctions qPopulationCountLongUnsignedInt(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_population_count_long_unsigned_int(zval *p_v);

/*@ast uint qCountTrailingZeroBits(quint32 v) */
/*@zep Core\QAlgorithmsFunctions qCountTrailingZeroBits(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_trailing_zero_bits(zval *p_v);

/*@ast uint qCountTrailingZeroBits(quint8 v) */
/*@zep Core\QAlgorithmsFunctions qCountTrailingZeroBitsQuint8(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_trailing_zero_bits_quint8(zval *p_v);

/*@ast uint qCountTrailingZeroBits(quint16 v) */
/*@zep Core\QAlgorithmsFunctions qCountTrailingZeroBitsQuint16(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_trailing_zero_bits_quint16(zval *p_v);

/*@ast uint qCountTrailingZeroBits(quint64 v) */
/*@zep Core\QAlgorithmsFunctions qCountTrailingZeroBitsQuint64(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_trailing_zero_bits_quint64(zval *p_v);

/*@ast uint qCountTrailingZeroBits(long unsigned int v) */
/*@zep Core\QAlgorithmsFunctions qCountTrailingZeroBitsLongUnsignedInt(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_trailing_zero_bits_long_unsigned_int(zval *p_v);

/*@ast uint qCountLeadingZeroBits(quint32 v) */
/*@zep Core\QAlgorithmsFunctions qCountLeadingZeroBits(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_leading_zero_bits(zval *p_v);

/*@ast uint qCountLeadingZeroBits(quint8 v) */
/*@zep Core\QAlgorithmsFunctions qCountLeadingZeroBitsQuint8(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_leading_zero_bits_quint8(zval *p_v);

/*@ast uint qCountLeadingZeroBits(quint16 v) */
/*@zep Core\QAlgorithmsFunctions qCountLeadingZeroBitsQuint16(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_leading_zero_bits_quint16(zval *p_v);

/*@ast uint qCountLeadingZeroBits(quint64 v) */
/*@zep Core\QAlgorithmsFunctions qCountLeadingZeroBitsQuint64(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_leading_zero_bits_quint64(zval *p_v);

/*@ast uint qCountLeadingZeroBits(long unsigned int v) */
/*@zep Core\QAlgorithmsFunctions qCountLeadingZeroBitsLongUnsignedInt(int v) -> int */
zend_long phpqt_qalgorithmsfunctions_q_count_leading_zero_bits_long_unsigned_int(zval *p_v);


#ifdef __cplusplus
}
#endif
#endif
