/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_CORE_QATOMICINT_H
#define PHPQT_CORE_QATOMICINT_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast QAtomicInt(int value) */
/*@zep Core\QAtomicInt new(int value = 0) -> int */
zend_long phpqt_qatomicint_new(zval *p_value);


#ifdef __cplusplus
}
#endif
#endif
