/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_DBUS_QDBUSEXTRATYPESFUNCTIONS_H
#define PHPQT_DBUS_QDBUSEXTRATYPESFUNCTIONS_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast void swap(QDBusObjectPath & value1, QDBusObjectPath & value2) */
/*@zep DBus\QDbusextratypesFunctions swap(int value1, int value2) -> void */
void phpqt_qdbusextratypesfunctions_swap(zval *p_value1, zval *p_value2);

/*@ast size_t qHash(const QDBusObjectPath & objectPath, size_t seed) */
/*@zep DBus\QDbusextratypesFunctions qHash(int objectPath, int seed = 0) -> int */
zend_long phpqt_qdbusextratypesfunctions_q_hash(zval *p_objectPath, zval *p_seed);

/*@ast void swap(QDBusSignature & value1, QDBusSignature & value2) */
/*@zep DBus\QDbusextratypesFunctions swapQDBusSignatureQDBusSignature(int value1, int value2) -> void */
void phpqt_qdbusextratypesfunctions_swap_q_d_bus_signature_q_d_bus_signature(zval *p_value1, zval *p_value2);

/*@ast size_t qHash(const QDBusSignature & signature, size_t seed) */
/*@zep DBus\QDbusextratypesFunctions qHashQDBusSignatureSizeT(int signature, int seed = 0) -> int */
zend_long phpqt_qdbusextratypesfunctions_q_hash_q_d_bus_signature_size_t(zval *p_signature, zval *p_seed);

/*@ast void swap(QDBusVariant & value1, QDBusVariant & value2) */
/*@zep DBus\QDbusextratypesFunctions swapQDBusVariantQDBusVariant(int value1, int value2) -> void */
void phpqt_qdbusextratypesfunctions_swap_q_d_bus_variant_q_d_bus_variant(zval *p_value1, zval *p_value2);

/*@ast int qRegisterNormalizedMetaType_QDBusVariant(const QByteArray &) */
/*@zep DBus\QDbusextratypesFunctions qRegisterNormalizedMetaType_QDBusVariant(string arg0) -> int */
zend_long phpqt_qdbusextratypesfunctions_q_register_normalized_meta_type__q_d_bus_variant(zval *p_arg0);

/*@ast int qRegisterNormalizedMetaType_QDBusObjectPath(const QByteArray &) */
/*@zep DBus\QDbusextratypesFunctions qRegisterNormalizedMetaType_QDBusObjectPath(string arg0) -> int */
zend_long phpqt_qdbusextratypesfunctions_q_register_normalized_meta_type__q_d_bus_object_path(zval *p_arg0);

/*@ast int qRegisterNormalizedMetaType_QDBusSignature(const QByteArray &) */
/*@zep DBus\QDbusextratypesFunctions qRegisterNormalizedMetaType_QDBusSignature(string arg0) -> int */
zend_long phpqt_qdbusextratypesfunctions_q_register_normalized_meta_type__q_d_bus_signature(zval *p_arg0);

/*@reserved DBus\QDbusextratypesFunctions template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName) */
/*@reserved DBus\QDbusextratypesFunctions template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName) */
/*@reserved DBus\QDbusextratypesFunctions template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator==(const QDBusObjectPath & lhs, const QDBusObjectPath & rhs) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator!=(const QDBusObjectPath & lhs, const QDBusObjectPath & rhs) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator<(const QDBusObjectPath & lhs, const QDBusObjectPath & rhs) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator==(const QDBusSignature & lhs, const QDBusSignature & rhs) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator!=(const QDBusSignature & lhs, const QDBusSignature & rhs) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator<(const QDBusSignature & lhs, const QDBusSignature & rhs) */
/*@reserved DBus\QDbusextratypesFunctions operator bool operator==(const QDBusVariant & v1, const QDBusVariant & v2) */
/*@reserved DBus\QDbusextratypesFunctions stream QDebug operator<<(QDebug, const QDBusObjectPath &) */

#ifdef __cplusplus
}
#endif
#endif
