/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include "gui-qaccessibleeditabletextinterface-shell.h"

PhpQtQAccessibleEditableTextInterface::~PhpQtQAccessibleEditableTextInterface()
{
    phpqt::forget_canon(phpqt::canon_impl(static_cast<QAccessibleEditableTextInterface *>(this)));
}

void PhpQtQAccessibleEditableTextInterface::deleteText(int p0, int p1) noexcept(noexcept(std::declval<PhpQtQAccessibleEditableTextInterface &>().QAccessibleEditableTextInterface::deleteText(std::declval<int>(), std::declval<int>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QAccessibleEditableTextInterface *>(this)), "deleteText");
    if (fn == nullptr) { phpqt::warn_once("QAccessibleEditableTextInterface::deleteText", "QAccessibleEditableTextInterface::deleteText: pure virtual with no PHP override"); return; }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QAccessibleEditableTextInterface *>(this), PHPQT_TAG_QAccessibleEditableTextInterface, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    ZVAL_LONG(&argv[2], static_cast<zend_long>(p1));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQAccessibleEditableTextInterface::insertText(int p0, const QString & p1) noexcept(noexcept(std::declval<PhpQtQAccessibleEditableTextInterface &>().QAccessibleEditableTextInterface::insertText(std::declval<int>(), std::declval<const QString &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QAccessibleEditableTextInterface *>(this)), "insertText");
    if (fn == nullptr) { phpqt::warn_once("QAccessibleEditableTextInterface::insertText", "QAccessibleEditableTextInterface::insertText: pure virtual with no PHP override"); return; }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QAccessibleEditableTextInterface *>(this), PHPQT_TAG_QAccessibleEditableTextInterface, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    phpqt::ret_qstring(&argv[2], p1);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQAccessibleEditableTextInterface::replaceText(int p0, int p1, const QString & p2) noexcept(noexcept(std::declval<PhpQtQAccessibleEditableTextInterface &>().QAccessibleEditableTextInterface::replaceText(std::declval<int>(), std::declval<int>(), std::declval<const QString &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QAccessibleEditableTextInterface *>(this)), "replaceText");
    if (fn == nullptr) { phpqt::warn_once("QAccessibleEditableTextInterface::replaceText", "QAccessibleEditableTextInterface::replaceText: pure virtual with no PHP override"); return; }
    zval argv[4];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QAccessibleEditableTextInterface *>(this), PHPQT_TAG_QAccessibleEditableTextInterface, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    ZVAL_LONG(&argv[2], static_cast<zend_long>(p1));
    phpqt::ret_qstring(&argv[3], p2);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 4, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

const char *const PhpQtQAccessibleEditableTextInterface::kOverridable[] = { "deleteText", "insertText", "replaceText", nullptr };
