/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qrect.h>
#include <QtGui/qregion.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "gui-qregionfunctions.h"

extern "C" void phpqt_qregionfunctions_swap(zval *p_value1, zval *p_value2)
{
    QRegion *a0_p = phpqt::is_null(p_value1) ? nullptr : phpqt::as<QRegion>(p_value1, PHPQT_TAG_QRegion);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "swap: value1 is not a QRegion handle"); return; }
    QRegion *a1_p = phpqt::is_null(p_value2) ? nullptr : phpqt::as<QRegion>(p_value2, PHPQT_TAG_QRegion);
    if (a1_p == nullptr) { php_error_docref(NULL, E_WARNING, "swap: value2 is not a QRegion handle"); return; }
    swap(*a0_p, *a1_p); /* native */
}

extern "C" zend_long phpqt_qregionfunctions_qt_region_strict_contains(zval *p_region, zval *p_rectX, zval *p_rectY, zval *p_rectWidth, zval *p_rectHeight)
{
    QRegion *a0_p = phpqt::is_null(p_region) ? nullptr : phpqt::as<QRegion>(p_region, PHPQT_TAG_QRegion);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "qt_region_strictContains: region is not a QRegion handle"); return 0; }
    QRect a1 = QRect(static_cast<int>(phpqt::arg_long(p_rectX)), static_cast<int>(phpqt::arg_long(p_rectY)), static_cast<int>(phpqt::arg_long(p_rectWidth)), static_cast<int>(phpqt::arg_long(p_rectHeight)));
    return (qt_region_strictContains(*a0_p, a1)) ? 1 : 0; /* native */
}

