/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_GUI_QINPUTMETHODQUERYEVENT_H
#define PHPQT_GUI_QINPUTMETHODQUERYEVENT_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast QInputMethodQueryEvent(const QInputMethodQueryEvent &) */
/*@zep Gui\QInputMethodQueryEvent new(int arg0) -> int */
zend_long phpqt_qinputmethodqueryevent_new(zval *p_arg0);

/*@ast QInputMethodQueryEvent * clone() const */
/*@zep Gui\QInputMethodQueryEvent clone(int handle) -> int */
zend_long phpqt_qinputmethodqueryevent_clone(zval *p_handle);

/*@ast QInputMethodQueryEvent(Qt::InputMethodQueries queries) */
/*@zep Gui\QInputMethodQueryEvent newQtInputMethodQueries(int queries) -> int */
zend_long phpqt_qinputmethodqueryevent_new_qt_input_method_queries(zval *p_queries);

/*@ast Qt::InputMethodQueries queries() const */
/*@zep Gui\QInputMethodQueryEvent queries(int handle) -> int */
zend_long phpqt_qinputmethodqueryevent_queries(zval *p_handle);

/*@ast void setValue(Qt::InputMethodQuery query, const QVariant & value) */
/*@zep Gui\QInputMethodQueryEvent setValue(int handle, int query, var value) -> void */
void phpqt_qinputmethodqueryevent_set_value(zval *p_handle, zval *p_query, zval *p_value);

/*@ast QVariant value(Qt::InputMethodQuery query) const */
/*@zep Gui\QInputMethodQueryEvent value(int handle, int query) -> var */
void phpqt_qinputmethodqueryevent_value(zval *return_value, zval *p_handle, zval *p_query);

/*@reserved Gui\QInputMethodQueryEvent operator QInputMethodQueryEvent & operator=(const QInputMethodQueryEvent & other) */
/*@override Gui\QInputMethodQueryEvent clone QInputMethodQueryEvent * clone() const */
/*@override Gui\QInputMethodQueryEvent setAccepted void setAccepted(bool accepted) */

#ifdef __cplusplus
}
#endif
#endif
