/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_GUI_QGENERICPLUGIN_H
#define PHPQT_GUI_QGENERICPLUGIN_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Gui\QGenericPlugin staticMetaObject() -> int */
zend_long phpqt_qgenericplugin_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Gui\QGenericPlugin tr(var s, var c = null, int n = -1) -> string */
void phpqt_qgenericplugin_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QGenericPlugin(QObject * parent) */
/*@zep Gui\QGenericPlugin new(int parent = 0) -> int */
zend_long phpqt_qgenericplugin_new(zval *p_parent);

/*@ast QObject * create(const QString & name, const QString & spec) */
/*@zep Gui\QGenericPlugin create(int handle, string name, string spec) -> int */
zend_long phpqt_qgenericplugin_create(zval *p_handle, zval *p_name, zval *p_spec);

/*@override Gui\QGenericPlugin create QObject * create(const QString & name, const QString & spec) */
/*@override Gui\QGenericPlugin event bool event(QEvent * event) */
/*@override Gui\QGenericPlugin eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Gui\QGenericPlugin timerEvent void timerEvent(QTimerEvent * event) */
/*@override Gui\QGenericPlugin childEvent void childEvent(QChildEvent * event) */
/*@override Gui\QGenericPlugin customEvent void customEvent(QEvent * event) */
/*@override Gui\QGenericPlugin connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Gui\QGenericPlugin disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
