/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtGui/qaccessible.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQAccessibleAttributesInterface : public QAccessibleAttributesInterface {
public:
    ~PhpQtQAccessibleAttributesInterface();
    QList<QAccessible::Attribute> attributeKeys() const noexcept(noexcept(std::declval<const PhpQtQAccessibleAttributesInterface &>().QAccessibleAttributesInterface::attributeKeys())) override;
    QVariant attributeValue(QAccessible::Attribute p0) const noexcept(noexcept(std::declval<const PhpQtQAccessibleAttributesInterface &>().QAccessibleAttributesInterface::attributeValue(std::declval<QAccessible::Attribute>()))) override;
    static const char *const kOverridable[];
};
