/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_NETWORK_QNETWORKDATAGRAMFUNCTIONS_H
#define PHPQT_NETWORK_QNETWORKDATAGRAMFUNCTIONS_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast void swap(QNetworkDatagram & value1, QNetworkDatagram & value2) */
/*@zep Network\QNetworkdatagramFunctions swap(int value1, int value2) -> void */
void phpqt_qnetworkdatagramfunctions_swap(zval *p_value1, zval *p_value2);

/*@ast int qRegisterNormalizedMetaType_QNetworkDatagram(const QByteArray &) */
/*@zep Network\QNetworkdatagramFunctions qRegisterNormalizedMetaType_QNetworkDatagram(string arg0) -> int */
zend_long phpqt_qnetworkdatagramfunctions_q_register_normalized_meta_type__q_network_datagram(zval *p_arg0);

/*@reserved Network\QNetworkdatagramFunctions template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName) */

#ifdef __cplusplus
}
#endif
#endif
