/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtNetwork/qnetworkinformation.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "network-qnetworkinformationfunctions.h"

