/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qcoreevent.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtCore/qsize.h>
#include <QtGui/qevent.h>
#include <QtGui/qicon.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qpainter.h>
#include <QtWidgets/qabstractbutton.h>
#include <QtWidgets/qmenu.h>
#include <QtWidgets/qpushbutton.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qwidget.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "widgets-qpushbutton.h"
#include "widgets-qpushbutton-shell.h"

extern "C" zend_long phpqt_qpushbutton_static_meta_object(void)
{
    return phpqt::reg_copy(QPushButton::staticMetaObject, PHPQT_TAG_QMetaObject); /* native */
}

extern "C" void phpqt_qpushbutton_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n)
{
    const char *a0 = phpqt::arg_cstr(p_s);
    const char *a1 = phpqt::arg_cstr(p_c);
    int a2 = static_cast<int>(phpqt::arg_long(p_n));
    phpqt::ret_qstring(return_value, QPushButton::tr(a0, a1, a2)); /* native */
}

extern "C" zend_long phpqt_qpushbutton_new(zval *p_parent)
{
    QWidget *a0 = phpqt::as<QWidget>(p_parent, PHPQT_TAG_QWidget);
    auto *obj = new PhpQtQPushButton(a0); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QPushButton, true, true);
}

extern "C" zend_long phpqt_qpushbutton_new_q_string_q_widget(zval *p_text, zval *p_parent)
{
    QString a0 = phpqt::arg_qstring(p_text);
    QWidget *a1 = phpqt::as<QWidget>(p_parent, PHPQT_TAG_QWidget);
    auto *obj = new PhpQtQPushButton(a0, a1); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QPushButton, true, true);
}

extern "C" zend_long phpqt_qpushbutton_new_q_icon_q_string_q_widget(zval *p_icon, zval *p_text, zval *p_parent)
{
    QIcon *a0_p = phpqt::is_null(p_icon) ? nullptr : phpqt::as<QIcon>(p_icon, PHPQT_TAG_QIcon);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::QPushButton: icon is not a QIcon handle"); return 0; }
    QString a1 = phpqt::arg_qstring(p_text);
    QWidget *a2 = phpqt::as<QWidget>(p_parent, PHPQT_TAG_QWidget);
    auto *obj = new PhpQtQPushButton(*a0_p, a1, a2); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QPushButton, true, true);
}

extern "C" void phpqt_qpushbutton_size_hint(zval *return_value, zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::sizeHint: handle is not a QPushButton"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->sizeHint()); /* native */
}

extern "C" void phpqt_qpushbutton_minimum_size_hint(zval *return_value, zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::minimumSizeHint: handle is not a QPushButton"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->minimumSizeHint()); /* native */
}

extern "C" zend_long phpqt_qpushbutton_auto_default(zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::autoDefault: handle is not a QPushButton"); return 0; }
    return (self->autoDefault()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qpushbutton_set_auto_default(zval *p_handle, zval *p_arg0)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::setAutoDefault: handle is not a QPushButton"); return; }
    bool a0 = phpqt::arg_bool(p_arg0);
    self->setAutoDefault(a0); /* native */
}

extern "C" zend_long phpqt_qpushbutton_is_default(zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::isDefault: handle is not a QPushButton"); return 0; }
    return (self->isDefault()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qpushbutton_set_default(zval *p_handle, zval *p_arg0)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::setDefault: handle is not a QPushButton"); return; }
    bool a0 = phpqt::arg_bool(p_arg0);
    self->setDefault(a0); /* native */
}

extern "C" void phpqt_qpushbutton_set_menu(zval *p_handle, zval *p_menu)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::setMenu: handle is not a QPushButton"); return; }
    QMenu *a0 = phpqt::as<QMenu>(p_menu, PHPQT_TAG_QMenu);
    self->setMenu(a0); /* native */
}

extern "C" zend_long phpqt_qpushbutton_menu(zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::menu: handle is not a QPushButton"); return 0; }
    return phpqt::reg_out(const_cast<QMenu *>(self->menu()), PHPQT_TAG_QMenu); /* native */
}

extern "C" void phpqt_qpushbutton_set_flat(zval *p_handle, zval *p_arg0)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::setFlat: handle is not a QPushButton"); return; }
    bool a0 = phpqt::arg_bool(p_arg0);
    self->setFlat(a0); /* native */
}

extern "C" zend_long phpqt_qpushbutton_is_flat(zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::isFlat: handle is not a QPushButton"); return 0; }
    return (self->isFlat()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qpushbutton_show_menu(zval *p_handle)
{
    QPushButton *self = phpqt::as<QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::showMenu: handle is not a QPushButton"); return; }
    self->showMenu(); /* native */
}

extern "C" zend_long phpqt_qpushbutton_event(zval *p_handle, zval *p_e)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::event: handle is not a QPushButton constructed through the extension"); return 0; }
    QEvent *a0 = phpqt::as<QEvent>(p_e, PHPQT_TAG_QEvent);
    return (self->phpqt_fwd_event(a0)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qpushbutton_paint_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::paintEvent: handle is not a QPushButton constructed through the extension"); return; }
    QPaintEvent *a0 = phpqt::as<QPaintEvent>(p_arg0, PHPQT_TAG_QPaintEvent);
    self->phpqt_fwd_paintEvent(a0); /* native */
}

extern "C" void phpqt_qpushbutton_key_press_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::keyPressEvent: handle is not a QPushButton constructed through the extension"); return; }
    QKeyEvent *a0 = phpqt::as<QKeyEvent>(p_arg0, PHPQT_TAG_QKeyEvent);
    self->phpqt_fwd_keyPressEvent(a0); /* native */
}

extern "C" void phpqt_qpushbutton_focus_in_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::focusInEvent: handle is not a QPushButton constructed through the extension"); return; }
    QFocusEvent *a0 = phpqt::as<QFocusEvent>(p_arg0, PHPQT_TAG_QFocusEvent);
    self->phpqt_fwd_focusInEvent(a0); /* native */
}

extern "C" void phpqt_qpushbutton_focus_out_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::focusOutEvent: handle is not a QPushButton constructed through the extension"); return; }
    QFocusEvent *a0 = phpqt::as<QFocusEvent>(p_arg0, PHPQT_TAG_QFocusEvent);
    self->phpqt_fwd_focusOutEvent(a0); /* native */
}

extern "C" void phpqt_qpushbutton_mouse_move_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::mouseMoveEvent: handle is not a QPushButton constructed through the extension"); return; }
    QMouseEvent *a0 = phpqt::as<QMouseEvent>(p_arg0, PHPQT_TAG_QMouseEvent);
    self->phpqt_fwd_mouseMoveEvent(a0); /* native */
}

extern "C" void phpqt_qpushbutton_init_style_option(zval *p_handle, zval *p_option)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::initStyleOption: handle is not a QPushButton constructed through the extension"); return; }
    QStyleOptionButton *a0 = phpqt::as<QStyleOptionButton>(p_option, PHPQT_TAG_QStyleOptionButton);
    self->phpqt_fwd_initStyleOption(a0); /* native */
}

extern "C" zend_long phpqt_qpushbutton_hit_button(zval *p_handle, zval *p_posX, zval *p_posY)
{
    PhpQtQPushButton *self = phpqt::as_shell<PhpQtQPushButton, QPushButton>(p_handle, PHPQT_TAG_QPushButton);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QPushButton::hitButton: handle is not a QPushButton constructed through the extension"); return 0; }
    QPoint a0 = QPoint(static_cast<int>(phpqt::arg_long(p_posX)), static_cast<int>(phpqt::arg_long(p_posY)));
    return (self->phpqt_fwd_hitButton(a0)) ? 1 : 0; /* native */
}

