/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QITEMEDITORFACTORY_H
#define PHPQT_WIDGETS_QITEMEDITORFACTORY_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast QItemEditorFactory() */
/*@zep Widgets\QItemEditorFactory new() -> int */
zend_long phpqt_qitemeditorfactory_new(void);

/*@ast QWidget * createEditor(int userType, QWidget * parent) const */
/*@zep Widgets\QItemEditorFactory createEditor(int handle, int userType, int parent) -> int */
zend_long phpqt_qitemeditorfactory_create_editor(zval *p_handle, zval *p_userType, zval *p_parent);

/*@ast QByteArray valuePropertyName(int userType) const */
/*@zep Widgets\QItemEditorFactory valuePropertyName(int handle, int userType) -> string */
void phpqt_qitemeditorfactory_value_property_name(zval *return_value, zval *p_handle, zval *p_userType);

/*@ast void registerEditor(int userType, QItemEditorCreatorBase * creator) */
/*@zep Widgets\QItemEditorFactory registerEditor(int handle, int userType, int creator) -> void */
void phpqt_qitemeditorfactory_register_editor(zval *p_handle, zval *p_userType, zval *p_creator);

/*@ast const QItemEditorFactory * defaultFactory() */
/*@zep Widgets\QItemEditorFactory defaultFactory() -> int */
zend_long phpqt_qitemeditorfactory_default_factory(void);

/*@ast void setDefaultFactory(QItemEditorFactory * factory) */
/*@zep Widgets\QItemEditorFactory setDefaultFactory(int factory) -> void */
void phpqt_qitemeditorfactory_set_default_factory(zval *p_factory);

/*@override Widgets\QItemEditorFactory createEditor QWidget * createEditor(int userType, QWidget * parent) const */
/*@override Widgets\QItemEditorFactory valuePropertyName QByteArray valuePropertyName(int userType) const */

#ifdef __cplusplus
}
#endif
#endif
