/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include "widgets-qmdisubwindow-shell.h"

PhpQtQMdiSubWindow::~PhpQtQMdiSubWindow()
{
    phpqt::forget_canon(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)));
}

QSize PhpQtQMdiSubWindow::sizeHint() const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QMdiSubWindow::sizeHint()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "sizeHint");
    if (fn == nullptr) { return QMdiSubWindow::sizeHint(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QMdiSubWindow::sizeHint(); }
    QSize r = phpqt::arg_geom_QSize(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

QSize PhpQtQMdiSubWindow::minimumSizeHint() const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QMdiSubWindow::minimumSizeHint()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "minimumSizeHint");
    if (fn == nullptr) { return QMdiSubWindow::minimumSizeHint(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QMdiSubWindow::minimumSizeHint(); }
    QSize r = phpqt::arg_geom_QSize(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQMdiSubWindow::eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "eventFilter");
    if (fn == nullptr) { return QMdiSubWindow::eventFilter(p0, p1); }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    ZVAL_LONG(&argv[1], phpqt::reg_out(const_cast<QObject *>(p0), PHPQT_TAG_QObject));
    phpqt::Temp<QEvent> t1(const_cast<QEvent *>(p1), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[2], t1.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QMdiSubWindow::eventFilter(p0, p1); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQMdiSubWindow::event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::event(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "event");
    if (fn == nullptr) { return QMdiSubWindow::event(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QMdiSubWindow::event(p0); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQMdiSubWindow::showEvent(QShowEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::showEvent(std::declval<QShowEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "showEvent");
    if (fn == nullptr) { QMdiSubWindow::showEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QShowEvent> t0(const_cast<QShowEvent *>(p0), PHPQT_TAG_QShowEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::hideEvent(QHideEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::hideEvent(std::declval<QHideEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "hideEvent");
    if (fn == nullptr) { QMdiSubWindow::hideEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QHideEvent> t0(const_cast<QHideEvent *>(p0), PHPQT_TAG_QHideEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::changeEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::changeEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "changeEvent");
    if (fn == nullptr) { QMdiSubWindow::changeEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::closeEvent(QCloseEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::closeEvent(std::declval<QCloseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "closeEvent");
    if (fn == nullptr) { QMdiSubWindow::closeEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QCloseEvent> t0(const_cast<QCloseEvent *>(p0), PHPQT_TAG_QCloseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::leaveEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::leaveEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "leaveEvent");
    if (fn == nullptr) { QMdiSubWindow::leaveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::resizeEvent(QResizeEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::resizeEvent(std::declval<QResizeEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "resizeEvent");
    if (fn == nullptr) { QMdiSubWindow::resizeEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QResizeEvent> t0(const_cast<QResizeEvent *>(p0), PHPQT_TAG_QResizeEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::timerEvent(std::declval<QTimerEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "timerEvent");
    if (fn == nullptr) { QMdiSubWindow::timerEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QTimerEvent> t0(const_cast<QTimerEvent *>(p0), PHPQT_TAG_QTimerEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::moveEvent(QMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::moveEvent(std::declval<QMoveEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "moveEvent");
    if (fn == nullptr) { QMdiSubWindow::moveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMoveEvent> t0(const_cast<QMoveEvent *>(p0), PHPQT_TAG_QMoveEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::paintEvent(QPaintEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::paintEvent(std::declval<QPaintEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "paintEvent");
    if (fn == nullptr) { QMdiSubWindow::paintEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QPaintEvent> t0(const_cast<QPaintEvent *>(p0), PHPQT_TAG_QPaintEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::mousePressEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::mousePressEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "mousePressEvent");
    if (fn == nullptr) { QMdiSubWindow::mousePressEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::mouseDoubleClickEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::mouseDoubleClickEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "mouseDoubleClickEvent");
    if (fn == nullptr) { QMdiSubWindow::mouseDoubleClickEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::mouseReleaseEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::mouseReleaseEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "mouseReleaseEvent");
    if (fn == nullptr) { QMdiSubWindow::mouseReleaseEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::mouseMoveEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::mouseMoveEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "mouseMoveEvent");
    if (fn == nullptr) { QMdiSubWindow::mouseMoveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::keyPressEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::keyPressEvent(std::declval<QKeyEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "keyPressEvent");
    if (fn == nullptr) { QMdiSubWindow::keyPressEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QKeyEvent> t0(const_cast<QKeyEvent *>(p0), PHPQT_TAG_QKeyEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::contextMenuEvent(QContextMenuEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::contextMenuEvent(std::declval<QContextMenuEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "contextMenuEvent");
    if (fn == nullptr) { QMdiSubWindow::contextMenuEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QContextMenuEvent> t0(const_cast<QContextMenuEvent *>(p0), PHPQT_TAG_QContextMenuEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::focusInEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::focusInEvent(std::declval<QFocusEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "focusInEvent");
    if (fn == nullptr) { QMdiSubWindow::focusInEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QFocusEvent> t0(const_cast<QFocusEvent *>(p0), PHPQT_TAG_QFocusEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::focusOutEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::focusOutEvent(std::declval<QFocusEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "focusOutEvent");
    if (fn == nullptr) { QMdiSubWindow::focusOutEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QFocusEvent> t0(const_cast<QFocusEvent *>(p0), PHPQT_TAG_QFocusEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QMdiSubWindow::childEvent(std::declval<QChildEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "childEvent");
    if (fn == nullptr) { QMdiSubWindow::childEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QChildEvent> t0(const_cast<QChildEvent *>(p0), PHPQT_TAG_QChildEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

int PhpQtQMdiSubWindow::devType() const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::devType()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "devType");
    if (fn == nullptr) { return QWidget::devType(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::devType(); }
    int r = static_cast<int>(phpqt::arg_long(&ret));
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQMdiSubWindow::setVisible(bool p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::setVisible(std::declval<bool>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "setVisible");
    if (fn == nullptr) { QWidget::setVisible(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    ZVAL_BOOL(&argv[1], (p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

int PhpQtQMdiSubWindow::heightForWidth(int p0) const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::heightForWidth(std::declval<int>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "heightForWidth");
    if (fn == nullptr) { return QWidget::heightForWidth(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::heightForWidth(p0); }
    int r = static_cast<int>(phpqt::arg_long(&ret));
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQMdiSubWindow::hasHeightForWidth() const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::hasHeightForWidth()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "hasHeightForWidth");
    if (fn == nullptr) { return QWidget::hasHeightForWidth(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::hasHeightForWidth(); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

QPaintEngine * PhpQtQMdiSubWindow::paintEngine() const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::paintEngine()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "paintEngine");
    if (fn == nullptr) { return QWidget::paintEngine(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::paintEngine(); }
    QPaintEngine * r = phpqt::as<QPaintEngine>(&ret, PHPQT_TAG_QPaintEngine);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQMdiSubWindow::wheelEvent(QWheelEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::wheelEvent(std::declval<QWheelEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "wheelEvent");
    if (fn == nullptr) { QWidget::wheelEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QWheelEvent> t0(const_cast<QWheelEvent *>(p0), PHPQT_TAG_QWheelEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::keyReleaseEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::keyReleaseEvent(std::declval<QKeyEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "keyReleaseEvent");
    if (fn == nullptr) { QWidget::keyReleaseEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QKeyEvent> t0(const_cast<QKeyEvent *>(p0), PHPQT_TAG_QKeyEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::enterEvent(QEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::enterEvent(std::declval<QEnterEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "enterEvent");
    if (fn == nullptr) { QWidget::enterEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QEnterEvent> t0(const_cast<QEnterEvent *>(p0), PHPQT_TAG_QEnterEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::tabletEvent(QTabletEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::tabletEvent(std::declval<QTabletEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "tabletEvent");
    if (fn == nullptr) { QWidget::tabletEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QTabletEvent> t0(const_cast<QTabletEvent *>(p0), PHPQT_TAG_QTabletEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::actionEvent(QActionEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::actionEvent(std::declval<QActionEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "actionEvent");
    if (fn == nullptr) { QWidget::actionEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QActionEvent> t0(const_cast<QActionEvent *>(p0), PHPQT_TAG_QActionEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::dragEnterEvent(QDragEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::dragEnterEvent(std::declval<QDragEnterEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "dragEnterEvent");
    if (fn == nullptr) { QWidget::dragEnterEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QDragEnterEvent> t0(const_cast<QDragEnterEvent *>(p0), PHPQT_TAG_QDragEnterEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::dragMoveEvent(QDragMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::dragMoveEvent(std::declval<QDragMoveEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "dragMoveEvent");
    if (fn == nullptr) { QWidget::dragMoveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QDragMoveEvent> t0(const_cast<QDragMoveEvent *>(p0), PHPQT_TAG_QDragMoveEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::dragLeaveEvent(QDragLeaveEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::dragLeaveEvent(std::declval<QDragLeaveEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "dragLeaveEvent");
    if (fn == nullptr) { QWidget::dragLeaveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QDragLeaveEvent> t0(const_cast<QDragLeaveEvent *>(p0), PHPQT_TAG_QDragLeaveEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::dropEvent(QDropEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::dropEvent(std::declval<QDropEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "dropEvent");
    if (fn == nullptr) { QWidget::dropEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QDropEvent> t0(const_cast<QDropEvent *>(p0), PHPQT_TAG_QDropEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

int PhpQtQMdiSubWindow::metric(QPaintDevice::PaintDeviceMetric p0) const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::metric(std::declval<QPaintDevice::PaintDeviceMetric>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "metric");
    if (fn == nullptr) { return QWidget::metric(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::metric(p0); }
    int r = static_cast<int>(phpqt::arg_long(&ret));
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQMdiSubWindow::initPainter(QPainter * p0) const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::initPainter(std::declval<QPainter *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "initPainter");
    if (fn == nullptr) { QWidget::initPainter(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QPainter> t0(const_cast<QPainter *>(p0), PHPQT_TAG_QPainter);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

QPainter * PhpQtQMdiSubWindow::sharedPainter() const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::sharedPainter()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "sharedPainter");
    if (fn == nullptr) { return QWidget::sharedPainter(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::sharedPainter(); }
    QPainter * r = phpqt::as<QPainter>(&ret, PHPQT_TAG_QPainter);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQMdiSubWindow::inputMethodEvent(QInputMethodEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::inputMethodEvent(std::declval<QInputMethodEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "inputMethodEvent");
    if (fn == nullptr) { QWidget::inputMethodEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QInputMethodEvent> t0(const_cast<QInputMethodEvent *>(p0), PHPQT_TAG_QInputMethodEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

QVariant PhpQtQMdiSubWindow::inputMethodQuery(Qt::InputMethodQuery p0) const noexcept(noexcept(std::declval<const PhpQtQMdiSubWindow &>().QWidget::inputMethodQuery(std::declval<Qt::InputMethodQuery>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this))), "inputMethodQuery");
    if (fn == nullptr) { return QWidget::inputMethodQuery(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QMdiSubWindow *>(static_cast<const QMdiSubWindow *>(this)), PHPQT_TAG_QMdiSubWindow, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::inputMethodQuery(p0); }
    QVariant r = phpqt::arg_variant(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQMdiSubWindow::focusNextPrevChild(bool p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QWidget::focusNextPrevChild(std::declval<bool>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "focusNextPrevChild");
    if (fn == nullptr) { return QWidget::focusNextPrevChild(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    ZVAL_BOOL(&argv[1], (p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::focusNextPrevChild(p0); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQMdiSubWindow::customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QObject::customEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "customEvent");
    if (fn == nullptr) { QObject::customEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QObject::connectNotify(std::declval<const QMetaMethod &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "connectNotify");
    if (fn == nullptr) { QObject::connectNotify(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMetaMethod> t0(const_cast<QMetaMethod *>(&p0), PHPQT_TAG_QMetaMethod);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQMdiSubWindow::disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQMdiSubWindow &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QMdiSubWindow *>(this)), "disconnectNotify");
    if (fn == nullptr) { QObject::disconnectNotify(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QMdiSubWindow *>(this), PHPQT_TAG_QMdiSubWindow, false));
    phpqt::Temp<QMetaMethod> t0(const_cast<QMetaMethod *>(&p0), PHPQT_TAG_QMetaMethod);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

const char *const PhpQtQMdiSubWindow::kOverridable[] = { "actionEvent", "changeEvent", "childEvent", "closeEvent", "connectNotify", "contextMenuEvent", "customEvent", "devType", "disconnectNotify", "dragEnterEvent", "dragLeaveEvent", "dragMoveEvent", "dropEvent", "enterEvent", "event", "eventFilter", "focusInEvent", "focusNextPrevChild", "focusOutEvent", "hasHeightForWidth", "heightForWidth", "hideEvent", "initPainter", "inputMethodEvent", "inputMethodQuery", "keyPressEvent", "keyReleaseEvent", "leaveEvent", "metric", "minimumSizeHint", "mouseDoubleClickEvent", "mouseMoveEvent", "mousePressEvent", "mouseReleaseEvent", "moveEvent", "paintEngine", "paintEvent", "resizeEvent", "setVisible", "sharedPainter", "showEvent", "sizeHint", "tabletEvent", "timerEvent", "wheelEvent", nullptr };
