/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include "widgets-qtextbrowser-shell.h"

PhpQtQTextBrowser::~PhpQtQTextBrowser()
{
    phpqt::forget_canon(phpqt::canon_impl(static_cast<QTextBrowser *>(this)));
}

QVariant PhpQtQTextBrowser::loadResource(int p0, const QUrl & p1) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::loadResource(std::declval<int>(), std::declval<const QUrl &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "loadResource");
    if (fn == nullptr) { return QTextBrowser::loadResource(p0, p1); }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    phpqt::Temp<QUrl> t1(const_cast<QUrl *>(&p1), PHPQT_TAG_QUrl);
    ZVAL_LONG(&argv[2], t1.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QTextBrowser::loadResource(p0, p1); }
    QVariant r = phpqt::arg_variant(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::backward() noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::backward()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "backward");
    if (fn == nullptr) { QTextBrowser::backward(); return; }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::forward() noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::forward()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "forward");
    if (fn == nullptr) { QTextBrowser::forward(); return; }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::home() noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::home()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "home");
    if (fn == nullptr) { QTextBrowser::home(); return; }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::reload() noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::reload()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "reload");
    if (fn == nullptr) { QTextBrowser::reload(); return; }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

bool PhpQtQTextBrowser::event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::event(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "event");
    if (fn == nullptr) { return QTextBrowser::event(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QTextBrowser::event(p0); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::keyPressEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::keyPressEvent(std::declval<QKeyEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "keyPressEvent");
    if (fn == nullptr) { QTextBrowser::keyPressEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QKeyEvent> t0(const_cast<QKeyEvent *>(p0), PHPQT_TAG_QKeyEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::mouseMoveEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::mouseMoveEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "mouseMoveEvent");
    if (fn == nullptr) { QTextBrowser::mouseMoveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::mousePressEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::mousePressEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "mousePressEvent");
    if (fn == nullptr) { QTextBrowser::mousePressEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::mouseReleaseEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::mouseReleaseEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "mouseReleaseEvent");
    if (fn == nullptr) { QTextBrowser::mouseReleaseEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::focusOutEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::focusOutEvent(std::declval<QFocusEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "focusOutEvent");
    if (fn == nullptr) { QTextBrowser::focusOutEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QFocusEvent> t0(const_cast<QFocusEvent *>(p0), PHPQT_TAG_QFocusEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

bool PhpQtQTextBrowser::focusNextPrevChild(bool p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::focusNextPrevChild(std::declval<bool>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "focusNextPrevChild");
    if (fn == nullptr) { return QTextBrowser::focusNextPrevChild(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_BOOL(&argv[1], (p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QTextBrowser::focusNextPrevChild(p0); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::paintEvent(QPaintEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::paintEvent(std::declval<QPaintEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "paintEvent");
    if (fn == nullptr) { QTextBrowser::paintEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QPaintEvent> t0(const_cast<QPaintEvent *>(p0), PHPQT_TAG_QPaintEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::doSetSource(const QUrl & p0, QTextDocument::ResourceType p1) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextBrowser::doSetSource(std::declval<const QUrl &>(), std::declval<QTextDocument::ResourceType>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "doSetSource");
    if (fn == nullptr) { QTextBrowser::doSetSource(p0, p1); return; }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QUrl> t0(const_cast<QUrl *>(&p0), PHPQT_TAG_QUrl);
    ZVAL_LONG(&argv[1], t0.h);
    ZVAL_LONG(&argv[2], static_cast<zend_long>(p1));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

QVariant PhpQtQTextBrowser::inputMethodQuery(Qt::InputMethodQuery p0) const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QTextEdit::inputMethodQuery(std::declval<Qt::InputMethodQuery>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "inputMethodQuery");
    if (fn == nullptr) { return QTextEdit::inputMethodQuery(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QTextEdit::inputMethodQuery(p0); }
    QVariant r = phpqt::arg_variant(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::timerEvent(std::declval<QTimerEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "timerEvent");
    if (fn == nullptr) { QTextEdit::timerEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QTimerEvent> t0(const_cast<QTimerEvent *>(p0), PHPQT_TAG_QTimerEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::keyReleaseEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::keyReleaseEvent(std::declval<QKeyEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "keyReleaseEvent");
    if (fn == nullptr) { QTextEdit::keyReleaseEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QKeyEvent> t0(const_cast<QKeyEvent *>(p0), PHPQT_TAG_QKeyEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::resizeEvent(QResizeEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::resizeEvent(std::declval<QResizeEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "resizeEvent");
    if (fn == nullptr) { QTextEdit::resizeEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QResizeEvent> t0(const_cast<QResizeEvent *>(p0), PHPQT_TAG_QResizeEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::mouseDoubleClickEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::mouseDoubleClickEvent(std::declval<QMouseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "mouseDoubleClickEvent");
    if (fn == nullptr) { QTextEdit::mouseDoubleClickEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMouseEvent> t0(const_cast<QMouseEvent *>(p0), PHPQT_TAG_QMouseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::contextMenuEvent(QContextMenuEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::contextMenuEvent(std::declval<QContextMenuEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "contextMenuEvent");
    if (fn == nullptr) { QTextEdit::contextMenuEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QContextMenuEvent> t0(const_cast<QContextMenuEvent *>(p0), PHPQT_TAG_QContextMenuEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::dragEnterEvent(QDragEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::dragEnterEvent(std::declval<QDragEnterEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "dragEnterEvent");
    if (fn == nullptr) { QTextEdit::dragEnterEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QDragEnterEvent> t0(const_cast<QDragEnterEvent *>(p0), PHPQT_TAG_QDragEnterEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::dragLeaveEvent(QDragLeaveEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::dragLeaveEvent(std::declval<QDragLeaveEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "dragLeaveEvent");
    if (fn == nullptr) { QTextEdit::dragLeaveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QDragLeaveEvent> t0(const_cast<QDragLeaveEvent *>(p0), PHPQT_TAG_QDragLeaveEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::dragMoveEvent(QDragMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::dragMoveEvent(std::declval<QDragMoveEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "dragMoveEvent");
    if (fn == nullptr) { QTextEdit::dragMoveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QDragMoveEvent> t0(const_cast<QDragMoveEvent *>(p0), PHPQT_TAG_QDragMoveEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::dropEvent(QDropEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::dropEvent(std::declval<QDropEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "dropEvent");
    if (fn == nullptr) { QTextEdit::dropEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QDropEvent> t0(const_cast<QDropEvent *>(p0), PHPQT_TAG_QDropEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::focusInEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::focusInEvent(std::declval<QFocusEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "focusInEvent");
    if (fn == nullptr) { QTextEdit::focusInEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QFocusEvent> t0(const_cast<QFocusEvent *>(p0), PHPQT_TAG_QFocusEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::showEvent(QShowEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::showEvent(std::declval<QShowEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "showEvent");
    if (fn == nullptr) { QTextEdit::showEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QShowEvent> t0(const_cast<QShowEvent *>(p0), PHPQT_TAG_QShowEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::changeEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::changeEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "changeEvent");
    if (fn == nullptr) { QTextEdit::changeEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::wheelEvent(QWheelEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::wheelEvent(std::declval<QWheelEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "wheelEvent");
    if (fn == nullptr) { QTextEdit::wheelEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QWheelEvent> t0(const_cast<QWheelEvent *>(p0), PHPQT_TAG_QWheelEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

QMimeData * PhpQtQTextBrowser::createMimeDataFromSelection() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QTextEdit::createMimeDataFromSelection()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "createMimeDataFromSelection");
    if (fn == nullptr) { return QTextEdit::createMimeDataFromSelection(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QTextEdit::createMimeDataFromSelection(); }
    QMimeData * r = phpqt::as<QMimeData>(&ret, PHPQT_TAG_QMimeData);
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQTextBrowser::canInsertFromMimeData(const QMimeData * p0) const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QTextEdit::canInsertFromMimeData(std::declval<const QMimeData *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "canInsertFromMimeData");
    if (fn == nullptr) { return QTextEdit::canInsertFromMimeData(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], phpqt::reg_out(const_cast<QMimeData *>(p0), PHPQT_TAG_QMimeData));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QTextEdit::canInsertFromMimeData(p0); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::insertFromMimeData(const QMimeData * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::insertFromMimeData(std::declval<const QMimeData *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "insertFromMimeData");
    if (fn == nullptr) { QTextEdit::insertFromMimeData(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], phpqt::reg_out(const_cast<QMimeData *>(p0), PHPQT_TAG_QMimeData));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::inputMethodEvent(QInputMethodEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::inputMethodEvent(std::declval<QInputMethodEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "inputMethodEvent");
    if (fn == nullptr) { QTextEdit::inputMethodEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QInputMethodEvent> t0(const_cast<QInputMethodEvent *>(p0), PHPQT_TAG_QInputMethodEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::scrollContentsBy(int p0, int p1) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::scrollContentsBy(std::declval<int>(), std::declval<int>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "scrollContentsBy");
    if (fn == nullptr) { QTextEdit::scrollContentsBy(p0, p1); return; }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    ZVAL_LONG(&argv[2], static_cast<zend_long>(p1));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::doSetTextCursor(const QTextCursor & p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QTextEdit::doSetTextCursor(std::declval<const QTextCursor &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "doSetTextCursor");
    if (fn == nullptr) { QTextEdit::doSetTextCursor(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QTextCursor> t0(const_cast<QTextCursor *>(&p0), PHPQT_TAG_QTextCursor);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

QSize PhpQtQTextBrowser::minimumSizeHint() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QAbstractScrollArea::minimumSizeHint()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "minimumSizeHint");
    if (fn == nullptr) { return QAbstractScrollArea::minimumSizeHint(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QAbstractScrollArea::minimumSizeHint(); }
    QSize r = phpqt::arg_geom_QSize(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

QSize PhpQtQTextBrowser::sizeHint() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QAbstractScrollArea::sizeHint()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "sizeHint");
    if (fn == nullptr) { return QAbstractScrollArea::sizeHint(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QAbstractScrollArea::sizeHint(); }
    QSize r = phpqt::arg_geom_QSize(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::setupViewport(QWidget * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QAbstractScrollArea::setupViewport(std::declval<QWidget *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "setupViewport");
    if (fn == nullptr) { QAbstractScrollArea::setupViewport(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], phpqt::reg_out(const_cast<QWidget *>(p0), PHPQT_TAG_QWidget));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

bool PhpQtQTextBrowser::eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QAbstractScrollArea::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "eventFilter");
    if (fn == nullptr) { return QAbstractScrollArea::eventFilter(p0, p1); }
    zval argv[3];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], phpqt::reg_out(const_cast<QObject *>(p0), PHPQT_TAG_QObject));
    phpqt::Temp<QEvent> t1(const_cast<QEvent *>(p1), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[2], t1.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 3, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QAbstractScrollArea::eventFilter(p0, p1); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQTextBrowser::viewportEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QAbstractScrollArea::viewportEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "viewportEvent");
    if (fn == nullptr) { return QAbstractScrollArea::viewportEvent(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QAbstractScrollArea::viewportEvent(p0); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

QSize PhpQtQTextBrowser::viewportSizeHint() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QAbstractScrollArea::viewportSizeHint()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "viewportSizeHint");
    if (fn == nullptr) { return QAbstractScrollArea::viewportSizeHint(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QAbstractScrollArea::viewportSizeHint(); }
    QSize r = phpqt::arg_geom_QSize(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::initStyleOption(QStyleOptionFrame * p0) const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QFrame::initStyleOption(std::declval<QStyleOptionFrame *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "initStyleOption");
    if (fn == nullptr) { QFrame::initStyleOption(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QStyleOptionFrame> t0(const_cast<QStyleOptionFrame *>(p0), PHPQT_TAG_QStyleOptionFrame);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

int PhpQtQTextBrowser::devType() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::devType()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "devType");
    if (fn == nullptr) { return QWidget::devType(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::devType(); }
    int r = static_cast<int>(phpqt::arg_long(&ret));
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::setVisible(bool p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::setVisible(std::declval<bool>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "setVisible");
    if (fn == nullptr) { QWidget::setVisible(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    ZVAL_BOOL(&argv[1], (p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

int PhpQtQTextBrowser::heightForWidth(int p0) const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::heightForWidth(std::declval<int>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "heightForWidth");
    if (fn == nullptr) { return QWidget::heightForWidth(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::heightForWidth(p0); }
    int r = static_cast<int>(phpqt::arg_long(&ret));
    zval_ptr_dtor(&ret);
    return r;
}

bool PhpQtQTextBrowser::hasHeightForWidth() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::hasHeightForWidth()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "hasHeightForWidth");
    if (fn == nullptr) { return QWidget::hasHeightForWidth(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::hasHeightForWidth(); }
    bool r = phpqt::arg_bool(&ret);
    zval_ptr_dtor(&ret);
    return r;
}

QPaintEngine * PhpQtQTextBrowser::paintEngine() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::paintEngine()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "paintEngine");
    if (fn == nullptr) { return QWidget::paintEngine(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::paintEngine(); }
    QPaintEngine * r = phpqt::as<QPaintEngine>(&ret, PHPQT_TAG_QPaintEngine);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::enterEvent(QEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::enterEvent(std::declval<QEnterEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "enterEvent");
    if (fn == nullptr) { QWidget::enterEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QEnterEvent> t0(const_cast<QEnterEvent *>(p0), PHPQT_TAG_QEnterEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::leaveEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::leaveEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "leaveEvent");
    if (fn == nullptr) { QWidget::leaveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::moveEvent(QMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::moveEvent(std::declval<QMoveEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "moveEvent");
    if (fn == nullptr) { QWidget::moveEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMoveEvent> t0(const_cast<QMoveEvent *>(p0), PHPQT_TAG_QMoveEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::closeEvent(QCloseEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::closeEvent(std::declval<QCloseEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "closeEvent");
    if (fn == nullptr) { QWidget::closeEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QCloseEvent> t0(const_cast<QCloseEvent *>(p0), PHPQT_TAG_QCloseEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::tabletEvent(QTabletEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::tabletEvent(std::declval<QTabletEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "tabletEvent");
    if (fn == nullptr) { QWidget::tabletEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QTabletEvent> t0(const_cast<QTabletEvent *>(p0), PHPQT_TAG_QTabletEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::actionEvent(QActionEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::actionEvent(std::declval<QActionEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "actionEvent");
    if (fn == nullptr) { QWidget::actionEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QActionEvent> t0(const_cast<QActionEvent *>(p0), PHPQT_TAG_QActionEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::hideEvent(QHideEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QWidget::hideEvent(std::declval<QHideEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "hideEvent");
    if (fn == nullptr) { QWidget::hideEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QHideEvent> t0(const_cast<QHideEvent *>(p0), PHPQT_TAG_QHideEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

int PhpQtQTextBrowser::metric(QPaintDevice::PaintDeviceMetric p0) const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::metric(std::declval<QPaintDevice::PaintDeviceMetric>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "metric");
    if (fn == nullptr) { return QWidget::metric(p0); }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    ZVAL_LONG(&argv[1], static_cast<zend_long>(p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::metric(p0); }
    int r = static_cast<int>(phpqt::arg_long(&ret));
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::initPainter(QPainter * p0) const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::initPainter(std::declval<QPainter *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "initPainter");
    if (fn == nullptr) { QWidget::initPainter(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QPainter> t0(const_cast<QPainter *>(p0), PHPQT_TAG_QPainter);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

QPainter * PhpQtQTextBrowser::sharedPainter() const noexcept(noexcept(std::declval<const PhpQtQTextBrowser &>().QWidget::sharedPainter()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this))), "sharedPainter");
    if (fn == nullptr) { return QWidget::sharedPainter(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QTextBrowser *>(static_cast<const QTextBrowser *>(this)), PHPQT_TAG_QTextBrowser, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QWidget::sharedPainter(); }
    QPainter * r = phpqt::as<QPainter>(&ret, PHPQT_TAG_QPainter);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQTextBrowser::childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QObject::childEvent(std::declval<QChildEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "childEvent");
    if (fn == nullptr) { QObject::childEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QChildEvent> t0(const_cast<QChildEvent *>(p0), PHPQT_TAG_QChildEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QObject::customEvent(std::declval<QEvent *>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "customEvent");
    if (fn == nullptr) { QObject::customEvent(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QEvent> t0(const_cast<QEvent *>(p0), PHPQT_TAG_QEvent);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QObject::connectNotify(std::declval<const QMetaMethod &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "connectNotify");
    if (fn == nullptr) { QObject::connectNotify(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMetaMethod> t0(const_cast<QMetaMethod *>(&p0), PHPQT_TAG_QMetaMethod);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

void PhpQtQTextBrowser::disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQTextBrowser &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QTextBrowser *>(this)), "disconnectNotify");
    if (fn == nullptr) { QObject::disconnectNotify(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QTextBrowser *>(this), PHPQT_TAG_QTextBrowser, false));
    phpqt::Temp<QMetaMethod> t0(const_cast<QMetaMethod *>(&p0), PHPQT_TAG_QMetaMethod);
    ZVAL_LONG(&argv[1], t0.h);
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

const char *const PhpQtQTextBrowser::kOverridable[] = { "actionEvent", "backward", "canInsertFromMimeData", "changeEvent", "childEvent", "closeEvent", "connectNotify", "contextMenuEvent", "createMimeDataFromSelection", "customEvent", "devType", "disconnectNotify", "doSetSource", "doSetTextCursor", "dragEnterEvent", "dragLeaveEvent", "dragMoveEvent", "dropEvent", "enterEvent", "event", "eventFilter", "focusInEvent", "focusNextPrevChild", "focusOutEvent", "forward", "hasHeightForWidth", "heightForWidth", "hideEvent", "home", "initPainter", "initStyleOption", "inputMethodEvent", "inputMethodQuery", "insertFromMimeData", "keyPressEvent", "keyReleaseEvent", "leaveEvent", "loadResource", "metric", "minimumSizeHint", "mouseDoubleClickEvent", "mouseMoveEvent", "mousePressEvent", "mouseReleaseEvent", "moveEvent", "paintEngine", "paintEvent", "reload", "resizeEvent", "scrollContentsBy", "setVisible", "setupViewport", "sharedPainter", "showEvent", "sizeHint", "tabletEvent", "timerEvent", "viewportEvent", "viewportSizeHint", "wheelEvent", nullptr };
