/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QTIMEEDIT_H
#define PHPQT_WIDGETS_QTIMEEDIT_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QTimeEdit staticMetaObject() -> int */
zend_long phpqt_qtimeedit_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QTimeEdit tr(var s, var c = null, int n = -1) -> string */
void phpqt_qtimeedit_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QTimeEdit(QWidget * parent) */
/*@zep Widgets\QTimeEdit new(int parent = 0) -> int */
zend_long phpqt_qtimeedit_new(zval *p_parent);

/*@ast QTimeEdit(QTime time, QWidget * parent) */
/*@zep Widgets\QTimeEdit newQTimeQWidget(int time, int parent = 0) -> int */
zend_long phpqt_qtimeedit_new_q_time_q_widget(zval *p_time, zval *p_parent);

/*@ast void userTimeChanged(QTime time) */
/*@zep Widgets\QTimeEdit userTimeChanged(int handle, int time) -> void */
void phpqt_qtimeedit_user_time_changed(zval *p_handle, zval *p_time);

/*@override Widgets\QTimeEdit sizeHint QSize sizeHint() const */
/*@override Widgets\QTimeEdit clear void clear() */
/*@override Widgets\QTimeEdit stepBy void stepBy(int steps) */
/*@override Widgets\QTimeEdit event bool event(QEvent * event) */
/*@override Widgets\QTimeEdit keyPressEvent void keyPressEvent(QKeyEvent * event) */
/*@override Widgets\QTimeEdit wheelEvent void wheelEvent(QWheelEvent * event) */
/*@override Widgets\QTimeEdit focusInEvent void focusInEvent(QFocusEvent * event) */
/*@override Widgets\QTimeEdit focusNextPrevChild bool focusNextPrevChild(bool next) */
/*@reserved-override Widgets\QTimeEdit raw-pointer QValidator::State validate(QString & input, int & pos) const */
/*@reserved-override Widgets\QTimeEdit raw-pointer void fixup(QString & input) const */
/*@override Widgets\QTimeEdit dateTimeFromText QDateTime dateTimeFromText(const QString & text) const */
/*@override Widgets\QTimeEdit textFromDateTime QString textFromDateTime(const QDateTime & dt) const */
/*@override Widgets\QTimeEdit stepEnabled QAbstractSpinBox::StepEnabled stepEnabled() const */
/*@override Widgets\QTimeEdit mousePressEvent void mousePressEvent(QMouseEvent * event) */
/*@override Widgets\QTimeEdit paintEvent void paintEvent(QPaintEvent * event) */
/*@override Widgets\QTimeEdit initStyleOption void initStyleOption(QStyleOptionSpinBox * option) const */
/*@override Widgets\QTimeEdit minimumSizeHint QSize minimumSizeHint() const */
/*@override Widgets\QTimeEdit inputMethodQuery QVariant inputMethodQuery(Qt::InputMethodQuery) const */
/*@override Widgets\QTimeEdit resizeEvent void resizeEvent(QResizeEvent * event) */
/*@override Widgets\QTimeEdit keyReleaseEvent void keyReleaseEvent(QKeyEvent * event) */
/*@override Widgets\QTimeEdit focusOutEvent void focusOutEvent(QFocusEvent * event) */
/*@override Widgets\QTimeEdit contextMenuEvent void contextMenuEvent(QContextMenuEvent * event) */
/*@override Widgets\QTimeEdit changeEvent void changeEvent(QEvent * event) */
/*@override Widgets\QTimeEdit closeEvent void closeEvent(QCloseEvent * event) */
/*@override Widgets\QTimeEdit hideEvent void hideEvent(QHideEvent * event) */
/*@override Widgets\QTimeEdit mouseReleaseEvent void mouseReleaseEvent(QMouseEvent * event) */
/*@override Widgets\QTimeEdit mouseMoveEvent void mouseMoveEvent(QMouseEvent * event) */
/*@override Widgets\QTimeEdit timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QTimeEdit showEvent void showEvent(QShowEvent * event) */
/*@override Widgets\QTimeEdit devType int devType() const */
/*@override Widgets\QTimeEdit setVisible void setVisible(bool visible) */
/*@override Widgets\QTimeEdit heightForWidth int heightForWidth(int) const */
/*@override Widgets\QTimeEdit hasHeightForWidth bool hasHeightForWidth() const */
/*@override Widgets\QTimeEdit paintEngine QPaintEngine * paintEngine() const */
/*@override Widgets\QTimeEdit mouseDoubleClickEvent void mouseDoubleClickEvent(QMouseEvent * event) */
/*@override Widgets\QTimeEdit enterEvent void enterEvent(QEnterEvent * event) */
/*@override Widgets\QTimeEdit leaveEvent void leaveEvent(QEvent * event) */
/*@override Widgets\QTimeEdit moveEvent void moveEvent(QMoveEvent * event) */
/*@override Widgets\QTimeEdit tabletEvent void tabletEvent(QTabletEvent * event) */
/*@override Widgets\QTimeEdit actionEvent void actionEvent(QActionEvent * event) */
/*@override Widgets\QTimeEdit dragEnterEvent void dragEnterEvent(QDragEnterEvent * event) */
/*@override Widgets\QTimeEdit dragMoveEvent void dragMoveEvent(QDragMoveEvent * event) */
/*@override Widgets\QTimeEdit dragLeaveEvent void dragLeaveEvent(QDragLeaveEvent * event) */
/*@override Widgets\QTimeEdit dropEvent void dropEvent(QDropEvent * event) */
/*@reserved-override Widgets\QTimeEdit raw-pointer bool nativeEvent(const QByteArray & eventType, void * message, qintptr * result) */
/*@override Widgets\QTimeEdit metric int metric(QPaintDevice::PaintDeviceMetric) const */
/*@override Widgets\QTimeEdit initPainter void initPainter(QPainter * painter) const */
/*@reserved-override Widgets\QTimeEdit raw-pointer QPaintDevice * redirected(QPoint * offset) const */
/*@override Widgets\QTimeEdit sharedPainter QPainter * sharedPainter() const */
/*@override Widgets\QTimeEdit inputMethodEvent void inputMethodEvent(QInputMethodEvent *) */
/*@override Widgets\QTimeEdit eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Widgets\QTimeEdit childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QTimeEdit customEvent void customEvent(QEvent * event) */
/*@override Widgets\QTimeEdit connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QTimeEdit disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
