/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qcoreevent.h>
#include <QtCore/qflags.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qsize.h>
#include <QtGui/qevent.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qpainter.h>
#include <QtWidgets/qabstractspinbox.h>
#include <QtWidgets/qspinbox.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qwidget.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQSpinBox : public QSpinBox {
public:
    PhpQtQSpinBox(QWidget * p0) : QSpinBox(p0) {}
    ~PhpQtQSpinBox();
    bool event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QSpinBox::event(std::declval<QEvent *>()))) override;
    int valueFromText(const QString & p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QSpinBox::valueFromText(std::declval<const QString &>()))) override;
    QString textFromValue(int p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QSpinBox::textFromValue(std::declval<int>()))) override;
    QSize sizeHint() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QAbstractSpinBox::sizeHint())) override;
    QSize minimumSizeHint() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QAbstractSpinBox::minimumSizeHint())) override;
    QVariant inputMethodQuery(Qt::InputMethodQuery p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QAbstractSpinBox::inputMethodQuery(std::declval<Qt::InputMethodQuery>()))) override;
    void stepBy(int p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::stepBy(std::declval<int>()))) override;
    void clear() noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::clear())) override;
    void resizeEvent(QResizeEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::resizeEvent(std::declval<QResizeEvent *>()))) override;
    void keyPressEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::keyPressEvent(std::declval<QKeyEvent *>()))) override;
    void keyReleaseEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::keyReleaseEvent(std::declval<QKeyEvent *>()))) override;
    void wheelEvent(QWheelEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::wheelEvent(std::declval<QWheelEvent *>()))) override;
    void focusInEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::focusInEvent(std::declval<QFocusEvent *>()))) override;
    void focusOutEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::focusOutEvent(std::declval<QFocusEvent *>()))) override;
    void contextMenuEvent(QContextMenuEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::contextMenuEvent(std::declval<QContextMenuEvent *>()))) override;
    void changeEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::changeEvent(std::declval<QEvent *>()))) override;
    void closeEvent(QCloseEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::closeEvent(std::declval<QCloseEvent *>()))) override;
    void hideEvent(QHideEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::hideEvent(std::declval<QHideEvent *>()))) override;
    void mousePressEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::mousePressEvent(std::declval<QMouseEvent *>()))) override;
    void mouseReleaseEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::mouseReleaseEvent(std::declval<QMouseEvent *>()))) override;
    void mouseMoveEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::mouseMoveEvent(std::declval<QMouseEvent *>()))) override;
    void timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::timerEvent(std::declval<QTimerEvent *>()))) override;
    void paintEvent(QPaintEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::paintEvent(std::declval<QPaintEvent *>()))) override;
    void showEvent(QShowEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QAbstractSpinBox::showEvent(std::declval<QShowEvent *>()))) override;
    void initStyleOption(QStyleOptionSpinBox * p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QAbstractSpinBox::initStyleOption(std::declval<QStyleOptionSpinBox *>()))) override;
    QAbstractSpinBox::StepEnabled stepEnabled() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QAbstractSpinBox::stepEnabled())) override;
    int devType() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::devType())) override;
    void setVisible(bool p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::setVisible(std::declval<bool>()))) override;
    int heightForWidth(int p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::heightForWidth(std::declval<int>()))) override;
    bool hasHeightForWidth() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::hasHeightForWidth())) override;
    QPaintEngine * paintEngine() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::paintEngine())) override;
    void mouseDoubleClickEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::mouseDoubleClickEvent(std::declval<QMouseEvent *>()))) override;
    void enterEvent(QEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::enterEvent(std::declval<QEnterEvent *>()))) override;
    void leaveEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::leaveEvent(std::declval<QEvent *>()))) override;
    void moveEvent(QMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::moveEvent(std::declval<QMoveEvent *>()))) override;
    void tabletEvent(QTabletEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::tabletEvent(std::declval<QTabletEvent *>()))) override;
    void actionEvent(QActionEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::actionEvent(std::declval<QActionEvent *>()))) override;
    void dragEnterEvent(QDragEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::dragEnterEvent(std::declval<QDragEnterEvent *>()))) override;
    void dragMoveEvent(QDragMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::dragMoveEvent(std::declval<QDragMoveEvent *>()))) override;
    void dragLeaveEvent(QDragLeaveEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::dragLeaveEvent(std::declval<QDragLeaveEvent *>()))) override;
    void dropEvent(QDropEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::dropEvent(std::declval<QDropEvent *>()))) override;
    int metric(QPaintDevice::PaintDeviceMetric p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::metric(std::declval<QPaintDevice::PaintDeviceMetric>()))) override;
    void initPainter(QPainter * p0) const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::initPainter(std::declval<QPainter *>()))) override;
    QPainter * sharedPainter() const noexcept(noexcept(std::declval<const PhpQtQSpinBox &>().QWidget::sharedPainter())) override;
    void inputMethodEvent(QInputMethodEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::inputMethodEvent(std::declval<QInputMethodEvent *>()))) override;
    bool focusNextPrevChild(bool p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QWidget::focusNextPrevChild(std::declval<bool>()))) override;
    bool eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QObject::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>()))) override;
    void childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QObject::childEvent(std::declval<QChildEvent *>()))) override;
    void customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QObject::customEvent(std::declval<QEvent *>()))) override;
    void connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QObject::connectNotify(std::declval<const QMetaMethod &>()))) override;
    void disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQSpinBox &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>()))) override;
    bool phpqt_fwd_event(QEvent * p0) { return event(p0); }
    QValidator::State phpqt_fwd_validate(QString & p0, int & p1) const { return validate(p0, p1); }
    int phpqt_fwd_valueFromText(const QString & p0) const { return valueFromText(p0); }
    QString phpqt_fwd_textFromValue(int p0) const { return textFromValue(p0); }
    void phpqt_fwd_fixup(QString & p0) const { fixup(p0); }
    static const char *const kOverridable[];
};
