/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QSTATUSBAR_H
#define PHPQT_WIDGETS_QSTATUSBAR_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QStatusBar staticMetaObject() -> int */
zend_long phpqt_qstatusbar_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QStatusBar tr(var s, var c = null, int n = -1) -> string */
void phpqt_qstatusbar_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QStatusBar(QWidget * parent) */
/*@zep Widgets\QStatusBar new(int parent = 0) -> int */
zend_long phpqt_qstatusbar_new(zval *p_parent);

/*@ast void addWidget(QWidget * widget, int stretch) */
/*@zep Widgets\QStatusBar addWidget(int handle, int widget, int stretch = 0) -> void */
void phpqt_qstatusbar_add_widget(zval *p_handle, zval *p_widget, zval *p_stretch);

/*@ast int insertWidget(int index, QWidget * widget, int stretch) */
/*@zep Widgets\QStatusBar insertWidget(int handle, int index, int widget, int stretch = 0) -> int */
zend_long phpqt_qstatusbar_insert_widget(zval *p_handle, zval *p_index, zval *p_widget, zval *p_stretch);

/*@ast void addPermanentWidget(QWidget * widget, int stretch) */
/*@zep Widgets\QStatusBar addPermanentWidget(int handle, int widget, int stretch = 0) -> void */
void phpqt_qstatusbar_add_permanent_widget(zval *p_handle, zval *p_widget, zval *p_stretch);

/*@ast int insertPermanentWidget(int index, QWidget * widget, int stretch) */
/*@zep Widgets\QStatusBar insertPermanentWidget(int handle, int index, int widget, int stretch = 0) -> int */
zend_long phpqt_qstatusbar_insert_permanent_widget(zval *p_handle, zval *p_index, zval *p_widget, zval *p_stretch);

/*@ast void removeWidget(QWidget * widget) */
/*@zep Widgets\QStatusBar removeWidget(int handle, int widget) -> void */
void phpqt_qstatusbar_remove_widget(zval *p_handle, zval *p_widget);

/*@ast void setSizeGripEnabled(bool) */
/*@zep Widgets\QStatusBar setSizeGripEnabled(int handle, bool arg0) -> void */
void phpqt_qstatusbar_set_size_grip_enabled(zval *p_handle, zval *p_arg0);

/*@ast bool isSizeGripEnabled() const */
/*@zep Widgets\QStatusBar isSizeGripEnabled(int handle) -> bool */
zend_long phpqt_qstatusbar_is_size_grip_enabled(zval *p_handle);

/*@ast QString currentMessage() const */
/*@zep Widgets\QStatusBar currentMessage(int handle) -> string */
void phpqt_qstatusbar_current_message(zval *return_value, zval *p_handle);

/*@ast void showMessage(const QString & text, int timeout) */
/*@zep Widgets\QStatusBar showMessage(int handle, string text, int timeout = 0) -> void */
void phpqt_qstatusbar_show_message(zval *p_handle, zval *p_text, zval *p_timeout);

/*@ast void clearMessage() */
/*@zep Widgets\QStatusBar clearMessage(int handle) -> void */
void phpqt_qstatusbar_clear_message(zval *p_handle);

/*@ast void messageChanged(const QString & text) */
/*@zep Widgets\QStatusBar messageChanged(int handle, string text) -> void */
void phpqt_qstatusbar_message_changed(zval *p_handle, zval *p_text);

/*@ast void showEvent(QShowEvent *) */
/*@zep Widgets\QStatusBar showEvent(int handle, int arg0) -> void */
void phpqt_qstatusbar_show_event(zval *p_handle, zval *p_arg0);

/*@ast void paintEvent(QPaintEvent *) */
/*@zep Widgets\QStatusBar paintEvent(int handle, int arg0) -> void */
void phpqt_qstatusbar_paint_event(zval *p_handle, zval *p_arg0);

/*@ast void resizeEvent(QResizeEvent *) */
/*@zep Widgets\QStatusBar resizeEvent(int handle, int arg0) -> void */
void phpqt_qstatusbar_resize_event(zval *p_handle, zval *p_arg0);

/*@ast void reformat() */
/*@zep Widgets\QStatusBar reformat(int handle) -> void */
void phpqt_qstatusbar_reformat(zval *p_handle);

/*@ast void hideOrShow() */
/*@zep Widgets\QStatusBar hideOrShow(int handle) -> void */
void phpqt_qstatusbar_hide_or_show(zval *p_handle);

/*@ast bool event(QEvent *) */
/*@zep Widgets\QStatusBar event(int handle, int arg0) -> bool */
zend_long phpqt_qstatusbar_event(zval *p_handle, zval *p_arg0);

/*@override Widgets\QStatusBar showEvent void showEvent(QShowEvent *) */
/*@override Widgets\QStatusBar paintEvent void paintEvent(QPaintEvent *) */
/*@override Widgets\QStatusBar resizeEvent void resizeEvent(QResizeEvent *) */
/*@override Widgets\QStatusBar event bool event(QEvent *) */
/*@override Widgets\QStatusBar devType int devType() const */
/*@override Widgets\QStatusBar setVisible void setVisible(bool visible) */
/*@override Widgets\QStatusBar sizeHint QSize sizeHint() const */
/*@override Widgets\QStatusBar minimumSizeHint QSize minimumSizeHint() const */
/*@override Widgets\QStatusBar heightForWidth int heightForWidth(int) const */
/*@override Widgets\QStatusBar hasHeightForWidth bool hasHeightForWidth() const */
/*@override Widgets\QStatusBar paintEngine QPaintEngine * paintEngine() const */
/*@override Widgets\QStatusBar mousePressEvent void mousePressEvent(QMouseEvent * event) */
/*@override Widgets\QStatusBar mouseReleaseEvent void mouseReleaseEvent(QMouseEvent * event) */
/*@override Widgets\QStatusBar mouseDoubleClickEvent void mouseDoubleClickEvent(QMouseEvent * event) */
/*@override Widgets\QStatusBar mouseMoveEvent void mouseMoveEvent(QMouseEvent * event) */
/*@override Widgets\QStatusBar wheelEvent void wheelEvent(QWheelEvent * event) */
/*@override Widgets\QStatusBar keyPressEvent void keyPressEvent(QKeyEvent * event) */
/*@override Widgets\QStatusBar keyReleaseEvent void keyReleaseEvent(QKeyEvent * event) */
/*@override Widgets\QStatusBar focusInEvent void focusInEvent(QFocusEvent * event) */
/*@override Widgets\QStatusBar focusOutEvent void focusOutEvent(QFocusEvent * event) */
/*@override Widgets\QStatusBar enterEvent void enterEvent(QEnterEvent * event) */
/*@override Widgets\QStatusBar leaveEvent void leaveEvent(QEvent * event) */
/*@override Widgets\QStatusBar moveEvent void moveEvent(QMoveEvent * event) */
/*@override Widgets\QStatusBar closeEvent void closeEvent(QCloseEvent * event) */
/*@override Widgets\QStatusBar contextMenuEvent void contextMenuEvent(QContextMenuEvent * event) */
/*@override Widgets\QStatusBar tabletEvent void tabletEvent(QTabletEvent * event) */
/*@override Widgets\QStatusBar actionEvent void actionEvent(QActionEvent * event) */
/*@override Widgets\QStatusBar dragEnterEvent void dragEnterEvent(QDragEnterEvent * event) */
/*@override Widgets\QStatusBar dragMoveEvent void dragMoveEvent(QDragMoveEvent * event) */
/*@override Widgets\QStatusBar dragLeaveEvent void dragLeaveEvent(QDragLeaveEvent * event) */
/*@override Widgets\QStatusBar dropEvent void dropEvent(QDropEvent * event) */
/*@override Widgets\QStatusBar hideEvent void hideEvent(QHideEvent * event) */
/*@reserved-override Widgets\QStatusBar raw-pointer bool nativeEvent(const QByteArray & eventType, void * message, qintptr * result) */
/*@override Widgets\QStatusBar changeEvent void changeEvent(QEvent *) */
/*@override Widgets\QStatusBar metric int metric(QPaintDevice::PaintDeviceMetric) const */
/*@override Widgets\QStatusBar initPainter void initPainter(QPainter * painter) const */
/*@reserved-override Widgets\QStatusBar raw-pointer QPaintDevice * redirected(QPoint * offset) const */
/*@override Widgets\QStatusBar sharedPainter QPainter * sharedPainter() const */
/*@override Widgets\QStatusBar inputMethodEvent void inputMethodEvent(QInputMethodEvent *) */
/*@override Widgets\QStatusBar inputMethodQuery QVariant inputMethodQuery(Qt::InputMethodQuery) const */
/*@override Widgets\QStatusBar focusNextPrevChild bool focusNextPrevChild(bool next) */
/*@override Widgets\QStatusBar eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Widgets\QStatusBar timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QStatusBar childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QStatusBar customEvent void customEvent(QEvent * event) */
/*@override Widgets\QStatusBar connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QStatusBar disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
