/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QGRAPHICSLAYOUTFUNCTIONS_H
#define PHPQT_WIDGETS_QGRAPHICSLAYOUTFUNCTIONS_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@reserved Widgets\QGraphicslayoutFunctions template QGraphicsLayout * qobject_cast(QObject * object) */
/*@reserved Widgets\QGraphicslayoutFunctions template const QGraphicsLayout * qobject_cast(const QObject * object) */
/*@reserved Widgets\QGraphicslayoutFunctions template const char * qobject_interface_iid() */

#ifdef __cplusplus
}
#endif
#endif
