/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtWidgets/qslider.h>
#include <QtWidgets/qstyleoption.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "widgets-qsliderfunctions.h"

extern "C" zend_long phpqt_qsliderfunctions_qt_qslider_style_option(zval *p_slider)
{
    QSlider *a0 = phpqt::as<QSlider>(p_slider, PHPQT_TAG_QSlider);
    return phpqt::reg(new QStyleOptionSlider(qt_qsliderStyleOption(a0)), PHPQT_TAG_QStyleOptionSlider, true); /* native */
}

