/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_XML_QDOMNODELIST_H
#define PHPQT_XML_QDOMNODELIST_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast QDomNodeList() */
/*@zep Xml\QDomNodeList new() -> int */
zend_long phpqt_qdomnodelist_new(void);

/*@ast QDomNodeList(const QDomNodeList & nodeList) */
/*@zep Xml\QDomNodeList newQDomNodeList(int nodeList) -> int */
zend_long phpqt_qdomnodelist_new_q_dom_node_list(zval *p_nodeList);

/*@ast QDomNode item(int index) const */
/*@zep Xml\QDomNodeList item(int handle, int index) -> int */
zend_long phpqt_qdomnodelist_item(zval *p_handle, zval *p_index);

/*@ast QDomNode at(int index) const */
/*@zep Xml\QDomNodeList at(int handle, int index) -> int */
zend_long phpqt_qdomnodelist_at(zval *p_handle, zval *p_index);

/*@ast int length() const */
/*@zep Xml\QDomNodeList length(int handle) -> int */
zend_long phpqt_qdomnodelist_length(zval *p_handle);

/*@ast int count() const */
/*@zep Xml\QDomNodeList count(int handle) -> int */
zend_long phpqt_qdomnodelist_count(zval *p_handle);

/*@ast int size() const */
/*@zep Xml\QDomNodeList size(int handle) -> int */
zend_long phpqt_qdomnodelist_size(zval *p_handle);

/*@ast bool isEmpty() const */
/*@zep Xml\QDomNodeList isEmpty(int handle) -> bool */
zend_long phpqt_qdomnodelist_is_empty(zval *p_handle);

/*@reserved Xml\QDomNodeList operator QDomNodeList & operator=(const QDomNodeList & other) */
/*@reserved Xml\QDomNodeList operator bool operator==(const QDomNodeList & other) const */
/*@reserved Xml\QDomNodeList operator bool operator!=(const QDomNodeList & other) const */

#ifdef __cplusplus
}
#endif
#endif
