
extern zend_class_entry *qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord);

PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, staticMetaObject);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, qt_check_for_QGADGET_macro);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, new_);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, newQDnsTlsAssociationRecord);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, swap);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, name);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, timeToLive);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, usage);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, selector);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, matchType);
PHP_METHOD(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, value);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_qt_check_for_qgadget_macro, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_newqdnstlsassociationrecord, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_name, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_timetolive, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_usage, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_selector, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_matchtype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_value, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_method_entry) {
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, staticMetaObject, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, qt_check_for_QGADGET_macro, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_qt_check_for_qgadget_macro, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, new_, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, newQDnsTlsAssociationRecord, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_newqdnstlsassociationrecord, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, swap, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, name, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_name, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, timeToLive, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_timetolive, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, usage, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_usage, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, selector, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_selector, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, matchType, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_matchtype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsTlsAssociationRecord_QDnsTlsAssociationRecord, value, arginfo_qt_network_qdnstlsassociationrecord_qdnstlsassociationrecord_value, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
