
extern zend_class_entry *qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord);

PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, new_);
PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, newQDnsMailExchangeRecord);
PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, swap);
PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, exchange);
PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, name);
PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, preference);
PHP_METHOD(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, timeToLive);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_newqdnsmailexchangerecord, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_exchange, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_name, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_preference, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_timetolive, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_method_entry) {
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, new_, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, newQDnsMailExchangeRecord, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_newqdnsmailexchangerecord, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, swap, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, exchange, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_exchange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, name, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_name, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, preference, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_preference, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsMailExchangeRecord_QDnsMailExchangeRecord, timeToLive, arginfo_qt_network_qdnsmailexchangerecord_qdnsmailexchangerecord_timetolive, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
