
extern zend_class_entry *qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat);

PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, new_);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, newQOpenGLFramebufferObjectFormat);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setSamples);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, samples);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setMipmap);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, mipmap);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setAttachment);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, attachment);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setTextureTarget);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, textureTarget);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setInternalTextureFormat);
PHP_METHOD(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, internalTextureFormat);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_newqopenglframebufferobjectformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setsamples, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, samples, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_samples, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setmipmap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, enabled, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_mipmap, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setattachment, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, attachment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_attachment, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_settexturetarget, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, target, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_texturetarget, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setinternaltextureformat, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, internalTextureFormat, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_internaltextureformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, new_, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, newQOpenGLFramebufferObjectFormat, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_newqopenglframebufferobjectformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setSamples, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setsamples, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, samples, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_samples, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setMipmap, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setmipmap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, mipmap, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_mipmap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setAttachment, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setattachment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, attachment, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_attachment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setTextureTarget, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_settexturetarget, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, textureTarget, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_texturetarget, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, setInternalTextureFormat, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_setinternaltextureformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLFramebufferObjectFormat_QOpenGLFramebufferObjectFormat, internalTextureFormat, arginfo_qt_opengl_qopenglframebufferobjectformat_qopenglframebufferobjectformat_internaltextureformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
