
extern zend_class_entry *qt_core_qtversionfunctions_qtversionfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QTversionFunctions_QTversionFunctions);

PHP_METHOD(Qt_Core_QTversionFunctions_QTversionFunctions, qVersion);

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_core_qtversionfunctions_qtversionfunctions_qversion, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qtversionfunctions_qtversionfunctions_method_entry) {
PHP_ME(Qt_Core_QTversionFunctions_QTversionFunctions, qVersion, arginfo_qt_core_qtversionfunctions_qtversionfunctions_qversion, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
