
extern zend_class_entry *qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator);

PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, staticMetaObject);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, qt_check_for_QGADGET_macro);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, new_);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, newQSslPreSharedKeyAuthenticator);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, swap);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, identityHint);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, setIdentity);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, identity);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, maximumIdentityLength);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, setPreSharedKey);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, preSharedKey);
PHP_METHOD(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, maximumPreSharedKeyLength);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_qt_check_for_qgadget_macro, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_newqsslpresharedkeyauthenticator, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, authenticator, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_identityhint, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_setidentity, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, identity, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_identity, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_maximumidentitylength, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_setpresharedkey, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, preSharedKey, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_presharedkey, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_maximumpresharedkeylength, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_method_entry) {
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, staticMetaObject, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, qt_check_for_QGADGET_macro, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_qt_check_for_qgadget_macro, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, new_, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, newQSslPreSharedKeyAuthenticator, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_newqsslpresharedkeyauthenticator, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, swap, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, identityHint, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_identityhint, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, setIdentity, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_setidentity, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, identity, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_identity, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, maximumIdentityLength, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_maximumidentitylength, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, setPreSharedKey, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_setpresharedkey, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, preSharedKey, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_presharedkey, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslPreSharedKeyAuthenticator_QSslPreSharedKeyAuthenticator, maximumPreSharedKeyLength, arginfo_qt_network_qsslpresharedkeyauthenticator_qsslpresharedkeyauthenticator_maximumpresharedkeylength, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
