
extern zend_class_entry *qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface);

PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, tr);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, actionNames);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, localizedActionName);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, localizedActionDescription);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, doAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, keyBindingsForAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, pressAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, increaseAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, decreaseAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, showMenuAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, setFocusAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, toggleAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollLeftAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollRightAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollUpAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollDownAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, nextPageAction);
PHP_METHOD(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, previousPageAction);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_tr, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, sourceText)
	ZEND_ARG_INFO(0, disambiguation)
	ZEND_ARG_TYPE_INFO(0, n, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_actionnames, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_localizedactionname, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_localizedactiondescription, 0, 2, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_doaction, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, actionName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_keybindingsforaction, 0, 2, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, actionName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_pressaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_increaseaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_decreaseaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_showmenuaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_setfocusaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_toggleaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrollleftaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrollrightaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrollupaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrolldownaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_nextpageaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_previouspageaction, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, tr, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_tr, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, actionNames, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_actionnames, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, localizedActionName, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_localizedactionname, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, localizedActionDescription, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_localizedactiondescription, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, doAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_doaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, keyBindingsForAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_keybindingsforaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, pressAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_pressaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, increaseAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_increaseaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, decreaseAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_decreaseaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, showMenuAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_showmenuaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, setFocusAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_setfocusaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, toggleAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_toggleaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollLeftAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrollleftaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollRightAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrollrightaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollUpAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrollupaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, scrollDownAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_scrolldownaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, nextPageAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_nextpageaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleActionInterface_QAccessibleActionInterface, previousPageAction, arginfo_qt_gui_qaccessibleactioninterface_qaccessibleactioninterface_previouspageaction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
