
extern zend_class_entry *qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions);

PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, new_);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, newQOpenGLPixelTransferOptions);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, swap);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setAlignment);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, alignment);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSkipImages);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, skipImages);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSkipRows);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, skipRows);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSkipPixels);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, skipPixels);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setImageHeight);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, imageHeight);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setRowLength);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, rowLength);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setLeastSignificantByteFirst);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, isLeastSignificantBitFirst);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSwapBytesEnabled);
PHP_METHOD(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, isSwapBytesEnabled);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_newqopenglpixeltransferoptions, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setalignment, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, alignment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_alignment, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setskipimages, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, skipImages, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_skipimages, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setskiprows, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, skipRows, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_skiprows, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setskippixels, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, skipPixels, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_skippixels, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setimageheight, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, imageHeight, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_imageheight, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setrowlength, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rowLength, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_rowlength, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setleastsignificantbytefirst, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lsbFirst, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_isleastsignificantbitfirst, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setswapbytesenabled, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, swapBytes, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_isswapbytesenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, new_, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, newQOpenGLPixelTransferOptions, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_newqopenglpixeltransferoptions, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, swap, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setAlignment, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setalignment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, alignment, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_alignment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSkipImages, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setskipimages, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, skipImages, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_skipimages, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSkipRows, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setskiprows, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, skipRows, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_skiprows, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSkipPixels, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setskippixels, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, skipPixels, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_skippixels, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setImageHeight, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setimageheight, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, imageHeight, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_imageheight, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setRowLength, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setrowlength, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, rowLength, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_rowlength, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setLeastSignificantByteFirst, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setleastsignificantbytefirst, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, isLeastSignificantBitFirst, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_isleastsignificantbitfirst, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, setSwapBytesEnabled, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_setswapbytesenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLPixelTransferOptions_QOpenGLPixelTransferOptions, isSwapBytesEnabled, arginfo_qt_opengl_qopenglpixeltransferoptions_qopenglpixeltransferoptions_isswapbytesenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
