// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Gui\QFontTag;

class QFontTag
{
    public static function new_() -> int
    {
        return qfonttag_new();
    }

    public static function isValid(int handle) -> bool
    {
        int r;

        let r = qfonttag_is_valid(handle);

        return r == 1;
    }

    public static function value(int handle) -> int
    {
        return qfonttag_value(handle);
    }

    public static function toString(int handle) -> string
    {
        var result;

        let result = qfonttag_to_string(handle);

        return result;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template std::optional<QFont::Tag> fromValue(quint32 value)
    // @reserved template std::optional<QFont::Tag> fromString(QAnyStringView view)

}
