// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QMessageLogContext;

class QMessageLogContext
{
    public static function CurrentVersion() -> int
    {
        return qmessagelogcontext_current_version();
    }

    public static function new_() -> int
    {
        return qmessagelogcontext_new();
    }

    public static function newCharIntCharChar(var fileName, int lineNumber, var functionName, var categoryName) -> int
    {
        return qmessagelogcontext_new_char_int_char_char(fileName, lineNumber, functionName, categoryName);
    }

    public static function version(int handle) -> int
    {
        return qmessagelogcontext_version(handle);
    }

    public static function setVersion(int handle, int value) -> void
    {
        qmessagelogcontext_set_version(handle, value);
    }

    public static function line(int handle) -> int
    {
        return qmessagelogcontext_line(handle);
    }

    public static function setLine(int handle, int value) -> void
    {
        qmessagelogcontext_set_line(handle, value);
    }

    public static function file(int handle) -> var
    {
        var result;

        let result = qmessagelogcontext_file(handle);

        return result;
    }

    public static function function_(int handle) -> var
    {
        var result;

        let result = qmessagelogcontext_function(handle);

        return result;
    }

    public static function category(int handle) -> var
    {
        var result;

        let result = qmessagelogcontext_category(handle);

        return result;
    }
}
