
extern zend_class_entry *qt_core_qvariantconstpointer_qvariantconstpointer_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QVariantConstPointer_QVariantConstPointer);

PHP_METHOD(Qt_Core_QVariantConstPointer_QVariantConstPointer, new_);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qvariantconstpointer_qvariantconstpointer_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_INFO(0, variant)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qvariantconstpointer_qvariantconstpointer_method_entry) {
	PHP_ME(Qt_Core_QVariantConstPointer_QVariantConstPointer, new_, arginfo_qt_core_qvariantconstpointer_qvariantconstpointer_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
