
extern zend_class_entry *qt_gui_qopenglcontextgroup_qopenglcontextgroup_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup);

PHP_METHOD(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, staticMetaObject);
PHP_METHOD(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, tr);
PHP_METHOD(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, shares);
PHP_METHOD(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, currentContextGroup);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_tr, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, s)
	ZEND_ARG_INFO(0, c)
	ZEND_ARG_TYPE_INFO(0, n, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_shares, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_currentcontextgroup, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qopenglcontextgroup_qopenglcontextgroup_method_entry) {
	PHP_ME(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, staticMetaObject, arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, tr, arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_tr, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, shares, arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_shares, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QOpenGLContextGroup_QOpenGLContextGroup, currentContextGroup, arginfo_qt_gui_qopenglcontextgroup_qopenglcontextgroup_currentcontextgroup, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
