// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QAbstractListModel;

class QAbstractListModel
{
    public static function parent_(int handle) -> int
    {
        return qabstractlistmodel_parent(handle);
    }

    public static function staticMetaObject() -> int
    {
        return qabstractlistmodel_static_meta_object();
    }

    public static function tr(var s, var c = null, int n = -1) -> string
    {
        var result;

        let result = qabstractlistmodel_tr(s, c, n);

        return result;
    }

    public static function new_(int parent_ = 0) -> int
    {
        return qabstractlistmodel_new(parent_);
    }

    public static function index(int handle, int row, int column = 0, var parent_ = null) -> int
    {
        return qabstractlistmodel_index(handle, row, column, parent_);
    }

    public static function sibling(int handle, int row, int column, int idx) -> int
    {
        return qabstractlistmodel_sibling(handle, row, column, idx);
    }

    public static function dropMimeData(int handle, int data, int action, int row, int column, int parent_) -> bool
    {
        int r;

        let r = qabstractlistmodel_drop_mime_data(handle, data, action, row, column, parent_);

        return r == 1;
    }

    public static function flags(int handle, int index) -> int
    {
        return qabstractlistmodel_flags(handle, index);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template QAbstractListModel(QAbstractItemModelPrivate & dd, QObject * parent)

}
