// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Gui\QRasterWindow;

class QRasterWindow
{
    public static function staticMetaObject() -> int
    {
        return qrasterwindow_static_meta_object();
    }

    public static function tr(var s, var c = null, int n = -1) -> string
    {
        var result;

        let result = qrasterwindow_tr(s, c, n);

        return result;
    }

    public static function new_(int parent_ = 0) -> int
    {
        return qrasterwindow_new(parent_);
    }

    public static function metric(int handle, int metric) -> int
    {
        return qrasterwindow_metric(handle, metric);
    }

    public static function redirected(int handle, var arg0) -> array
    {
        var result;

        let result = qrasterwindow_redirected(handle, arg0);

        return result;
    }

    public static function resizeEvent(int handle, int event) -> void
    {
        qrasterwindow_resize_event(handle, event);
    }
}
