
extern zend_class_entry *qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject);

PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, staticMetaObject);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, tr);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, new_);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, create);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, destroy);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, isCreated);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, objectId);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, bind);
PHP_METHOD(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, release);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_tr, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, s)
	ZEND_ARG_INFO(0, c)
	ZEND_ARG_TYPE_INFO(0, n, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_new_, 0, 0, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, parent_, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_create, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_destroy, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_iscreated, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_objectid, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_bind, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_release, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, staticMetaObject, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, tr, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_tr, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, new_, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, create, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_create, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, destroy, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_destroy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, isCreated, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_iscreated, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, objectId, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_objectid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, bind, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_bind, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVertexArrayObject_QOpenGLVertexArrayObject, release, arginfo_qt_opengl_qopenglvertexarrayobject_qopenglvertexarrayobject_release, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
