
extern zend_class_entry *qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions);

PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qHash);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, swap);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qHashQModelIndexSizeT);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qRegisterNormalizedMetaType_QModelIndexList);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, compareThreeWay);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, comparesEqual);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, compareThreeWayQPersistentModelIndexQModelIndex);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, compareThreeWayQPersistentModelIndexQPersistentModelIndex);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, comparesEqualQPersistentModelIndexQModelIndex);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, comparesEqualQPersistentModelIndexQPersistentModelIndex);
PHP_METHOD(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qHashEquals);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qhashqmodelindexsizet, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, index, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qregisternormalizedmetatype_qmodelindexlist, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparethreeway, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparethreewayqpersistentmodelindexqmodelindex, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparethreewayqpersistentmodelindexqpersistentmodelindex, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparesequalqpersistentmodelindexqmodelindex, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparesequalqpersistentmodelindexqpersistentmodelindex, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qhashequals, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, a, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, b, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_method_entry) {
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qHash, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, swap, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qHashQModelIndexSizeT, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qhashqmodelindexsizet, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qRegisterNormalizedMetaType_QModelIndexList, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qregisternormalizedmetatype_qmodelindexlist, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, compareThreeWay, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparethreeway, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, comparesEqual, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, compareThreeWayQPersistentModelIndexQModelIndex, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparethreewayqpersistentmodelindexqmodelindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, compareThreeWayQPersistentModelIndexQPersistentModelIndex, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparethreewayqpersistentmodelindexqpersistentmodelindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, comparesEqualQPersistentModelIndexQModelIndex, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparesequalqpersistentmodelindexqmodelindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, comparesEqualQPersistentModelIndexQPersistentModelIndex, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_comparesequalqpersistentmodelindexqpersistentmodelindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractitemmodelFunctions_QAbstractitemmodelFunctions, qHashEquals, arginfo_qt_core_qabstractitemmodelfunctions_qabstractitemmodelfunctions_qhashequals, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
