
extern zend_class_entry *qt_network_qabstractsocketfunctions_qabstractsocketfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QAbstractsocketFunctions_QAbstractsocketFunctions);

PHP_METHOD(Qt_Network_QAbstractsocketFunctions_QAbstractsocketFunctions, qRegisterNormalizedMetaType_QAbstractSocket__SocketState);
PHP_METHOD(Qt_Network_QAbstractsocketFunctions_QAbstractsocketFunctions, qRegisterNormalizedMetaType_QAbstractSocket__SocketError);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qabstractsocketfunctions_qabstractsocketfunctions_qregisternormalizedmetatype_qabstractsocket__socketstate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qabstractsocketfunctions_qabstractsocketfunctions_qregisternormalizedmetatype_qabstractsocket__socketerror, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qabstractsocketfunctions_qabstractsocketfunctions_method_entry) {
	PHP_ME(Qt_Network_QAbstractsocketFunctions_QAbstractsocketFunctions, qRegisterNormalizedMetaType_QAbstractSocket__SocketState, arginfo_qt_network_qabstractsocketfunctions_qabstractsocketfunctions_qregisternormalizedmetatype_qabstractsocket__socketstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QAbstractsocketFunctions_QAbstractsocketFunctions, qRegisterNormalizedMetaType_QAbstractSocket__SocketError, arginfo_qt_network_qabstractsocketfunctions_qabstractsocketfunctions_qregisternormalizedmetatype_qabstractsocket__socketerror, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
