
extern zend_class_entry *qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2);

PHP_METHOD(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, timerId);
PHP_METHOD(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, setTimerId);
PHP_METHOD(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, timerType);
PHP_METHOD(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, setTimerType);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_timerid, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_settimerid, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_timertype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_settimertype, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_method_entry) {
	PHP_ME(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, timerId, arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_timerid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, setTimerId, arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_settimerid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, timerType, arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_timertype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAbstractEventDispatcherTimerInfoV2_QAbstractEventDispatcherTimerInfoV2, setTimerType, arginfo_qt_core_qabstracteventdispatchertimerinfov2_qabstracteventdispatchertimerinfov2_settimertype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
