
extern zend_class_entry *qt_network_qdnshostaddressrecord_qdnshostaddressrecord_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord);

PHP_METHOD(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, new_);
PHP_METHOD(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, newQDnsHostAddressRecord);
PHP_METHOD(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, swap);
PHP_METHOD(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, name);
PHP_METHOD(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, timeToLive);
PHP_METHOD(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, value);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_newqdnshostaddressrecord, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_name, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_timetolive, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_value, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qdnshostaddressrecord_qdnshostaddressrecord_method_entry) {
	PHP_ME(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, new_, arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, newQDnsHostAddressRecord, arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_newqdnshostaddressrecord, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, swap, arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, name, arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_name, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, timeToLive, arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_timetolive, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDnsHostAddressRecord_QDnsHostAddressRecord, value, arginfo_qt_network_qdnshostaddressrecord_qdnshostaddressrecord_value, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
