
extern zend_class_entry *qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters);

PHP_METHOD(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, new_);
PHP_METHOD(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, newQCryptographicHashAlgorithmQByteArray);
PHP_METHOD(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, hash);
PHP_METHOD(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, setHash);
PHP_METHOD(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, secret);
PHP_METHOD(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, setSecret);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_newqcryptographichashalgorithmqbytearray, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, a, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, s, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_hash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_sethash, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_secret, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_setsecret, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_method_entry) {
	PHP_ME(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, new_, arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, newQCryptographicHashAlgorithmQByteArray, arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_newqcryptographichashalgorithmqbytearray, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, hash, arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_hash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, setHash, arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_sethash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, secret, arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_secret, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QDtlsClientVerifierGeneratorParameters_QDtlsClientVerifierGeneratorParameters, setSecret, arginfo_qt_network_qdtlsclientverifiergeneratorparameters_qdtlsclientverifiergeneratorparameters_setsecret, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
