<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class QfiledeviceUnmapOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 2) {
            throw new CompilerException("'qfiledevice_unmap' requires exactly 2 parameters", $expression);
        }

        $context->headersManager->add('src/core-qfiledevice');

        $call->processExpectedReturn($context);

        $symbolVariable = $call->getSymbolVariable(true, $context);
        $this->checkNotVariableString($symbolVariable, $expression);

        $symbolVariable->setDynamicTypes('array');

        $this->checkInitSymbolVariable($call, $symbolVariable, $context);

        $symbol = $context->backend->getVariableCode($symbolVariable);

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('phpqt_qfiledevice_unmap(' . $symbol . ', ' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ');');

        return new CompiledExpression('variable', $symbolVariable->getRealName(), $expression);
    }
}
