<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class QlineeditAddActionQIconQStringQKeySequenceOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 4) {
            throw new CompilerException("'qlineedit_add_action_q_icon_q_string_q_key_sequence' requires exactly 4 parameters", $expression);
        }

        $context->headersManager->add('src/widgets-qlineedit');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        return new CompiledExpression(
            'int',
            'phpqt_qlineedit_add_action_q_icon_q_string_q_key_sequence(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ', ' . $resolvedParams[2] . ', ' . $resolvedParams[3] . ')',
            $expression
        );
    }
}
