<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class QnetworkproxyfunctionsSwapQNetworkProxyQNetworkProxyOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (!isset($expression['parameters']) || count($expression['parameters']) !== 2) {
            throw new CompilerException("'qnetworkproxyfunctions_swap_q_network_proxy_q_network_proxy' requires exactly 2 parameters", $expression);
        }

        $context->headersManager->add('src/network-qnetworkproxyfunctions');

        $resolvedParams = $call->getReadOnlyResolvedParams($expression['parameters'], $context, $expression);

        $context->codePrinter->output('phpqt_qnetworkproxyfunctions_swap_q_network_proxy_q_network_proxy(' . $resolvedParams[0] . ', ' . $resolvedParams[1] . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
