<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class QtesteventloopStaticMetaObjectOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'qtesteventloop_static_meta_object' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/test-qtesteventloop');


        return new CompiledExpression(
            'int',
            'phpqt_qtesteventloop_static_meta_object(' . ')',
            $expression
        );
    }
}
