<?php

/* GENERATED by scripts/gen-zep.php — DO NOT EDIT. */

namespace Zephir\Optimizers\FunctionCall;

use Zephir\Call;
use Zephir\CompilationContext;
use Zephir\CompiledExpression;
use Zephir\Exception\CompilerException;
use Zephir\Optimizers\OptimizerAbstract;

class QyieldcpufunctionsQYieldCpuOptimizer extends OptimizerAbstract
{
    public function optimize(array $expression, Call $call, CompilationContext $context)
    {
        if (isset($expression['parameters']) && count($expression['parameters']) !== 0) {
            throw new CompilerException("'qyieldcpufunctions_q_yield_cpu' requires zero parameters", $expression);
        }

        $context->headersManager->add('src/core-qyieldcpufunctions');


        $context->codePrinter->output('phpqt_qyieldcpufunctions_q_yield_cpu(' . ');');

        return new CompiledExpression('null', 'null', $expression);
    }
}
