
extern zend_class_entry *qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip);

PHP_METHOD(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, corner);
PHP_METHOD(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, setCorner);
PHP_METHOD(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, new_);
PHP_METHOD(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, newQStyleOptionSizeGrip);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_corner, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_setcorner, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_newqstyleoptionsizegrip, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_method_entry) {
	PHP_ME(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, corner, arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_corner, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, setCorner, arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_setcorner, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, new_, arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionSizeGrip_QStyleOptionSizeGrip, newQStyleOptionSizeGrip, arginfo_qt_widgets_qstyleoptionsizegrip_qstyleoptionsizegrip_newqstyleoptionsizegrip, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
