
extern zend_class_entry *qt_gui_qpagesizefunctions_qpagesizefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions);

PHP_METHOD(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, swap);
PHP_METHOD(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, qRegisterNormalizedMetaType_QPageSize);
PHP_METHOD(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, qRegisterNormalizedMetaType_QPageSize__PageSizeId);
PHP_METHOD(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, qRegisterNormalizedMetaType_QPageSize__Unit);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_qregisternormalizedmetatype_qpagesize, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_qregisternormalizedmetatype_qpagesize__pagesizeid, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_qregisternormalizedmetatype_qpagesize__unit, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qpagesizefunctions_qpagesizefunctions_method_entry) {
	PHP_ME(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, swap, arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, qRegisterNormalizedMetaType_QPageSize, arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_qregisternormalizedmetatype_qpagesize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, qRegisterNormalizedMetaType_QPageSize__PageSizeId, arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_qregisternormalizedmetatype_qpagesize__pagesizeid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPagesizeFunctions_QPagesizeFunctions, qRegisterNormalizedMetaType_QPageSize__Unit, arginfo_qt_gui_qpagesizefunctions_qpagesizefunctions_qregisternormalizedmetatype_qpagesize__unit, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
