
extern zend_class_entry *qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent);

PHP_METHOD(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, new_);
PHP_METHOD(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, clone_);
PHP_METHOD(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, newQScreenQtScreenOrientation);
PHP_METHOD(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, screen);
PHP_METHOD(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, orientation);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_clone_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_newqscreenqtscreenorientation, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, screen, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, orientation, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_screen, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_orientation, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_method_entry) {
	PHP_ME(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, new_, arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, clone_, arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_clone_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, newQScreenQtScreenOrientation, arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_newqscreenqtscreenorientation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, screen, arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_screen, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QScreenOrientationChangeEvent_QScreenOrientationChangeEvent, orientation, arginfo_qt_gui_qscreenorientationchangeevent_qscreenorientationchangeevent_orientation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
