
extern zend_class_entry *qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions);

PHP_METHOD(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, swap);
PHP_METHOD(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, qRegisterNormalizedMetaType_QItemSelectionRange);
PHP_METHOD(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, qRegisterNormalizedMetaType_QItemSelection);
PHP_METHOD(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, comparesEqual);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_qregisternormalizedmetatype_qitemselectionrange, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_qregisternormalizedmetatype_qitemselection, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_method_entry) {
	PHP_ME(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, swap, arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, qRegisterNormalizedMetaType_QItemSelectionRange, arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_qregisternormalizedmetatype_qitemselectionrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, qRegisterNormalizedMetaType_QItemSelection, arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_qregisternormalizedmetatype_qitemselection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QItemselectionmodelFunctions_QItemselectionmodelFunctions, comparesEqual, arginfo_qt_core_qitemselectionmodelfunctions_qitemselectionmodelfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
