// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QDirFunctions;

class QDirFunctions
{
    public static function swap(int value1, int value2) -> void
    {
        qdirfunctions_swap(value1, value2);
    }

    public static function comparesEqual(int lhs, int rhs) -> bool
    {
        int r;

        let r = qdirfunctions_compares_equal(lhs, rhs);

        return r == 1;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved operator QFlags<QDir::Filter> operator|(QFlags<QDir::Filter>::enum_type f1, QFlags<QDir::Filter>::enum_type f2)
    // @reserved operator QFlags<QDir::Filter> operator|(QFlags<QDir::Filter>::enum_type f1, QFlags<QDir::Filter> f2)
    // @reserved operator QFlags<QDir::Filter> operator&(QFlags<QDir::Filter>::enum_type f1, QFlags<QDir::Filter>::enum_type f2)
    // @reserved operator QFlags<QDir::Filter> operator&(QFlags<QDir::Filter>::enum_type f1, QFlags<QDir::Filter> f2)
    // @reserved operator QFlags<QDir::Filter> operator^(QFlags<QDir::Filter>::enum_type f1, QFlags<QDir::Filter>::enum_type f2)
    // @reserved operator QFlags<QDir::Filter> operator^(QFlags<QDir::Filter>::enum_type f1, QFlags<QDir::Filter> f2)
    // @reserved operator QIncompatibleFlag operator|(QFlags<QDir::Filter>::enum_type f1, int f2)
    // @reserved operator QFlags<QDir::SortFlag> operator|(QFlags<QDir::SortFlag>::enum_type f1, QFlags<QDir::SortFlag>::enum_type f2)
    // @reserved operator QFlags<QDir::SortFlag> operator|(QFlags<QDir::SortFlag>::enum_type f1, QFlags<QDir::SortFlag> f2)
    // @reserved operator QFlags<QDir::SortFlag> operator&(QFlags<QDir::SortFlag>::enum_type f1, QFlags<QDir::SortFlag>::enum_type f2)
    // @reserved operator QFlags<QDir::SortFlag> operator&(QFlags<QDir::SortFlag>::enum_type f1, QFlags<QDir::SortFlag> f2)
    // @reserved operator QFlags<QDir::SortFlag> operator^(QFlags<QDir::SortFlag>::enum_type f1, QFlags<QDir::SortFlag>::enum_type f2)
    // @reserved operator QFlags<QDir::SortFlag> operator^(QFlags<QDir::SortFlag>::enum_type f1, QFlags<QDir::SortFlag> f2)
    // @reserved operator QIncompatibleFlag operator|(QFlags<QDir::SortFlag>::enum_type f1, int f2)
    // @reserved stream QDebug operator<<(QDebug debug, QDir::Filters filters)
    // @reserved stream QDebug operator<<(QDebug debug, const QDir & dir)
    // @reserved operator bool operator!=(const QDir & lhs, const QDir & rhs)
    // @reserved operator bool operator==(const QDir & lhs, const QDir & rhs)

}
