
extern zend_class_entry *qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters);

PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, defaultParameters);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, new_);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, newQSslDiffieHellmanParameters);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, swap);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, fromEncoded);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, fromEncodedQIODeviceQSslEncodingFormat);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, isEmpty);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, isValid);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, error);
PHP_METHOD(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, errorString);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_defaultparameters, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_newqssldiffiehellmanparameters, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_fromencoded, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, encoded, IS_STRING, 0)
	ZEND_ARG_INFO(0, format)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_fromencodedqiodeviceqsslencodingformat, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, device, IS_LONG, 0)
	ZEND_ARG_INFO(0, format)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_isempty, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_isvalid, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_error, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_errorstring, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_method_entry) {
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, defaultParameters, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_defaultparameters, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, new_, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, newQSslDiffieHellmanParameters, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_newqssldiffiehellmanparameters, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, swap, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, fromEncoded, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_fromencoded, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, fromEncodedQIODeviceQSslEncodingFormat, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_fromencodedqiodeviceqsslencodingformat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, isEmpty, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_isempty, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, isValid, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_isvalid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, error, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_error, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QSslDiffieHellmanParameters_QSslDiffieHellmanParameters, errorString, arginfo_qt_network_qssldiffiehellmanparameters_qssldiffiehellmanparameters_errorstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
