
extern zend_class_entry *qt_network_qnetworkcookiefunctions_qnetworkcookiefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Network_QNetworkcookieFunctions_QNetworkcookieFunctions);

PHP_METHOD(Qt_Network_QNetworkcookieFunctions_QNetworkcookieFunctions, swap);
PHP_METHOD(Qt_Network_QNetworkcookieFunctions_QNetworkcookieFunctions, qRegisterNormalizedMetaType_QNetworkCookie);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkcookiefunctions_qnetworkcookiefunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_network_qnetworkcookiefunctions_qnetworkcookiefunctions_qregisternormalizedmetatype_qnetworkcookie, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_network_qnetworkcookiefunctions_qnetworkcookiefunctions_method_entry) {
	PHP_ME(Qt_Network_QNetworkcookieFunctions_QNetworkcookieFunctions, swap, arginfo_qt_network_qnetworkcookiefunctions_qnetworkcookiefunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Network_QNetworkcookieFunctions_QNetworkcookieFunctions, qRegisterNormalizedMetaType_QNetworkCookie, arginfo_qt_network_qnetworkcookiefunctions_qnetworkcookiefunctions_qregisternormalizedmetatype_qnetworkcookie, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
