
extern zend_class_entry *qt_widgets_qstylehintreturnmask_qstylehintreturnmask_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask);

PHP_METHOD(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask, new_);
PHP_METHOD(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask, region);
PHP_METHOD(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask, setRegion);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstylehintreturnmask_qstylehintreturnmask_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstylehintreturnmask_qstylehintreturnmask_region, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstylehintreturnmask_qstylehintreturnmask_setregion, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qstylehintreturnmask_qstylehintreturnmask_method_entry) {
	PHP_ME(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask, new_, arginfo_qt_widgets_qstylehintreturnmask_qstylehintreturnmask_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask, region, arginfo_qt_widgets_qstylehintreturnmask_qstylehintreturnmask_region, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleHintReturnMask_QStyleHintReturnMask, setRegion, arginfo_qt_widgets_qstylehintreturnmask_qstylehintreturnmask_setregion, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
