
extern zend_class_entry *qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent);

PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, new_);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, newQAccessibleInterfaceIntQStringQString);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, textRemoved);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, textInserted);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, changePosition);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, m_position);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, setM_position);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, m_oldText);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, setM_oldText);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, m_text);
PHP_METHOD(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, setM_text);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_new_, 0, 4, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, obj, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, position, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, oldText, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_newqaccessibleinterfaceintqstringqstring, 0, 4, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, iface, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, position, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, oldText, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_textremoved, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_textinserted, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_changeposition, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_m_position, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_setm_position, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_m_oldtext, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_setm_oldtext, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_m_text, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_setm_text, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, new_, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, newQAccessibleInterfaceIntQStringQString, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_newqaccessibleinterfaceintqstringqstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, textRemoved, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_textremoved, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, textInserted, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_textinserted, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, changePosition, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_changeposition, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, m_position, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_m_position, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, setM_position, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_setm_position, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, m_oldText, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_m_oldtext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, setM_oldText, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_setm_oldtext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, m_text, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_m_text, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextUpdateEvent_QAccessibleTextUpdateEvent, setM_text, arginfo_qt_gui_qaccessibletextupdateevent_qaccessibletextupdateevent_setm_text, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
