
extern zend_class_entry *qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration);

PHP_METHOD(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, new_);
PHP_METHOD(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, name);
PHP_METHOD(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, notationName);
PHP_METHOD(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, systemId);
PHP_METHOD(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, publicId);
PHP_METHOD(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, value);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_name, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_notationname, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_systemid, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_publicid, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_value, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_method_entry) {
	PHP_ME(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, new_, arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, name, arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_name, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, notationName, arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_notationname, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, systemId, arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_systemid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, publicId, arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_publicid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamEntityDeclaration_QXmlStreamEntityDeclaration, value, arginfo_qt_core_qxmlstreamentitydeclaration_qxmlstreamentitydeclaration_value, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
