
extern zend_class_entry *qt_xml_qdomdocumentfragment_qdomdocumentfragment_ce;

ZEPHIR_INIT_CLASS(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment);

PHP_METHOD(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment, new_);
PHP_METHOD(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment, newQDomDocumentFragment);
PHP_METHOD(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment, nodeType);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentfragment_qdomdocumentfragment_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentfragment_qdomdocumentfragment_newqdomdocumentfragment, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, documentFragment, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomdocumentfragment_qdomdocumentfragment_nodetype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_xml_qdomdocumentfragment_qdomdocumentfragment_method_entry) {
	PHP_ME(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment, new_, arginfo_qt_xml_qdomdocumentfragment_qdomdocumentfragment_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment, newQDomDocumentFragment, arginfo_qt_xml_qdomdocumentfragment_qdomdocumentfragment_newqdomdocumentfragment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomDocumentFragment_QDomDocumentFragment, nodeType, arginfo_qt_xml_qdomdocumentfragment_qdomdocumentfragment_nodetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
