
extern zend_class_entry *qt_gui_qsurfacefunctions_qsurfacefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QSurfaceFunctions_QSurfaceFunctions);

PHP_METHOD(Qt_Gui_QSurfaceFunctions_QSurfaceFunctions, qRegisterNormalizedMetaType_QSurface_ptr);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qsurfacefunctions_qsurfacefunctions_qregisternormalizedmetatype_qsurface_ptr, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qsurfacefunctions_qsurfacefunctions_method_entry) {
	PHP_ME(Qt_Gui_QSurfaceFunctions_QSurfaceFunctions, qRegisterNormalizedMetaType_QSurface_ptr, arginfo_qt_gui_qsurfacefunctions_qsurfacefunctions_qregisternormalizedmetatype_qsurface_ptr, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
