// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Widgets\QLabel;

class QLabel
{
    public static function staticMetaObject() -> int
    {
        return qlabel_static_meta_object();
    }

    public static function tr(var s, var c = null, int n = -1) -> string
    {
        var result;

        let result = qlabel_tr(s, c, n);

        return result;
    }

    public static function new_(int parent_ = 0, var f = null) -> int
    {
        return qlabel_new(parent_, f);
    }

    public static function newQStringQWidgetQtWindowFlags(string text, int parent_ = 0, var f = null) -> int
    {
        return qlabel_new_q_string_q_widget_qt_window_flags(text, parent_, f);
    }

    public static function text(int handle) -> string
    {
        var result;

        let result = qlabel_text(handle);

        return result;
    }

    public static function pixmap(int handle, int arg0) -> int
    {
        return qlabel_pixmap(handle, arg0);
    }

    public static function pixmap2(int handle) -> int
    {
        return qlabel_pixmap2(handle);
    }

    public static function picture(int handle, int arg0) -> int
    {
        return qlabel_picture(handle, arg0);
    }

    public static function picture2(int handle) -> int
    {
        return qlabel_picture2(handle);
    }

    public static function movie(int handle) -> int
    {
        return qlabel_movie(handle);
    }

    public static function textFormat(int handle) -> int
    {
        return qlabel_text_format(handle);
    }

    public static function setTextFormat(int handle, int arg0) -> void
    {
        qlabel_set_text_format(handle, arg0);
    }

    public static function alignment(int handle) -> int
    {
        return qlabel_alignment(handle);
    }

    public static function setAlignment(int handle, int arg0) -> void
    {
        qlabel_set_alignment(handle, arg0);
    }

    public static function setWordWrap(int handle, bool on) -> void
    {
        qlabel_set_word_wrap(handle, on);
    }

    public static function wordWrap(int handle) -> bool
    {
        int r;

        let r = qlabel_word_wrap(handle);

        return r == 1;
    }

    public static function indent(int handle) -> int
    {
        return qlabel_indent(handle);
    }

    public static function setIndent(int handle, int arg0) -> void
    {
        qlabel_set_indent(handle, arg0);
    }

    public static function margin(int handle) -> int
    {
        return qlabel_margin(handle);
    }

    public static function setMargin(int handle, int arg0) -> void
    {
        qlabel_set_margin(handle, arg0);
    }

    public static function hasScaledContents(int handle) -> bool
    {
        int r;

        let r = qlabel_has_scaled_contents(handle);

        return r == 1;
    }

    public static function setScaledContents(int handle, bool arg0) -> void
    {
        qlabel_set_scaled_contents(handle, arg0);
    }

    public static function sizeHint(int handle) -> array
    {
        var result;

        let result = qlabel_size_hint(handle);

        return result;
    }

    public static function minimumSizeHint(int handle) -> array
    {
        var result;

        let result = qlabel_minimum_size_hint(handle);

        return result;
    }

    public static function setBuddy(int handle, int arg0) -> void
    {
        qlabel_set_buddy(handle, arg0);
    }

    public static function buddy(int handle) -> int
    {
        return qlabel_buddy(handle);
    }

    public static function heightForWidth(int handle, int arg0) -> int
    {
        return qlabel_height_for_width(handle, arg0);
    }

    public static function openExternalLinks(int handle) -> bool
    {
        int r;

        let r = qlabel_open_external_links(handle);

        return r == 1;
    }

    public static function setOpenExternalLinks(int handle, bool open) -> void
    {
        qlabel_set_open_external_links(handle, open);
    }

    public static function setTextInteractionFlags(int handle, int flags) -> void
    {
        qlabel_set_text_interaction_flags(handle, flags);
    }

    public static function textInteractionFlags(int handle) -> int
    {
        return qlabel_text_interaction_flags(handle);
    }

    public static function setSelection(int handle, int arg0, int arg1) -> void
    {
        qlabel_set_selection(handle, arg0, arg1);
    }

    public static function hasSelectedText(int handle) -> bool
    {
        int r;

        let r = qlabel_has_selected_text(handle);

        return r == 1;
    }

    public static function selectedText(int handle) -> string
    {
        var result;

        let result = qlabel_selected_text(handle);

        return result;
    }

    public static function selectionStart(int handle) -> int
    {
        return qlabel_selection_start(handle);
    }

    public static function setText(int handle, string arg0) -> void
    {
        qlabel_set_text(handle, arg0);
    }

    public static function setPixmap(int handle, int arg0) -> void
    {
        qlabel_set_pixmap(handle, arg0);
    }

    public static function setPicture(int handle, int arg0) -> void
    {
        qlabel_set_picture(handle, arg0);
    }

    public static function setMovie(int handle, int movie) -> void
    {
        qlabel_set_movie(handle, movie);
    }

    public static function setNum(int handle, int arg0) -> void
    {
        qlabel_set_num(handle, arg0);
    }

    public static function setNumDouble(int handle, double arg0) -> void
    {
        qlabel_set_num_double(handle, arg0);
    }

    public static function clear(int handle) -> void
    {
        qlabel_clear(handle);
    }

    public static function linkActivated(int handle, string link) -> void
    {
        qlabel_link_activated(handle, link);
    }

    public static function linkHovered(int handle, string link) -> void
    {
        qlabel_link_hovered(handle, link);
    }

    public static function event(int handle, int e) -> bool
    {
        int r;

        let r = qlabel_event(handle, e);

        return r == 1;
    }

    public static function keyPressEvent(int handle, int ev) -> void
    {
        qlabel_key_press_event(handle, ev);
    }

    public static function paintEvent(int handle, int arg0) -> void
    {
        qlabel_paint_event(handle, arg0);
    }

    public static function changeEvent(int handle, int arg0) -> void
    {
        qlabel_change_event(handle, arg0);
    }

    public static function mousePressEvent(int handle, int ev) -> void
    {
        qlabel_mouse_press_event(handle, ev);
    }

    public static function mouseMoveEvent(int handle, int ev) -> void
    {
        qlabel_mouse_move_event(handle, ev);
    }

    public static function mouseReleaseEvent(int handle, int ev) -> void
    {
        qlabel_mouse_release_event(handle, ev);
    }

    public static function contextMenuEvent(int handle, int ev) -> void
    {
        qlabel_context_menu_event(handle, ev);
    }

    public static function focusInEvent(int handle, int ev) -> void
    {
        qlabel_focus_in_event(handle, ev);
    }

    public static function focusOutEvent(int handle, int ev) -> void
    {
        qlabel_focus_out_event(handle, ev);
    }

    public static function focusNextPrevChild(int handle, bool next) -> bool
    {
        int r;

        let r = qlabel_focus_next_prev_child(handle, next);

        return r == 1;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved function-pointer QTextDocument::ResourceProvider resourceProvider() const
    // @reserved function-pointer void setResourceProvider(const QTextDocument::ResourceProvider & provider)

}
