// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Gui\QNativeInterfaceQGLXContext;

class QNativeInterfaceQGLXContext
{
    public static function new_() -> int
    {
        return qnativeinterfaceqglxcontext_new();
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template QOpenGLContext * fromNative(GLXContext configBasedContext, QOpenGLContext * shareContext)
    // @reserved template QOpenGLContext * fromNative(GLXContext visualBasedContext, void * visualInfo, QOpenGLContext * shareContext)
    // @reserved template GLXContext nativeContext() const

}
