
extern zend_class_entry *qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface);

PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, isSelected);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, columnHeaderCells);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, rowHeaderCells);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, columnIndex);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, rowIndex);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, columnExtent);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, rowExtent);
PHP_METHOD(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, table);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_isselected, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_columnheadercells, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_rowheadercells, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_columnindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_rowindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_columnextent, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_rowextent, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_table, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, isSelected, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_isselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, columnHeaderCells, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_columnheadercells, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, rowHeaderCells, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_rowheadercells, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, columnIndex, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_columnindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, rowIndex, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_rowindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, columnExtent, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_columnextent, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, rowExtent, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_rowextent, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableCellInterface_QAccessibleTableCellInterface, table, arginfo_qt_gui_qaccessibletablecellinterface_qaccessibletablecellinterface_table, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
