
extern zend_class_entry *qt_test_qtestthrowonfailenabler_qtestthrowonfailenabler_ce;

ZEPHIR_INIT_CLASS(Qt_Test_QTestThrowOnFailEnabler_QTestThrowOnFailEnabler);

PHP_METHOD(Qt_Test_QTestThrowOnFailEnabler_QTestThrowOnFailEnabler, new_);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestthrowonfailenabler_qtestthrowonfailenabler_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_test_qtestthrowonfailenabler_qtestthrowonfailenabler_method_entry) {
	PHP_ME(Qt_Test_QTestThrowOnFailEnabler_QTestThrowOnFailEnabler, new_, arginfo_qt_test_qtestthrowonfailenabler_qtestthrowonfailenabler_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
