
extern zend_class_entry *qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration);

PHP_METHOD(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, new_);
PHP_METHOD(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, name);
PHP_METHOD(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, systemId);
PHP_METHOD(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, publicId);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_name, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_systemid, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_publicid, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_method_entry) {
	PHP_ME(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, new_, arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, name, arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_name, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, systemId, arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_systemid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamNotationDeclaration_QXmlStreamNotationDeclaration, publicId, arginfo_qt_core_qxmlstreamnotationdeclaration_qxmlstreamnotationdeclaration_publicid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
