
extern zend_class_entry *qt_gui_qtextblockiterator_qtextblockiterator_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QTextBlockiterator_QTextBlockiterator);

PHP_METHOD(Qt_Gui_QTextBlockiterator_QTextBlockiterator, new_);
PHP_METHOD(Qt_Gui_QTextBlockiterator_QTextBlockiterator, fragment);
PHP_METHOD(Qt_Gui_QTextBlockiterator_QTextBlockiterator, atEnd);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qtextblockiterator_qtextblockiterator_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qtextblockiterator_qtextblockiterator_fragment, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qtextblockiterator_qtextblockiterator_atend, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qtextblockiterator_qtextblockiterator_method_entry) {
	PHP_ME(Qt_Gui_QTextBlockiterator_QTextBlockiterator, new_, arginfo_qt_gui_qtextblockiterator_qtextblockiterator_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QTextBlockiterator_QTextBlockiterator, fragment, arginfo_qt_gui_qtextblockiterator_qtextblockiterator_fragment, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QTextBlockiterator_QTextBlockiterator, atEnd, arginfo_qt_gui_qtextblockiterator_qtextblockiterator_atend, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
