// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\OpenGL\QOpenGLTexture;

class QOpenGLTexture
{
    public static function staticMetaObject() -> int
    {
        return qopengltexture_static_meta_object();
    }

    public static function qt_check_for_QGADGET_macro(int handle) -> void
    {
        qopengltexture_qt_check_for__q_g_a_d_g_e_t_macro(handle);
    }

    public static function new_(int target) -> int
    {
        return qopengltexture_new(target);
    }

    public static function newQImageQOpenGLTextureMipMapGeneration(int image, var genMipMaps = null) -> int
    {
        return qopengltexture_new_q_image_q_open_g_l_texture_mip_map_generation(image, genMipMaps);
    }

    public static function target(int handle) -> int
    {
        return qopengltexture_target(handle);
    }

    public static function create(int handle) -> bool
    {
        int r;

        let r = qopengltexture_create(handle);

        return r == 1;
    }

    public static function destroy(int handle) -> void
    {
        qopengltexture_destroy(handle);
    }

    public static function isCreated(int handle) -> bool
    {
        int r;

        let r = qopengltexture_is_created(handle);

        return r == 1;
    }

    public static function textureId(int handle) -> int
    {
        return qopengltexture_texture_id(handle);
    }

    public static function bind(int handle) -> void
    {
        qopengltexture_bind(handle);
    }

    public static function bindUintQOpenGLTextureTextureUnitReset(int handle, int unit, var reset = null) -> void
    {
        qopengltexture_bind_uint_q_open_g_l_texture_texture_unit_reset(handle, unit, reset);
    }

    public static function release(int handle) -> void
    {
        qopengltexture_release(handle);
    }

    public static function releaseUintQOpenGLTextureTextureUnitReset(int handle, int unit, var reset = null) -> void
    {
        qopengltexture_release_uint_q_open_g_l_texture_texture_unit_reset(handle, unit, reset);
    }

    public static function isBound(int handle) -> bool
    {
        int r;

        let r = qopengltexture_is_bound(handle);

        return r == 1;
    }

    public static function isBoundUint(int handle, int unit) -> bool
    {
        int r;

        let r = qopengltexture_is_bound_uint(handle, unit);

        return r == 1;
    }

    public static function boundTextureId(int target) -> int
    {
        return qopengltexture_bound_texture_id(target);
    }

    public static function boundTextureIdUintQOpenGLTextureBindingTarget(int unit, int target) -> int
    {
        return qopengltexture_bound_texture_id_uint_q_open_g_l_texture_binding_target(unit, target);
    }

    public static function setFormat(int handle, int format) -> void
    {
        qopengltexture_set_format(handle, format);
    }

    public static function format(int handle) -> int
    {
        return qopengltexture_format(handle);
    }

    public static function setSize(int handle, int width, int height = 1, int depth = 1) -> void
    {
        qopengltexture_set_size(handle, width, height, depth);
    }

    public static function width(int handle) -> int
    {
        return qopengltexture_width(handle);
    }

    public static function height(int handle) -> int
    {
        return qopengltexture_height(handle);
    }

    public static function depth(int handle) -> int
    {
        return qopengltexture_depth(handle);
    }

    public static function setMipLevels(int handle, int levels) -> void
    {
        qopengltexture_set_mip_levels(handle, levels);
    }

    public static function mipLevels(int handle) -> int
    {
        return qopengltexture_mip_levels(handle);
    }

    public static function maximumMipLevels(int handle) -> int
    {
        return qopengltexture_maximum_mip_levels(handle);
    }

    public static function setLayers(int handle, int layers) -> void
    {
        qopengltexture_set_layers(handle, layers);
    }

    public static function layers(int handle) -> int
    {
        return qopengltexture_layers(handle);
    }

    public static function faces(int handle) -> int
    {
        return qopengltexture_faces(handle);
    }

    public static function setSamples(int handle, int samples) -> void
    {
        qopengltexture_set_samples(handle, samples);
    }

    public static function samples(int handle) -> int
    {
        return qopengltexture_samples(handle);
    }

    public static function setFixedSamplePositions(int handle, bool fixed) -> void
    {
        qopengltexture_set_fixed_sample_positions(handle, fixed);
    }

    public static function isFixedSamplePositions(int handle) -> bool
    {
        int r;

        let r = qopengltexture_is_fixed_sample_positions(handle);

        return r == 1;
    }

    public static function allocateStorage(int handle) -> void
    {
        qopengltexture_allocate_storage(handle);
    }

    public static function allocateStorageQOpenGLTexturePixelFormatQOpenGLTexturePixelType(int handle, int pixelFormat, int pixelType) -> void
    {
        qopengltexture_allocate_storage_q_open_g_l_texture_pixel_format_q_open_g_l_texture_pixel_type(handle, pixelFormat, pixelType);
    }

    public static function isStorageAllocated(int handle) -> bool
    {
        int r;

        let r = qopengltexture_is_storage_allocated(handle);

        return r == 1;
    }

    public static function createTextureView(int handle, int target, int viewFormat, int minimumMipmapLevel, int maximumMipmapLevel, int minimumLayer, int maximumLayer) -> int
    {
        return qopengltexture_create_texture_view(handle, target, viewFormat, minimumMipmapLevel, maximumMipmapLevel, minimumLayer, maximumLayer);
    }

    public static function isTextureView(int handle) -> bool
    {
        int r;

        let r = qopengltexture_is_texture_view(handle);

        return r == 1;
    }

    public static function setData(int handle, int image, var genMipMaps = null) -> void
    {
        qopengltexture_set_data(handle, image, genMipMaps);
    }

    public static function hasFeature(int feature) -> bool
    {
        int r;

        let r = qopengltexture_has_feature(feature);

        return r == 1;
    }

    public static function setMipBaseLevel(int handle, int baseLevel) -> void
    {
        qopengltexture_set_mip_base_level(handle, baseLevel);
    }

    public static function mipBaseLevel(int handle) -> int
    {
        return qopengltexture_mip_base_level(handle);
    }

    public static function setMipMaxLevel(int handle, int maxLevel) -> void
    {
        qopengltexture_set_mip_max_level(handle, maxLevel);
    }

    public static function mipMaxLevel(int handle) -> int
    {
        return qopengltexture_mip_max_level(handle);
    }

    public static function setMipLevelRange(int handle, int baseLevel, int maxLevel) -> void
    {
        qopengltexture_set_mip_level_range(handle, baseLevel, maxLevel);
    }

    public static function mipLevelRange(int handle) -> array
    {
        var result;

        let result = qopengltexture_mip_level_range(handle);

        return result;
    }

    public static function setAutoMipMapGenerationEnabled(int handle, bool enabled) -> void
    {
        qopengltexture_set_auto_mip_map_generation_enabled(handle, enabled);
    }

    public static function isAutoMipMapGenerationEnabled(int handle) -> bool
    {
        int r;

        let r = qopengltexture_is_auto_mip_map_generation_enabled(handle);

        return r == 1;
    }

    public static function generateMipMaps(int handle) -> void
    {
        qopengltexture_generate_mip_maps(handle);
    }

    public static function generateMipMapsIntBool(int handle, int baseLevel, bool resetBaseLevel = true) -> void
    {
        qopengltexture_generate_mip_maps_int_bool(handle, baseLevel, resetBaseLevel);
    }

    public static function setSwizzleMask(int handle, int component, int value) -> void
    {
        qopengltexture_set_swizzle_mask(handle, component, value);
    }

    public static function setSwizzleMaskQOpenGLTextureSwizzleValueQOpenGLTextureSwizzleValueQOpenGLTextureSwizzleValueQOpenGLTextureSwizzleValue(int handle, int r, int g, int b, int a) -> void
    {
        qopengltexture_set_swizzle_mask_q_open_g_l_texture_swizzle_value_q_open_g_l_texture_swizzle_value_q_open_g_l_texture_swizzle_value_q_open_g_l_texture_swizzle_value(handle, r, g, b, a);
    }

    public static function swizzleMask(int handle, int component) -> int
    {
        return qopengltexture_swizzle_mask(handle, component);
    }

    public static function setDepthStencilMode(int handle, int mode) -> void
    {
        qopengltexture_set_depth_stencil_mode(handle, mode);
    }

    public static function depthStencilMode(int handle) -> int
    {
        return qopengltexture_depth_stencil_mode(handle);
    }

    public static function setComparisonFunction(int handle, int function_) -> void
    {
        qopengltexture_set_comparison_function(handle, function_);
    }

    public static function comparisonFunction(int handle) -> int
    {
        return qopengltexture_comparison_function(handle);
    }

    public static function setComparisonMode(int handle, int mode) -> void
    {
        qopengltexture_set_comparison_mode(handle, mode);
    }

    public static function comparisonMode(int handle) -> int
    {
        return qopengltexture_comparison_mode(handle);
    }

    public static function setMinificationFilter(int handle, int filter) -> void
    {
        qopengltexture_set_minification_filter(handle, filter);
    }

    public static function minificationFilter(int handle) -> int
    {
        return qopengltexture_minification_filter(handle);
    }

    public static function setMagnificationFilter(int handle, int filter) -> void
    {
        qopengltexture_set_magnification_filter(handle, filter);
    }

    public static function magnificationFilter(int handle) -> int
    {
        return qopengltexture_magnification_filter(handle);
    }

    public static function setMinMagFilters(int handle, int minificationFilter, int magnificationFilter) -> void
    {
        qopengltexture_set_min_mag_filters(handle, minificationFilter, magnificationFilter);
    }

    public static function minMagFilters(int handle) -> array
    {
        var result;

        let result = qopengltexture_min_mag_filters(handle);

        return result;
    }

    public static function setMaximumAnisotropy(int handle, double anisotropy) -> void
    {
        qopengltexture_set_maximum_anisotropy(handle, anisotropy);
    }

    public static function maximumAnisotropy(int handle) -> double
    {
        return qopengltexture_maximum_anisotropy(handle);
    }

    public static function setWrapMode(int handle, int mode) -> void
    {
        qopengltexture_set_wrap_mode(handle, mode);
    }

    public static function setWrapModeQOpenGLTextureCoordinateDirectionQOpenGLTextureWrapMode(int handle, int direction, int mode) -> void
    {
        qopengltexture_set_wrap_mode_q_open_g_l_texture_coordinate_direction_q_open_g_l_texture_wrap_mode(handle, direction, mode);
    }

    public static function wrapMode(int handle, int direction) -> int
    {
        return qopengltexture_wrap_mode(handle, direction);
    }

    public static function setBorderColor(int handle, int color) -> void
    {
        qopengltexture_set_border_color(handle, color);
    }

    public static function setBorderColorFloatFloatFloatFloat(int handle, double r, double g, double b, double a) -> void
    {
        qopengltexture_set_border_color_float_float_float_float(handle, r, g, b, a);
    }

    public static function setBorderColorIntIntIntInt(int handle, int r, int g, int b, int a) -> void
    {
        qopengltexture_set_border_color_int_int_int_int(handle, r, g, b, a);
    }

    public static function setBorderColorUintUintUintUint(int handle, int r, int g, int b, int a) -> void
    {
        qopengltexture_set_border_color_uint_uint_uint_uint(handle, r, g, b, a);
    }

    public static function borderColor(int handle) -> int
    {
        return qopengltexture_border_color(handle);
    }

    public static function borderColorFloat(int handle, var border) -> array
    {
        var result;

        let result = qopengltexture_border_color_float(handle, border);

        return result;
    }

    public static function borderColorInt(int handle, var border) -> array
    {
        var result;

        let result = qopengltexture_border_color_int(handle, border);

        return result;
    }

    public static function borderColorUnsignedInt(int handle, var border) -> array
    {
        var result;

        let result = qopengltexture_border_color_unsigned_int(handle, border);

        return result;
    }

    public static function setMinimumLevelOfDetail(int handle, double value) -> void
    {
        qopengltexture_set_minimum_level_of_detail(handle, value);
    }

    public static function minimumLevelOfDetail(int handle) -> double
    {
        return qopengltexture_minimum_level_of_detail(handle);
    }

    public static function setMaximumLevelOfDetail(int handle, double value) -> void
    {
        qopengltexture_set_maximum_level_of_detail(handle, value);
    }

    public static function maximumLevelOfDetail(int handle) -> double
    {
        return qopengltexture_maximum_level_of_detail(handle);
    }

    public static function setLevelOfDetailRange(int handle, double min, double max) -> void
    {
        qopengltexture_set_level_of_detail_range(handle, min, max);
    }

    public static function levelOfDetailRange(int handle) -> array
    {
        var result;

        let result = qopengltexture_level_of_detail_range(handle);

        return result;
    }

    public static function setLevelofDetailBias(int handle, double bias) -> void
    {
        qopengltexture_set_levelof_detail_bias(handle, bias);
    }

    public static function levelofDetailBias(int handle) -> double
    {
        return qopengltexture_levelof_detail_bias(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved raw-pointer void setData(int mipLevel, int layer, QOpenGLTexture::CubeMapFace cubeFace, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int mipLevel, int layer, int layerCount, QOpenGLTexture::CubeMapFace cubeFace, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int mipLevel, int layer, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int mipLevel, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int xOffset, int yOffset, int zOffset, int width, int height, int depth, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int xOffset, int yOffset, int zOffset, int width, int height, int depth, int mipLevel, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int xOffset, int yOffset, int zOffset, int width, int height, int depth, int mipLevel, int layer, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int xOffset, int yOffset, int zOffset, int width, int height, int depth, int mipLevel, int layer, QOpenGLTexture::CubeMapFace cubeFace, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setData(int xOffset, int yOffset, int zOffset, int width, int height, int depth, int mipLevel, int layer, QOpenGLTexture::CubeMapFace cubeFace, int layerCount, QOpenGLTexture::PixelFormat sourceFormat, QOpenGLTexture::PixelType sourceType, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setCompressedData(int mipLevel, int layer, QOpenGLTexture::CubeMapFace cubeFace, int dataSize, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setCompressedData(int mipLevel, int layer, int layerCount, QOpenGLTexture::CubeMapFace cubeFace, int dataSize, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setCompressedData(int mipLevel, int layer, int dataSize, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setCompressedData(int mipLevel, int dataSize, const void * data, const QOpenGLPixelTransferOptions * options)
    // @reserved raw-pointer void setCompressedData(int dataSize, const void * data, const QOpenGLPixelTransferOptions * options)

}
