
extern zend_class_entry *qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions);

PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, swap);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qHash);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, swapQDBusSignatureQDBusSignature);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qHashQDBusSignatureSizeT);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, swapQDBusVariantQDBusVariant);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qRegisterNormalizedMetaType_QDBusVariant);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qRegisterNormalizedMetaType_QDBusObjectPath);
PHP_METHOD(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qRegisterNormalizedMetaType_QDBusSignature);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, objectPath, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_swapqdbussignatureqdbussignature, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qhashqdbussignaturesizet, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, signature, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_swapqdbusvariantqdbusvariant, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qregisternormalizedmetatype_qdbusvariant, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qregisternormalizedmetatype_qdbusobjectpath, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qregisternormalizedmetatype_qdbussignature, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_method_entry) {
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, swap, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qHash, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, swapQDBusSignatureQDBusSignature, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_swapqdbussignatureqdbussignature, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qHashQDBusSignatureSizeT, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qhashqdbussignaturesizet, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, swapQDBusVariantQDBusVariant, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_swapqdbusvariantqdbusvariant, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qRegisterNormalizedMetaType_QDBusVariant, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qregisternormalizedmetatype_qdbusvariant, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qRegisterNormalizedMetaType_QDBusObjectPath, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qregisternormalizedmetatype_qdbusobjectpath, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_DBus_QDbusextratypesFunctions_QDbusextratypesFunctions, qRegisterNormalizedMetaType_QDBusSignature, arginfo_qt_dbus_qdbusextratypesfunctions_qdbusextratypesfunctions_qregisternormalizedmetatype_qdbussignature, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
