
extern zend_class_entry *qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent);

PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, new_);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, newQAccessibleInterfaceIntQString);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, textInserted);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, changePosition);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, m_position);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, setM_position);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, m_text);
PHP_METHOD(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, setM_text);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_new_, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, obj, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, position, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_newqaccessibleinterfaceintqstring, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, iface, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, position, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, text, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_textinserted, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_changeposition, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_m_position, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_setm_position, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_m_text, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_setm_text, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, new_, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, newQAccessibleInterfaceIntQString, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_newqaccessibleinterfaceintqstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, textInserted, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_textinserted, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, changePosition, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_changeposition, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, m_position, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_m_position, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, setM_position, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_setm_position, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, m_text, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_m_text, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTextInsertEvent_QAccessibleTextInsertEvent, setM_text, arginfo_qt_gui_qaccessibletextinsertevent_qaccessibletextinsertevent_setm_text, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
