
extern zend_class_entry *qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration);

PHP_METHOD(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, new_);
PHP_METHOD(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, newQStringQString);
PHP_METHOD(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, prefix);
PHP_METHOD(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, namespaceUri);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_newqstringqstring, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, prefix, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, namespaceUri, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_prefix, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_namespaceuri, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_method_entry) {
	PHP_ME(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, new_, arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, newQStringQString, arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_newqstringqstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, prefix, arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_prefix, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QXmlStreamNamespaceDeclaration_QXmlStreamNamespaceDeclaration, namespaceUri, arginfo_qt_core_qxmlstreamnamespacedeclaration_qxmlstreamnamespacedeclaration_namespaceuri, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
