
extern zend_class_entry *qt_core_qcborvaluefunctions_qcborvaluefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QCborvalueFunctions_QCborvalueFunctions);

PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, swap);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, qHash);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, compareThreeWay);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, comparesEqual);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, compareThreeWayQCborValueConstRefQCborValue);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, comparesEqualQCborValueConstRefQCborValue);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, compareThreeWayQCborValueConstRefQCborValueConstRef);
PHP_METHOD(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, comparesEqualQCborValueConstRefQCborValueConstRef);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparethreeway, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparethreewayqcborvalueconstrefqcborvalue, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparesequalqcborvalueconstrefqcborvalue, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparethreewayqcborvalueconstrefqcborvalueconstref, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparesequalqcborvalueconstrefqcborvalueconstref, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qcborvaluefunctions_qcborvaluefunctions_method_entry) {
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, swap, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, qHash, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, compareThreeWay, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparethreeway, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, comparesEqual, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, compareThreeWayQCborValueConstRefQCborValue, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparethreewayqcborvalueconstrefqcborvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, comparesEqualQCborValueConstRefQCborValue, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparesequalqcborvalueconstrefqcborvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, compareThreeWayQCborValueConstRefQCborValueConstRef, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparethreewayqcborvalueconstrefqcborvalueconstref, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborvalueFunctions_QCborvalueFunctions, comparesEqualQCborValueConstRefQCborValueConstRef, arginfo_qt_core_qcborvaluefunctions_qcborvaluefunctions_comparesequalqcborvalueconstrefqcborvalueconstref, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
