// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Gui\QFontFunctions;

class QFontFunctions
{
    public static function swap(int value1, int value2) -> void
    {
        qfontfunctions_swap(value1, value2);
    }

    public static function qHash(int font, int seed = 0) -> int
    {
        return qfontfunctions_q_hash(font, seed);
    }

    public static function compareThreeWay(int lhs, int rhs) -> int
    {
        return qfontfunctions_compare_three_way(lhs, rhs);
    }

    public static function comparesEqual(int lhs, int rhs) -> bool
    {
        int r;

        let r = qfontfunctions_compares_equal(lhs, rhs);

        return r == 1;
    }

    public static function qHashQFontTagSizeT(int key, int seed = 0) -> int
    {
        return qfontfunctions_q_hash_q_font_tag_size_t(key, seed);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved stream QDataStream & operator<<(QDataStream &, const QFont &)
    // @reserved stream QDataStream & operator>>(QDataStream &, QFont &)
    // @reserved stream QDebug operator<<(QDebug, const QFont &)
    // @reserved operator bool operator>=(const QFont::Tag & lhs, const QFont::Tag & rhs)
    // @reserved operator bool operator<=(const QFont::Tag & lhs, const QFont::Tag & rhs)
    // @reserved operator bool operator>(const QFont::Tag & lhs, const QFont::Tag & rhs)
    // @reserved operator bool operator<(const QFont::Tag & lhs, const QFont::Tag & rhs)
    // @reserved operator bool operator!=(const QFont::Tag & lhs, const QFont::Tag & rhs)
    // @reserved operator bool operator==(const QFont::Tag & lhs, const QFont::Tag & rhs)
    // @reserved stream QDebug operator<<(QDebug debug, QFont::Tag tag)
    // @reserved stream QDataStream & operator>>(QDataStream &, QFont::Tag &)
    // @reserved stream QDataStream & operator<<(QDataStream &, QFont::Tag)

}
