
extern zend_class_entry *qt_gui_qaccessibleactivationobserver_qaccessibleactivationobserver_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleActivationObserver_QAccessibleActivationObserver);

PHP_METHOD(Qt_Gui_QAccessibleActivationObserver_QAccessibleActivationObserver, accessibilityActiveChanged);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleactivationobserver_qaccessibleactivationobserver_accessibilityactivechanged, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, active, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibleactivationobserver_qaccessibleactivationobserver_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleActivationObserver_QAccessibleActivationObserver, accessibilityActiveChanged, arginfo_qt_gui_qaccessibleactivationobserver_qaccessibleactivationobserver_accessibilityactivechanged, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
