// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QKeyCombination;

class QKeyCombination
{
    public static function new_(var key = null) -> int
    {
        return qkeycombination_new(key);
    }

    public static function newQtModifiersQtKey(int modifiers, var key = null) -> int
    {
        return qkeycombination_new_qt_modifiers_qt_key(modifiers, key);
    }

    public static function newQtKeyboardModifiersQtKey(int modifiers, var key = null) -> int
    {
        return qkeycombination_new_qt_keyboard_modifiers_qt_key(modifiers, key);
    }

    public static function keyboardModifiers(int handle) -> int
    {
        return qkeycombination_keyboard_modifiers(handle);
    }

    public static function key(int handle) -> int
    {
        return qkeycombination_key(handle);
    }

    public static function fromCombined(int combined) -> int
    {
        return qkeycombination_from_combined(combined);
    }

    public static function toCombined(int handle) -> int
    {
        return qkeycombination_to_combined(handle);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved operator int operator int() const

}
