
extern zend_class_entry *qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface);

PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectedItemCount);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectedItems);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectedItem);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, isSelected);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, select);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, unselect);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectAll);
PHP_METHOD(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, clear);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selecteditemcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selecteditems, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selecteditem, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, selectionIndex, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_isselected, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, childItem, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_select, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, childItem, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_unselect, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, childItem, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selectall, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_clear, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectedItemCount, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selecteditemcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectedItems, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selecteditems, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectedItem, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selecteditem, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, isSelected, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_isselected, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, select, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_select, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, unselect, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_unselect, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, selectAll, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_selectall, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleSelectionInterface_QAccessibleSelectionInterface, clear, arginfo_qt_gui_qaccessibleselectioninterface_qaccessibleselectioninterface_clear, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
