
extern zend_class_entry *qt_widgets_qitemeditorcreatorbase_qitemeditorcreatorbase_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QItemEditorCreatorBase_QItemEditorCreatorBase);

PHP_METHOD(Qt_Widgets_QItemEditorCreatorBase_QItemEditorCreatorBase, createWidget);
PHP_METHOD(Qt_Widgets_QItemEditorCreatorBase_QItemEditorCreatorBase, valuePropertyName);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qitemeditorcreatorbase_qitemeditorcreatorbase_createwidget, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, parent_, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qitemeditorcreatorbase_qitemeditorcreatorbase_valuepropertyname, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qitemeditorcreatorbase_qitemeditorcreatorbase_method_entry) {
	PHP_ME(Qt_Widgets_QItemEditorCreatorBase_QItemEditorCreatorBase, createWidget, arginfo_qt_widgets_qitemeditorcreatorbase_qitemeditorcreatorbase_createwidget, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QItemEditorCreatorBase_QItemEditorCreatorBase, valuePropertyName, arginfo_qt_widgets_qitemeditorcreatorbase_qitemeditorcreatorbase_valuepropertyname, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
