
extern zend_class_entry *qt_core_qpermissionsfunctions_qpermissionsfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QPermissionsFunctions_QPermissionsFunctions);

PHP_METHOD(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swap);
PHP_METHOD(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQCalendarPermissionQCalendarPermission);
PHP_METHOD(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQContactsPermissionQContactsPermission);
PHP_METHOD(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQBluetoothPermissionQBluetoothPermission);
PHP_METHOD(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQCameraPermissionQCameraPermission);
PHP_METHOD(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQMicrophonePermissionQMicrophonePermission);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqcalendarpermissionqcalendarpermission, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqcontactspermissionqcontactspermission, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqbluetoothpermissionqbluetoothpermission, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqcamerapermissionqcamerapermission, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqmicrophonepermissionqmicrophonepermission, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qpermissionsfunctions_qpermissionsfunctions_method_entry) {
	PHP_ME(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swap, arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQCalendarPermissionQCalendarPermission, arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqcalendarpermissionqcalendarpermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQContactsPermissionQContactsPermission, arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqcontactspermissionqcontactspermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQBluetoothPermissionQBluetoothPermission, arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqbluetoothpermissionqbluetoothpermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQCameraPermissionQCameraPermission, arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqcamerapermissionqcamerapermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPermissionsFunctions_QPermissionsFunctions, swapQMicrophonePermissionQMicrophonePermission, arginfo_qt_core_qpermissionsfunctions_qpermissionsfunctions_swapqmicrophonepermissionqmicrophonepermission, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
