
extern zend_class_entry *qt_opengl_qopenglversionprofilefunctions_qopenglversionprofilefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenglversionprofileFunctions_QOpenglversionprofileFunctions);

PHP_METHOD(Qt_OpenGL_QOpenglversionprofileFunctions_QOpenglversionprofileFunctions, qHash);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionprofilefunctions_qopenglversionprofilefunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglversionprofilefunctions_qopenglversionprofilefunctions_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenglversionprofileFunctions_QOpenglversionprofileFunctions, qHash, arginfo_qt_opengl_qopenglversionprofilefunctions_qopenglversionprofilefunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
