
extern zend_class_entry *qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId);

PHP_METHOD(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, staticMetaObject);
PHP_METHOD(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, qt_check_for_QGADGET_macro);
PHP_METHOD(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, new_);
PHP_METHOD(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, fromNumericId);
PHP_METHOD(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, isValid);
PHP_METHOD(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, numericId);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_staticmetaobject, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_qt_check_for_qgadget_macro, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_fromnumericid, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, id, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_isvalid, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_numericid, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_method_entry) {
	PHP_ME(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, staticMetaObject, arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_staticmetaobject, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, qt_check_for_QGADGET_macro, arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_qt_check_for_qgadget_macro, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, new_, arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, fromNumericId, arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_fromnumericid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, isValid, arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_isvalid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPointingDeviceUniqueId_QPointingDeviceUniqueId, numericId, arginfo_qt_gui_qpointingdeviceuniqueid_qpointingdeviceuniqueid_numericid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
