
extern zend_class_entry *qt_core_qcborcommonfunctions_qcborcommonfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QCborcommonFunctions_QCborcommonFunctions);

PHP_METHOD(Qt_Core_QCborcommonFunctions_QCborcommonFunctions, qHash);
PHP_METHOD(Qt_Core_QCborcommonFunctions_QCborcommonFunctions, qHashQCborTagSizeT);
PHP_METHOD(Qt_Core_QCborcommonFunctions_QCborcommonFunctions, qRegisterNormalizedMetaType_QCborTag);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborcommonfunctions_qcborcommonfunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, tag, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborcommonfunctions_qcborcommonfunctions_qhashqcbortagsizet, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, tag, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qcborcommonfunctions_qcborcommonfunctions_qregisternormalizedmetatype_qcbortag, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qcborcommonfunctions_qcborcommonfunctions_method_entry) {
	PHP_ME(Qt_Core_QCborcommonFunctions_QCborcommonFunctions, qHash, arginfo_qt_core_qcborcommonfunctions_qcborcommonfunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborcommonFunctions_QCborcommonFunctions, qHashQCborTagSizeT, arginfo_qt_core_qcborcommonfunctions_qcborcommonfunctions_qhashqcbortagsizet, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QCborcommonFunctions_QCborcommonFunctions, qRegisterNormalizedMetaType_QCborTag, arginfo_qt_core_qcborcommonfunctions_qcborcommonfunctions_qregisternormalizedmetatype_qcbortag, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
