
extern zend_class_entry *qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions);

PHP_METHOD(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, swap);
PHP_METHOD(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, qRegisterNormalizedMetaType_QPageLayout);
PHP_METHOD(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, qRegisterNormalizedMetaType_QPageLayout__Unit);
PHP_METHOD(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, qRegisterNormalizedMetaType_QPageLayout__Orientation);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_qregisternormalizedmetatype_qpagelayout, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_qregisternormalizedmetatype_qpagelayout__unit, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_qregisternormalizedmetatype_qpagelayout__orientation, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_method_entry) {
	PHP_ME(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, swap, arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, qRegisterNormalizedMetaType_QPageLayout, arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_qregisternormalizedmetatype_qpagelayout, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, qRegisterNormalizedMetaType_QPageLayout__Unit, arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_qregisternormalizedmetatype_qpagelayout__unit, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QPagelayoutFunctions_QPagelayoutFunctions, qRegisterNormalizedMetaType_QPageLayout__Orientation, arginfo_qt_gui_qpagelayoutfunctions_qpagelayoutfunctions_qregisternormalizedmetatype_qpagelayout__orientation, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
