
extern zend_class_entry *qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent);

PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, new_);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, newQAccessibleInterfaceQAccessibleTableModelChangeEventModelChangeType);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setModelChangeType);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, modelChangeType);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setFirstRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setFirstColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setLastRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setLastColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, firstRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, firstColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, lastRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, lastColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_modelChangeType);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_modelChangeType);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_firstRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_firstRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_firstColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_firstColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_lastRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_lastRow);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_lastColumn);
PHP_METHOD(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_lastColumn);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_new_, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, obj, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, changeType, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_newqaccessibleinterfaceqaccessibletablemodelchangeeventmodelchangetype, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, iface, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, changeType, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setmodelchangetype, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, changeType, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_modelchangetype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setfirstrow, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, row, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setfirstcolumn, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, col, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setlastrow, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, row, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setlastcolumn, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, col, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_firstrow, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_firstcolumn, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_lastrow, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_lastcolumn, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_modelchangetype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_modelchangetype, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_firstrow, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_firstrow, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_firstcolumn, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_firstcolumn, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_lastrow, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_lastrow, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_lastcolumn, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_lastcolumn, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, new_, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, newQAccessibleInterfaceQAccessibleTableModelChangeEventModelChangeType, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_newqaccessibleinterfaceqaccessibletablemodelchangeeventmodelchangetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setModelChangeType, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setmodelchangetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, modelChangeType, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_modelchangetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setFirstRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setfirstrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setFirstColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setfirstcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setLastRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setlastrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setLastColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setlastcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, firstRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_firstrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, firstColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_firstcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, lastRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_lastrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, lastColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_lastcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_modelChangeType, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_modelchangetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_modelChangeType, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_modelchangetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_firstRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_firstrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_firstRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_firstrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_firstColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_firstcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_firstColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_firstcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_lastRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_lastrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_lastRow, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_lastrow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, m_lastColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_m_lastcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleTableModelChangeEvent_QAccessibleTableModelChangeEvent, setM_lastColumn, arginfo_qt_gui_qaccessibletablemodelchangeevent_qaccessibletablemodelchangeevent_setm_lastcolumn, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
