
extern zend_class_entry *qt_gui_qaccessiblefunctions_qaccessiblefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions);

PHP_METHOD(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions, qAccessibleRoleString);
PHP_METHOD(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions, qAccessibleEventString);
PHP_METHOD(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions, qAccessibleLocalizedActionDescription);

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_gui_qaccessiblefunctions_qaccessiblefunctions_qaccessiblerolestring, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, role, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_qt_gui_qaccessiblefunctions_qaccessiblefunctions_qaccessibleeventstring, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, event, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessiblefunctions_qaccessiblefunctions_qaccessiblelocalizedactiondescription, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, actionName, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessiblefunctions_qaccessiblefunctions_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions, qAccessibleRoleString, arginfo_qt_gui_qaccessiblefunctions_qaccessiblefunctions_qaccessiblerolestring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions, qAccessibleEventString, arginfo_qt_gui_qaccessiblefunctions_qaccessiblefunctions_qaccessibleeventstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleFunctions_QAccessibleFunctions, qAccessibleLocalizedActionDescription, arginfo_qt_gui_qaccessiblefunctions_qaccessiblefunctions_qaccessiblelocalizedactiondescription, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
