
extern zend_class_entry *qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_ce;

ZEPHIR_INIT_CLASS(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController);

PHP_METHOD(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, new_);
PHP_METHOD(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, newQTestQBenchmarkIterationControllerRunMode);
PHP_METHOD(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, isDone);
PHP_METHOD(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, next);
PHP_METHOD(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, i);
PHP_METHOD(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, setI);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_newqtestqbenchmarkiterationcontrollerrunmode, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, runMode, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_isdone, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_next, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_i, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_seti, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_method_entry) {
	PHP_ME(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, new_, arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, newQTestQBenchmarkIterationControllerRunMode, arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_newqtestqbenchmarkiterationcontrollerrunmode, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, isDone, arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_isdone, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, next, arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_next, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, i, arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_i, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Test_QTestQBenchmarkIterationController_QTestQBenchmarkIterationController, setI, arginfo_qt_test_qtestqbenchmarkiterationcontroller_qtestqbenchmarkiterationcontroller_seti, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
