
extern zend_class_entry *qt_core_qtweak_ordering_qtweak_ordering_ce;

ZEPHIR_INIT_CLASS(Qt_Core_Qtweak_ordering_Qtweak_ordering);

PHP_METHOD(Qt_Core_Qtweak_ordering_Qtweak_ordering, less);
PHP_METHOD(Qt_Core_Qtweak_ordering_Qtweak_ordering, equivalent);
PHP_METHOD(Qt_Core_Qtweak_ordering_Qtweak_ordering, greater);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtweak_ordering_qtweak_ordering_less, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtweak_ordering_qtweak_ordering_equivalent, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtweak_ordering_qtweak_ordering_greater, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qtweak_ordering_qtweak_ordering_method_entry) {
	PHP_ME(Qt_Core_Qtweak_ordering_Qtweak_ordering, less, arginfo_qt_core_qtweak_ordering_qtweak_ordering_less, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_Qtweak_ordering_Qtweak_ordering, equivalent, arginfo_qt_core_qtweak_ordering_qtweak_ordering_equivalent, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_Qtweak_ordering_Qtweak_ordering, greater, arginfo_qt_core_qtweak_ordering_qtweak_ordering_greater, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
