
extern zend_class_entry *qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent);

PHP_METHOD(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, new_);
PHP_METHOD(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, clone_);
PHP_METHOD(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, newQtApplicationState);
PHP_METHOD(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, applicationState);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_clone_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_newqtapplicationstate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, state, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_applicationstate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_method_entry) {
	PHP_ME(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, new_, arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, clone_, arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_clone_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, newQtApplicationState, arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_newqtapplicationstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QApplicationStateChangeEvent_QApplicationStateChangeEvent, applicationState, arginfo_qt_gui_qapplicationstatechangeevent_qapplicationstatechangeevent_applicationstate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
