
extern zend_class_entry *qt_core_qtnoopfunctions_qtnoopfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QTnoopFunctions_QTnoopFunctions);

PHP_METHOD(Qt_Core_QTnoopFunctions_QTnoopFunctions, qt_noop);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtnoopfunctions_qtnoopfunctions_qt_noop, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qtnoopfunctions_qtnoopfunctions_method_entry) {
	PHP_ME(Qt_Core_QTnoopFunctions_QTnoopFunctions, qt_noop, arginfo_qt_core_qtnoopfunctions_qtnoopfunctions_qt_noop, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
