// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QBitArray;

class QBitArray
{
    public static function new_() -> int
    {
        return qbitarray_new();
    }

    public static function newQsizetypeBool(int size, bool val = false) -> int
    {
        return qbitarray_new_qsizetype_bool(size, val);
    }

    public static function newQBitArray(int other) -> int
    {
        return qbitarray_new_q_bit_array(other);
    }

    public static function swap(int handle, int other) -> void
    {
        qbitarray_swap(handle, other);
    }

    public static function size(int handle) -> int
    {
        return qbitarray_size(handle);
    }

    public static function count(int handle) -> int
    {
        return qbitarray_count(handle);
    }

    public static function countBool(int handle, bool on) -> int
    {
        return qbitarray_count_bool(handle, on);
    }

    public static function isEmpty(int handle) -> bool
    {
        int r;

        let r = qbitarray_is_empty(handle);

        return r == 1;
    }

    public static function isNull(int handle) -> bool
    {
        int r;

        let r = qbitarray_is_null(handle);

        return r == 1;
    }

    public static function resize(int handle, int size) -> void
    {
        qbitarray_resize(handle, size);
    }

    public static function detach(int handle) -> void
    {
        qbitarray_detach(handle);
    }

    public static function isDetached(int handle) -> bool
    {
        int r;

        let r = qbitarray_is_detached(handle);

        return r == 1;
    }

    public static function clear(int handle) -> void
    {
        qbitarray_clear(handle);
    }

    public static function testBit(int handle, int i) -> bool
    {
        int r;

        let r = qbitarray_test_bit(handle, i);

        return r == 1;
    }

    public static function setBit(int handle, int i) -> void
    {
        qbitarray_set_bit(handle, i);
    }

    public static function setBitQsizetypeBool(int handle, int i, bool val) -> void
    {
        qbitarray_set_bit_qsizetype_bool(handle, i, val);
    }

    public static function clearBit(int handle, int i) -> void
    {
        qbitarray_clear_bit(handle, i);
    }

    public static function toggleBit(int handle, int i) -> bool
    {
        int r;

        let r = qbitarray_toggle_bit(handle, i);

        return r == 1;
    }

    public static function at(int handle, int i) -> bool
    {
        int r;

        let r = qbitarray_at(handle, i);

        return r == 1;
    }

    public static function fill(int handle, bool aval, int asize = -1) -> bool
    {
        int r;

        let r = qbitarray_fill(handle, aval, asize);

        return r == 1;
    }

    public static function fillBoolQsizetypeQsizetype(int handle, bool val, int first, int last) -> void
    {
        qbitarray_fill_bool_qsizetype_qsizetype(handle, val, first, last);
    }

    public static function truncate(int handle, int pos) -> void
    {
        qbitarray_truncate(handle, pos);
    }

    public static function bits(int handle) -> var
    {
        var result;

        let result = qbitarray_bits(handle);

        return result;
    }

    public static function fromBits(var data, int len) -> int
    {
        return qbitarray_from_bits(data, len);
    }

    public static function toUInt32(int handle, int endianness, var ok = null) -> array
    {
        var result;

        let result = qbitarray_to_u_int32(handle, endianness, ok);

        return result;
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved operator QBitArray & operator=(const QBitArray & other)
    // @reserved rvalue QBitArray(QBitArray && other)
    // @reserved operator QBitArray & operator=(QBitArray && other)
    // @reserved operator QBitRef operator[](qsizetype i)
    // @reserved operator bool operator[](qsizetype i) const
    // @reserved operator QBitArray & operator&=(QBitArray &&)
    // @reserved operator QBitArray & operator|=(QBitArray &&)
    // @reserved operator QBitArray & operator^=(QBitArray &&)
    // @reserved operator QBitArray & operator&=(const QBitArray &)
    // @reserved operator QBitArray & operator|=(const QBitArray &)
    // @reserved operator QBitArray & operator^=(const QBitArray &)
    // @reserved template QBitArray::DataPtr & data_ptr()
    // @reserved template const QBitArray::DataPtr & data_ptr() const

}
