
extern zend_class_entry *qt_opengl_qopenglversionstatus_qopenglversionstatus_ce;

ZEPHIR_INIT_CLASS(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus);

PHP_METHOD(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, new_);
PHP_METHOD(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, newIntIntQOpenGLVersionStatusOpenGLStatus);
PHP_METHOD(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, version);
PHP_METHOD(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, setVersion);
PHP_METHOD(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, status);
PHP_METHOD(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, setStatus);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_newintintqopenglversionstatusopenglstatus, 0, 3, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, majorVersion, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, minorVersion, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, functionStatus, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_version, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_setversion, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, value, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_status, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_setstatus, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_opengl_qopenglversionstatus_qopenglversionstatus_method_entry) {
	PHP_ME(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, new_, arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, newIntIntQOpenGLVersionStatusOpenGLStatus, arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_newintintqopenglversionstatusopenglstatus, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, version, arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_version, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, setVersion, arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_setversion, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, status, arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_status, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_OpenGL_QOpenGLVersionStatus_QOpenGLVersionStatus, setStatus, arginfo_qt_opengl_qopenglversionstatus_qopenglversionstatus_setstatus, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
