
extern zend_class_entry *qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext);

PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, new_);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, cursorPosition);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setCursorPosition);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, palette);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setPalette);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, clip);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setClip);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, selections);
PHP_METHOD(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setSelections);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_cursorposition, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setcursorposition, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_palette, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setpalette, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_clip, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setclip, 0, 5, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, valueX, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, valueY, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, valueWidth, IS_DOUBLE, 0)
	ZEND_ARG_TYPE_INFO(0, valueHeight, IS_DOUBLE, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_selections, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setselections, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_ARRAY_INFO(0, value, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_method_entry) {
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, new_, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, cursorPosition, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_cursorposition, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setCursorPosition, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setcursorposition, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, palette, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_palette, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setPalette, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setpalette, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, clip, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_clip, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setClip, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setclip, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, selections, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_selections, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAbstractTextDocumentLayoutPaintContext_QAbstractTextDocumentLayoutPaintContext, setSelections, arginfo_qt_gui_qabstracttextdocumentlayoutpaintcontext_qabstracttextdocumentlayoutpaintcontext_setselections, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
