
extern zend_class_entry *qt_xml_qdomcdatasection_qdomcdatasection_ce;

ZEPHIR_INIT_CLASS(Qt_Xml_QDomCDATASection_QDomCDATASection);

PHP_METHOD(Qt_Xml_QDomCDATASection_QDomCDATASection, new_);
PHP_METHOD(Qt_Xml_QDomCDATASection_QDomCDATASection, newQDomCDATASection);
PHP_METHOD(Qt_Xml_QDomCDATASection_QDomCDATASection, nodeType);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomcdatasection_qdomcdatasection_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomcdatasection_qdomcdatasection_newqdomcdatasection, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, cdataSection, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_xml_qdomcdatasection_qdomcdatasection_nodetype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_xml_qdomcdatasection_qdomcdatasection_method_entry) {
	PHP_ME(Qt_Xml_QDomCDATASection_QDomCDATASection, new_, arginfo_qt_xml_qdomcdatasection_qdomcdatasection_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomCDATASection_QDomCDATASection, newQDomCDATASection, arginfo_qt_xml_qdomcdatasection_qdomcdatasection_newqdomcdatasection, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Xml_QDomCDATASection_QDomCDATASection, nodeType, arginfo_qt_xml_qdomcdatasection_qdomcdatasection_nodetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
