// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Network\QNetworkdatagramFunctions;

class QNetworkdatagramFunctions
{
    public static function swap(int value1, int value2) -> void
    {
        qnetworkdatagramfunctions_swap(value1, value2);
    }

    public static function qRegisterNormalizedMetaType_QNetworkDatagram(string arg0) -> int
    {
        return qnetworkdatagramfunctions_q_register_normalized_meta_type__q_network_datagram(arg0);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved template int qRegisterNormalizedMetaType(const QByteArray & normalizedTypeName)

}
