// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Core\QPermission;

class QPermission
{
    public static function new_() -> int
    {
        return qpermission_new();
    }

    public static function status(int handle) -> int
    {
        return qpermission_status(handle);
    }

    public static function type(int handle) -> int
    {
        return qpermission_type(handle);
    }
}
