// GENERATED by scripts/gen-zep.php — DO NOT EDIT.
// Source of truth: the @zep/@zep-construct/@reserved annotations in src/*.h.

namespace Qt\Network\QNetworkDatagram;

class QNetworkDatagram
{
    public static function new_() -> int
    {
        return qnetworkdatagram_new();
    }

    public static function newQByteArrayQHostAddressQuint16(string data, var destinationAddress = null, int port = 0) -> int
    {
        return qnetworkdatagram_new_q_byte_array_q_host_address_quint16(data, destinationAddress, port);
    }

    public static function newQNetworkDatagram(int other) -> int
    {
        return qnetworkdatagram_new_q_network_datagram(other);
    }

    public static function swap(int handle, int other) -> void
    {
        qnetworkdatagram_swap(handle, other);
    }

    public static function clear(int handle) -> void
    {
        qnetworkdatagram_clear(handle);
    }

    public static function isValid(int handle) -> bool
    {
        int r;

        let r = qnetworkdatagram_is_valid(handle);

        return r == 1;
    }

    public static function isNull(int handle) -> bool
    {
        int r;

        let r = qnetworkdatagram_is_null(handle);

        return r == 1;
    }

    public static function interfaceIndex(int handle) -> int
    {
        return qnetworkdatagram_interface_index(handle);
    }

    public static function setInterfaceIndex(int handle, int index) -> void
    {
        qnetworkdatagram_set_interface_index(handle, index);
    }

    public static function senderAddress(int handle) -> int
    {
        return qnetworkdatagram_sender_address(handle);
    }

    public static function destinationAddress(int handle) -> int
    {
        return qnetworkdatagram_destination_address(handle);
    }

    public static function senderPort(int handle) -> int
    {
        return qnetworkdatagram_sender_port(handle);
    }

    public static function destinationPort(int handle) -> int
    {
        return qnetworkdatagram_destination_port(handle);
    }

    public static function setSender(int handle, int address, int port = 0) -> void
    {
        qnetworkdatagram_set_sender(handle, address, port);
    }

    public static function setDestination(int handle, int address, int port) -> void
    {
        qnetworkdatagram_set_destination(handle, address, port);
    }

    public static function hopLimit(int handle) -> int
    {
        return qnetworkdatagram_hop_limit(handle);
    }

    public static function setHopLimit(int handle, int count) -> void
    {
        qnetworkdatagram_set_hop_limit(handle, count);
    }

    public static function data(int handle) -> string
    {
        var result;

        let result = qnetworkdatagram_data(handle);

        return result;
    }

    public static function setData(int handle, string data) -> void
    {
        qnetworkdatagram_set_data(handle, data);
    }

    public static function makeReply(int handle, string payload) -> int
    {
        return qnetworkdatagram_make_reply(handle, payload);
    }

    // ---- @reserved (not bound; see src/*.h) ----
    // @reserved operator QNetworkDatagram & operator=(const QNetworkDatagram & other)
    // @reserved rvalue QNetworkDatagram(QNetworkDatagram && other)
    // @reserved operator QNetworkDatagram & operator=(QNetworkDatagram && other)

}
