
extern zend_class_entry *qt_core_qoperatingsystemversion_qoperatingsystemversion_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion);

PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows7);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows8);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows8_1);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, OSXMavericks);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, OSXYosemite);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, OSXElCapitan);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSSierra);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSHighSierra);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSMojave);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSCatalina);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSBigSur);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSMonterey);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidJellyBean);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidJellyBean_MR1);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidJellyBean_MR2);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidKitKat);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidLollipop);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidLollipop_MR1);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidMarshmallow);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidNougat);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidNougat_MR1);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidOreo);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidOreo_MR1);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidPie);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android10);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android11);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_1809);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_1903);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_1909);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_2004);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_20H2);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_21H1);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_21H2);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_22H2);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows11);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows11_21H2);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows11_22H2);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android12);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android12L);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android13);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSVentura);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, new_);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, newQOperatingSystemVersionOSTypeIntIntInt);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, currentType);
PHP_METHOD(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, type);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows7, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows8, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows8_1, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_osxmavericks, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_osxyosemite, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_osxelcapitan, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macossierra, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macoshighsierra, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosmojave, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macoscatalina, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosbigsur, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosmonterey, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidjellybean, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidjellybean_mr1, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidjellybean_mr2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidkitkat, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidlollipop, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidlollipop_mr1, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidmarshmallow, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidnougat, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidnougat_mr1, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidoreo, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidoreo_mr1, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidpie, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android10, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android11, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_1809, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_1903, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_1909, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_2004, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_20h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_21h1, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_21h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_22h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows11, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows11_21h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows11_22h2, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android12, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android12l, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android13, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosventura, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, osversion, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_newqoperatingsystemversionostypeintintint, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, osType, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, vmajor, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, vminor, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, vmicro, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_currenttype, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_type, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qoperatingsystemversion_qoperatingsystemversion_method_entry) {
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows7, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows7, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows8, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows8, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows8_1, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows8_1, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, OSXMavericks, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_osxmavericks, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, OSXYosemite, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_osxyosemite, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, OSXElCapitan, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_osxelcapitan, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSSierra, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macossierra, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSHighSierra, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macoshighsierra, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSMojave, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosmojave, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSCatalina, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macoscatalina, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSBigSur, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosbigsur, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSMonterey, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosmonterey, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidJellyBean, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidjellybean, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidJellyBean_MR1, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidjellybean_mr1, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidJellyBean_MR2, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidjellybean_mr2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidKitKat, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidkitkat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidLollipop, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidlollipop, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidLollipop_MR1, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidlollipop_mr1, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidMarshmallow, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidmarshmallow, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidNougat, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidnougat, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidNougat_MR1, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidnougat_mr1, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidOreo, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidoreo, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidOreo_MR1, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidoreo_mr1, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, AndroidPie, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_androidpie, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android10, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android10, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android11, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android11, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_1809, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_1809, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_1903, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_1903, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_1909, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_1909, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_2004, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_2004, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_20H2, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_20h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_21H1, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_21h1, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_21H2, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_21h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows10_22H2, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows10_22h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows11, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows11, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows11_21H2, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows11_21h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Windows11_22H2, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_windows11_22h2, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android12, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android12, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android12L, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android12l, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, Android13, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_android13, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, MacOSVentura, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_macosventura, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, new_, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, newQOperatingSystemVersionOSTypeIntIntInt, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_newqoperatingsystemversionostypeintintint, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, currentType, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_currenttype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QOperatingSystemVersion_QOperatingSystemVersion, type, arginfo_qt_core_qoperatingsystemversion_qoperatingsystemversion_type, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
