
extern zend_class_entry *qt_core_qregularexpressionfunctions_qregularexpressionfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions);

PHP_METHOD(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, qHash);
PHP_METHOD(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, swap);
PHP_METHOD(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, swapQRegularExpressionMatchQRegularExpressionMatch);
PHP_METHOD(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, comparesEqual);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, key, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_swapqregularexpressionmatchqregularexpressionmatch, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qregularexpressionfunctions_qregularexpressionfunctions_method_entry) {
	PHP_ME(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, qHash, arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, swap, arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, swapQRegularExpressionMatchQRegularExpressionMatch, arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_swapqregularexpressionmatchqregularexpressionmatch, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QRegularexpressionFunctions_QRegularexpressionFunctions, comparesEqual, arginfo_qt_core_qregularexpressionfunctions_qregularexpressionfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
