/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qbytearraymatcher.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "core-qstaticbytearraymatcherbase.h"

