/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qnumeric.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "core-qnumericfunctions.h"

extern "C" zend_long phpqt_qnumericfunctions_q_is_inf(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return (qIsInf(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_na_n(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return (qIsNaN(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_finite(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return (qIsFinite(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_fp_classify(zval *p_val)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_val));
    return static_cast<zend_long>(qFpClassify(a0)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_inf_float(zval *p_f)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_f));
    return (qIsInf(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_na_n_float(zval *p_f)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_f));
    return (qIsNaN(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_finite_float(zval *p_f)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_f));
    return (qIsFinite(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_fp_classify_float(zval *p_val)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_val));
    return static_cast<zend_long>(qFpClassify(a0)); /* native */
}

extern "C" double phpqt_qnumericfunctions_q_s_na_n(void)
{
    return static_cast<double>(qSNaN()); /* native */
}

extern "C" double phpqt_qnumericfunctions_q_q_na_n(void)
{
    return static_cast<double>(qQNaN()); /* native */
}

extern "C" double phpqt_qnumericfunctions_q_inf(void)
{
    return static_cast<double>(qInf()); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_float_distance(zval *p_a, zval *p_b)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_a));
    float a1 = static_cast<float>(phpqt::arg_double(p_b));
    return static_cast<zend_long>(qFloatDistance(a0, a1)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_float_distance_double_double(zval *p_a, zval *p_b)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_a));
    double a1 = static_cast<double>(phpqt::arg_double(p_b));
    return static_cast<zend_long>(qFloatDistance(a0, a1)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_round(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return static_cast<zend_long>(qRound(a0)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_round_float(zval *p_d)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_d));
    return static_cast<zend_long>(qRound(a0)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_round64(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return static_cast<zend_long>(qRound64(a0)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_round64_float(zval *p_d)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_d));
    return static_cast<zend_long>(qRound64(a0)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_fuzzy_compare(zval *p_p1, zval *p_p2)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_p1));
    double a1 = static_cast<double>(phpqt::arg_double(p_p2));
    return (qFuzzyCompare(a0, a1)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_fuzzy_compare_float_float(zval *p_p1, zval *p_p2)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_p1));
    float a1 = static_cast<float>(phpqt::arg_double(p_p2));
    return (qFuzzyCompare(a0, a1)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_fuzzy_is_null(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return (qFuzzyIsNull(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_fuzzy_is_null_float(zval *p_f)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_f));
    return (qFuzzyIsNull(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_null(zval *p_d)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_d));
    return (qIsNull(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_is_null_float(zval *p_f)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_f));
    return (qIsNull(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_int_cast(zval *p_f)
{
    double a0 = static_cast<double>(phpqt::arg_double(p_f));
    return static_cast<zend_long>(qIntCast(a0)); /* native */
}

extern "C" zend_long phpqt_qnumericfunctions_q_int_cast_float(zval *p_f)
{
    float a0 = static_cast<float>(phpqt::arg_double(p_f));
    return static_cast<zend_long>(qIntCast(a0)); /* native */
}

