/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qcoreevent.h>
#include <QtCore/qdeadlinetimer.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qrunnable.h>
#include <QtCore/qthread.h>
#include <QtCore/qthreadpool.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQThreadPool : public QThreadPool {
public:
    PhpQtQThreadPool(QObject * p0) : QThreadPool(p0) {}
    ~PhpQtQThreadPool();
    bool event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::event(std::declval<QEvent *>()))) override;
    bool eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>()))) override;
    void timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::timerEvent(std::declval<QTimerEvent *>()))) override;
    void childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::childEvent(std::declval<QChildEvent *>()))) override;
    void customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::customEvent(std::declval<QEvent *>()))) override;
    void connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::connectNotify(std::declval<const QMetaMethod &>()))) override;
    void disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQThreadPool &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>()))) override;
    static const char *const kOverridable[];
};
