/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtDBus/qdbusunixfiledescriptor.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "dbus-qdbusunixfiledescriptorfunctions.h"

extern "C" void phpqt_qdbusunixfiledescriptorfunctions_swap(zval *p_value1, zval *p_value2)
{
    QDBusUnixFileDescriptor *a0_p = phpqt::is_null(p_value1) ? nullptr : phpqt::as<QDBusUnixFileDescriptor>(p_value1, PHPQT_TAG_QDBusUnixFileDescriptor);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "swap: value1 is not a QDBusUnixFileDescriptor handle"); return; }
    QDBusUnixFileDescriptor *a1_p = phpqt::is_null(p_value2) ? nullptr : phpqt::as<QDBusUnixFileDescriptor>(p_value2, PHPQT_TAG_QDBusUnixFileDescriptor);
    if (a1_p == nullptr) { php_error_docref(NULL, E_WARNING, "swap: value2 is not a QDBusUnixFileDescriptor handle"); return; }
    swap(*a0_p, *a1_p); /* native */
}

extern "C" zend_long phpqt_qdbusunixfiledescriptorfunctions_q_register_normalized_meta_type__q_d_bus_unix_file_descriptor(zval *p_arg0)
{
    QByteArray a0 = phpqt::arg_bytes(p_arg0);
    return static_cast<zend_long>(qRegisterNormalizedMetaType_QDBusUnixFileDescriptor(a0)); /* native */
}

