/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtGui/qtextobject.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "gui-qtextblockiterator.h"

extern "C" zend_long phpqt_qtextblockiterator_new(void)
{
    auto *obj = new QTextBlock::iterator(); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QTextBlockiterator, true, false);
}

extern "C" zend_long phpqt_qtextblockiterator_fragment(zval *p_handle)
{
    QTextBlock::iterator *self = phpqt::as<QTextBlock::iterator>(p_handle, PHPQT_TAG_QTextBlockiterator);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QTextBlock::iterator::fragment: handle is not a QTextBlock::iterator"); return 0; }
    return phpqt::reg(new QTextFragment(self->fragment()), PHPQT_TAG_QTextFragment, true); /* native */
}

extern "C" zend_long phpqt_qtextblockiterator_at_end(zval *p_handle)
{
    QTextBlock::iterator *self = phpqt::as<QTextBlock::iterator>(p_handle, PHPQT_TAG_QTextBlockiterator);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QTextBlock::iterator::atEnd: handle is not a QTextBlock::iterator"); return 0; }
    return (self->atEnd()) ? 1 : 0; /* native */
}

