/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_GUI_QACCESSIBLEOBJECT_H
#define PHPQT_GUI_QACCESSIBLEOBJECT_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast QAccessibleObject(QObject * object) */
/*@zep Gui\QAccessibleObject new(int object) -> int */
zend_long phpqt_qaccessibleobject_new(zval *p_object);

/*@ast bool isValid() const */
/*@zep Gui\QAccessibleObject isValid(int handle) -> bool */
zend_long phpqt_qaccessibleobject_is_valid(zval *p_handle);

/*@ast QObject * object() const */
/*@zep Gui\QAccessibleObject object(int handle) -> int */
zend_long phpqt_qaccessibleobject_object(zval *p_handle);

/*@ast QRect rect() const */
/*@zep Gui\QAccessibleObject rect(int handle) -> array */
void phpqt_qaccessibleobject_rect(zval *return_value, zval *p_handle);

/*@ast void setText(QAccessible::Text t, const QString & text) */
/*@zep Gui\QAccessibleObject setText(int handle, int t, string text) -> void */
void phpqt_qaccessibleobject_set_text(zval *p_handle, zval *p_t, zval *p_text);

/*@ast QAccessibleInterface * childAt(int x, int y) const */
/*@zep Gui\QAccessibleObject childAt(int handle, int x, int y) -> int */
zend_long phpqt_qaccessibleobject_child_at(zval *p_handle, zval *p_x, zval *p_y);

/*@override Gui\QAccessibleObject isValid bool isValid() const */
/*@override Gui\QAccessibleObject object QObject * object() const */
/*@override Gui\QAccessibleObject rect QRect rect() const */
/*@override Gui\QAccessibleObject setText void setText(QAccessible::Text t, const QString & text) */
/*@override Gui\QAccessibleObject childAt QAccessibleInterface * childAt(int x, int y) const */
/*@override Gui\QAccessibleObject window QWindow * window() const */
/*@override Gui\QAccessibleObject relations QList<std::pair<QAccessibleInterface *, QFlags<QAccessible::RelationFlag>>> relations(QAccessible::Relation match) const */
/*@override Gui\QAccessibleObject focusChild QAccessibleInterface * focusChild() const */
/*@override Gui\QAccessibleObject parent QAccessibleInterface * parent() const */
/*@override Gui\QAccessibleObject child QAccessibleInterface * child(int index) const */
/*@override Gui\QAccessibleObject childCount int childCount() const */
/*@override Gui\QAccessibleObject indexOfChild int indexOfChild(const QAccessibleInterface *) const */
/*@override Gui\QAccessibleObject text QString text(QAccessible::Text t) const */
/*@override Gui\QAccessibleObject role QAccessible::Role role() const */
/*@override Gui\QAccessibleObject state QAccessible::State state() const */
/*@override Gui\QAccessibleObject foregroundColor QColor foregroundColor() const */
/*@override Gui\QAccessibleObject backgroundColor QColor backgroundColor() const */
/*@reserved-override Gui\QAccessibleObject raw-pointer void virtual_hook(int id, void * data) */
/*@reserved-override Gui\QAccessibleObject raw-pointer void * interface_cast(QAccessible::InterfaceType) */

#ifdef __cplusplus
}
#endif
#endif
