/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qcoreevent.h>
#include <QtCore/qflags.h>
#include <QtCore/qmargins.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
#include <QtCore/qsize.h>
#include <QtGui/qaccessible.h>
#include <QtGui/qcursor.h>
#include <QtGui/qevent.h>
#include <QtGui/qicon.h>
#include <QtGui/qregion.h>
#include <QtGui/qscreen.h>
#include <QtGui/qsurface.h>
#include <QtGui/qsurfaceformat.h>
#include <QtGui/qwindow.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQWindow : public QWindow {
public:
    PhpQtQWindow(QScreen * p0) : QWindow(p0) {}
    PhpQtQWindow(QWindow * p0) : QWindow(p0) {}
    ~PhpQtQWindow();
    QSurface::SurfaceType surfaceType() const noexcept(noexcept(std::declval<const PhpQtQWindow &>().QWindow::surfaceType())) override;
    QSurfaceFormat format() const noexcept(noexcept(std::declval<const PhpQtQWindow &>().QWindow::format())) override;
    QSize size() const noexcept(noexcept(std::declval<const PhpQtQWindow &>().QWindow::size())) override;
    QAccessibleInterface * accessibleRoot() const noexcept(noexcept(std::declval<const PhpQtQWindow &>().QWindow::accessibleRoot())) override;
    QObject * focusObject() const noexcept(noexcept(std::declval<const PhpQtQWindow &>().QWindow::focusObject())) override;
    void exposeEvent(QExposeEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::exposeEvent(std::declval<QExposeEvent *>()))) override;
    void resizeEvent(QResizeEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::resizeEvent(std::declval<QResizeEvent *>()))) override;
    void paintEvent(QPaintEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::paintEvent(std::declval<QPaintEvent *>()))) override;
    void moveEvent(QMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::moveEvent(std::declval<QMoveEvent *>()))) override;
    void focusInEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::focusInEvent(std::declval<QFocusEvent *>()))) override;
    void focusOutEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::focusOutEvent(std::declval<QFocusEvent *>()))) override;
    void showEvent(QShowEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::showEvent(std::declval<QShowEvent *>()))) override;
    void hideEvent(QHideEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::hideEvent(std::declval<QHideEvent *>()))) override;
    void closeEvent(QCloseEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::closeEvent(std::declval<QCloseEvent *>()))) override;
    bool event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::event(std::declval<QEvent *>()))) override;
    void keyPressEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::keyPressEvent(std::declval<QKeyEvent *>()))) override;
    void keyReleaseEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::keyReleaseEvent(std::declval<QKeyEvent *>()))) override;
    void mousePressEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::mousePressEvent(std::declval<QMouseEvent *>()))) override;
    void mouseReleaseEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::mouseReleaseEvent(std::declval<QMouseEvent *>()))) override;
    void mouseDoubleClickEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::mouseDoubleClickEvent(std::declval<QMouseEvent *>()))) override;
    void mouseMoveEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::mouseMoveEvent(std::declval<QMouseEvent *>()))) override;
    void wheelEvent(QWheelEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::wheelEvent(std::declval<QWheelEvent *>()))) override;
    void touchEvent(QTouchEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::touchEvent(std::declval<QTouchEvent *>()))) override;
    void tabletEvent(QTabletEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QWindow::tabletEvent(std::declval<QTabletEvent *>()))) override;
    bool eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQWindow &>().QObject::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>()))) override;
    void timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QObject::timerEvent(std::declval<QTimerEvent *>()))) override;
    void childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QObject::childEvent(std::declval<QChildEvent *>()))) override;
    void customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QObject::customEvent(std::declval<QEvent *>()))) override;
    void connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QObject::connectNotify(std::declval<const QMetaMethod &>()))) override;
    void disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQWindow &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>()))) override;
    void phpqt_fwd_exposeEvent(QExposeEvent * p0) { exposeEvent(p0); }
    void phpqt_fwd_resizeEvent(QResizeEvent * p0) { resizeEvent(p0); }
    void phpqt_fwd_paintEvent(QPaintEvent * p0) { paintEvent(p0); }
    void phpqt_fwd_moveEvent(QMoveEvent * p0) { moveEvent(p0); }
    void phpqt_fwd_focusInEvent(QFocusEvent * p0) { focusInEvent(p0); }
    void phpqt_fwd_focusOutEvent(QFocusEvent * p0) { focusOutEvent(p0); }
    void phpqt_fwd_showEvent(QShowEvent * p0) { showEvent(p0); }
    void phpqt_fwd_hideEvent(QHideEvent * p0) { hideEvent(p0); }
    void phpqt_fwd_closeEvent(QCloseEvent * p0) { closeEvent(p0); }
    bool phpqt_fwd_event(QEvent * p0) { return event(p0); }
    void phpqt_fwd_keyPressEvent(QKeyEvent * p0) { keyPressEvent(p0); }
    void phpqt_fwd_keyReleaseEvent(QKeyEvent * p0) { keyReleaseEvent(p0); }
    void phpqt_fwd_mousePressEvent(QMouseEvent * p0) { mousePressEvent(p0); }
    void phpqt_fwd_mouseReleaseEvent(QMouseEvent * p0) { mouseReleaseEvent(p0); }
    void phpqt_fwd_mouseDoubleClickEvent(QMouseEvent * p0) { mouseDoubleClickEvent(p0); }
    void phpqt_fwd_mouseMoveEvent(QMouseEvent * p0) { mouseMoveEvent(p0); }
    void phpqt_fwd_wheelEvent(QWheelEvent * p0) { wheelEvent(p0); }
    void phpqt_fwd_touchEvent(QTouchEvent * p0) { touchEvent(p0); }
    void phpqt_fwd_tabletEvent(QTabletEvent * p0) { tabletEvent(p0); }
    static const char *const kOverridable[];
};
