/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_GUI_QABSTRACTTEXTDOCUMENTLAYOUTSELECTION_H
#define PHPQT_GUI_QABSTRACTTEXTDOCUMENTLAYOUTSELECTION_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast QTextCursor cursor */
/*@zep Gui\QAbstractTextDocumentLayoutSelection cursor(int handle) -> int */
zend_long phpqt_qabstracttextdocumentlayoutselection_cursor(zval *p_handle);

/*@ast QTextCursor cursor (set) */
/*@zep Gui\QAbstractTextDocumentLayoutSelection setCursor(int handle, int value) -> void */
void phpqt_qabstracttextdocumentlayoutselection_set_cursor(zval *p_handle, zval *p_value);

/*@ast QTextCharFormat format */
/*@zep Gui\QAbstractTextDocumentLayoutSelection format(int handle) -> int */
zend_long phpqt_qabstracttextdocumentlayoutselection_format(zval *p_handle);

/*@ast QTextCharFormat format (set) */
/*@zep Gui\QAbstractTextDocumentLayoutSelection setFormat(int handle, int value) -> void */
void phpqt_qabstracttextdocumentlayoutselection_set_format(zval *p_handle, zval *p_value);


#ifdef __cplusplus
}
#endif
#endif
