/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include "gui-qinputmethodevent-shell.h"

PhpQtQInputMethodEvent::~PhpQtQInputMethodEvent()
{
    phpqt::forget_canon(phpqt::canon_impl(static_cast<QInputMethodEvent *>(this)));
}

QInputMethodEvent * PhpQtQInputMethodEvent::clone() const noexcept(noexcept(std::declval<const PhpQtQInputMethodEvent &>().QInputMethodEvent::clone()))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(const_cast<QInputMethodEvent *>(static_cast<const QInputMethodEvent *>(this))), "clone");
    if (fn == nullptr) { return QInputMethodEvent::clone(); }
    zval argv[1];
    ZVAL_LONG(&argv[0], phpqt::reg(const_cast<QInputMethodEvent *>(static_cast<const QInputMethodEvent *>(this)), PHPQT_TAG_QInputMethodEvent, false));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 1, argv, &ret);
    if (!ok) { zval_ptr_dtor(&ret); return QInputMethodEvent::clone(); }
    QInputMethodEvent * r = phpqt::as<QInputMethodEvent>(&ret, PHPQT_TAG_QInputMethodEvent);
    zval_ptr_dtor(&ret);
    return r;
}

void PhpQtQInputMethodEvent::setAccepted(bool p0) noexcept(noexcept(std::declval<PhpQtQInputMethodEvent &>().QEvent::setAccepted(std::declval<bool>())))
{
    zval *fn = phpqt::override_lookup(phpqt::canon_impl(static_cast<QInputMethodEvent *>(this)), "setAccepted");
    if (fn == nullptr) { QEvent::setAccepted(p0); return; }
    zval argv[2];
    ZVAL_LONG(&argv[0], phpqt::reg(static_cast<QInputMethodEvent *>(this), PHPQT_TAG_QInputMethodEvent, false));
    ZVAL_BOOL(&argv[1], (p0));
    zval ret;
    ZVAL_UNDEF(&ret);
    bool ok = phpqt::call(fn, 2, argv, &ret);
    (void) ok;
    zval_ptr_dtor(&ret);
}

const char *const PhpQtQInputMethodEvent::kOverridable[] = { "clone", "setAccepted", nullptr };
