/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qcoreevent.h>
#include <QtCore/qflags.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtGui/qevent.h>
#include <QtGui/qpointingdevice.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQWheelEvent : public QWheelEvent {
public:
    PhpQtQWheelEvent(const QWheelEvent & p0) : QWheelEvent(p0) {}
    PhpQtQWheelEvent(const QPointF & p0, const QPointF & p1, QPoint p2, QPoint p3, Qt::MouseButtons p4, Qt::KeyboardModifiers p5, Qt::ScrollPhase p6, bool p7, Qt::MouseEventSource p8, const QPointingDevice * p9) : QWheelEvent(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) {}
    ~PhpQtQWheelEvent();
    using phpqt_QEvent_SinglePointEventTag = QEvent::SinglePointEventTag;
    using phpqt_QEvent_PointerEventTag = QEvent::PointerEventTag;
    using phpqt_QEvent_InputEventTag = QEvent::InputEventTag;
    QWheelEvent * clone() const noexcept(noexcept(std::declval<const PhpQtQWheelEvent &>().QWheelEvent::clone())) override;
    bool isBeginEvent() const noexcept(noexcept(std::declval<const PhpQtQWheelEvent &>().QWheelEvent::isBeginEvent())) override;
    bool isUpdateEvent() const noexcept(noexcept(std::declval<const PhpQtQWheelEvent &>().QWheelEvent::isUpdateEvent())) override;
    bool isEndEvent() const noexcept(noexcept(std::declval<const PhpQtQWheelEvent &>().QWheelEvent::isEndEvent())) override;
    void setTimestamp(quint64 p0) noexcept(noexcept(std::declval<PhpQtQWheelEvent &>().QPointerEvent::setTimestamp(std::declval<quint64>()))) override;
    void setAccepted(bool p0) noexcept(noexcept(std::declval<PhpQtQWheelEvent &>().QPointerEvent::setAccepted(std::declval<bool>()))) override;
    decltype(auto) phpqt_fwd_m_pixelDelta() const { return (m_pixelDelta); }
    void phpqt_fwd_setM_pixelDelta(QPoint p0) { m_pixelDelta = p0; }
    decltype(auto) phpqt_fwd_m_angleDelta() const { return (m_angleDelta); }
    void phpqt_fwd_setM_angleDelta(QPoint p0) { m_angleDelta = p0; }
    static const char *const kOverridable[];
};
