/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_NETWORK_QSSLCERTIFICATEEXTENSIONFUNCTIONS_H
#define PHPQT_NETWORK_QSSLCERTIFICATEEXTENSIONFUNCTIONS_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast void swap(QSslCertificateExtension & value1, QSslCertificateExtension & value2) */
/*@zep Network\QSslcertificateextensionFunctions swap(int value1, int value2) -> void */
void phpqt_qsslcertificateextensionfunctions_swap(zval *p_value1, zval *p_value2);


#ifdef __cplusplus
}
#endif
#endif
