/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QGRAPHICSOPACITYEFFECT_H
#define PHPQT_WIDGETS_QGRAPHICSOPACITYEFFECT_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QGraphicsOpacityEffect staticMetaObject() -> int */
zend_long phpqt_qgraphicsopacityeffect_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QGraphicsOpacityEffect tr(var s, var c = null, int n = -1) -> string */
void phpqt_qgraphicsopacityeffect_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QGraphicsOpacityEffect(QObject * parent) */
/*@zep Widgets\QGraphicsOpacityEffect new(int parent = 0) -> int */
zend_long phpqt_qgraphicsopacityeffect_new(zval *p_parent);

/*@ast qreal opacity() const */
/*@zep Widgets\QGraphicsOpacityEffect opacity(int handle) -> double */
double phpqt_qgraphicsopacityeffect_opacity(zval *p_handle);

/*@ast QBrush opacityMask() const */
/*@zep Widgets\QGraphicsOpacityEffect opacityMask(int handle) -> int */
zend_long phpqt_qgraphicsopacityeffect_opacity_mask(zval *p_handle);

/*@ast void setOpacity(qreal opacity) */
/*@zep Widgets\QGraphicsOpacityEffect setOpacity(int handle, double opacity) -> void */
void phpqt_qgraphicsopacityeffect_set_opacity(zval *p_handle, zval *p_opacity);

/*@ast void setOpacityMask(const QBrush & mask) */
/*@zep Widgets\QGraphicsOpacityEffect setOpacityMask(int handle, int mask) -> void */
void phpqt_qgraphicsopacityeffect_set_opacity_mask(zval *p_handle, zval *p_mask);

/*@ast void opacityChanged(qreal opacity) */
/*@zep Widgets\QGraphicsOpacityEffect opacityChanged(int handle, double opacity) -> void */
void phpqt_qgraphicsopacityeffect_opacity_changed(zval *p_handle, zval *p_opacity);

/*@ast void opacityMaskChanged(const QBrush & mask) */
/*@zep Widgets\QGraphicsOpacityEffect opacityMaskChanged(int handle, int mask) -> void */
void phpqt_qgraphicsopacityeffect_opacity_mask_changed(zval *p_handle, zval *p_mask);

/*@ast void draw(QPainter * painter) */
/*@zep Widgets\QGraphicsOpacityEffect draw(int handle, int painter) -> void */
void phpqt_qgraphicsopacityeffect_draw(zval *p_handle, zval *p_painter);

/*@override Widgets\QGraphicsOpacityEffect draw void draw(QPainter * painter) */
/*@override Widgets\QGraphicsOpacityEffect boundingRectFor QRectF boundingRectFor(const QRectF & sourceRect) const */
/*@override Widgets\QGraphicsOpacityEffect sourceChanged void sourceChanged(QGraphicsEffect::ChangeFlags flags) */
/*@override Widgets\QGraphicsOpacityEffect event bool event(QEvent * event) */
/*@override Widgets\QGraphicsOpacityEffect eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Widgets\QGraphicsOpacityEffect timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QGraphicsOpacityEffect childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QGraphicsOpacityEffect customEvent void customEvent(QEvent * event) */
/*@override Widgets\QGraphicsOpacityEffect connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QGraphicsOpacityEffect disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
