/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QABSTRACTITEMDELEGATE_H
#define PHPQT_WIDGETS_QABSTRACTITEMDELEGATE_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QAbstractItemDelegate staticMetaObject() -> int */
zend_long phpqt_qabstractitemdelegate_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QAbstractItemDelegate tr(var s, var c = null, int n = -1) -> string */
void phpqt_qabstractitemdelegate_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QAbstractItemDelegate(QObject * parent) */
/*@zep Widgets\QAbstractItemDelegate new(int parent = 0) -> int */
zend_long phpqt_qabstractitemdelegate_new(zval *p_parent);

/*@ast void paint(QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate paint(int handle, int painter, int option, int index) -> void */
void phpqt_qabstractitemdelegate_paint(zval *p_handle, zval *p_painter, zval *p_option, zval *p_index);

/*@ast QSize sizeHint(const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate sizeHint(int handle, int option, int index) -> array */
void phpqt_qabstractitemdelegate_size_hint(zval *return_value, zval *p_handle, zval *p_option, zval *p_index);

/*@ast QWidget * createEditor(QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate createEditor(int handle, int parent, int option, int index) -> int */
zend_long phpqt_qabstractitemdelegate_create_editor(zval *p_handle, zval *p_parent, zval *p_option, zval *p_index);

/*@ast void destroyEditor(QWidget * editor, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate destroyEditor(int handle, int editor, int index) -> void */
void phpqt_qabstractitemdelegate_destroy_editor(zval *p_handle, zval *p_editor, zval *p_index);

/*@ast void setEditorData(QWidget * editor, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate setEditorData(int handle, int editor, int index) -> void */
void phpqt_qabstractitemdelegate_set_editor_data(zval *p_handle, zval *p_editor, zval *p_index);

/*@ast void setModelData(QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate setModelData(int handle, int editor, int model, int index) -> void */
void phpqt_qabstractitemdelegate_set_model_data(zval *p_handle, zval *p_editor, zval *p_model, zval *p_index);

/*@ast void updateEditorGeometry(QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@zep Widgets\QAbstractItemDelegate updateEditorGeometry(int handle, int editor, int option, int index) -> void */
void phpqt_qabstractitemdelegate_update_editor_geometry(zval *p_handle, zval *p_editor, zval *p_option, zval *p_index);

/*@ast bool editorEvent(QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) */
/*@zep Widgets\QAbstractItemDelegate editorEvent(int handle, int event, int model, int option, int index) -> bool */
zend_long phpqt_qabstractitemdelegate_editor_event(zval *p_handle, zval *p_event, zval *p_model, zval *p_option, zval *p_index);

/*@ast bool helpEvent(QHelpEvent * event, QAbstractItemView * view, const QStyleOptionViewItem & option, const QModelIndex & index) */
/*@zep Widgets\QAbstractItemDelegate helpEvent(int handle, int event, int view, int option, int index) -> bool */
zend_long phpqt_qabstractitemdelegate_help_event(zval *p_handle, zval *p_event, zval *p_view, zval *p_option, zval *p_index);

/*@ast QList<int> paintingRoles() const */
/*@zep Widgets\QAbstractItemDelegate paintingRoles(int handle) -> array */
void phpqt_qabstractitemdelegate_painting_roles(zval *return_value, zval *p_handle);

/*@ast void commitData(QWidget * editor) */
/*@zep Widgets\QAbstractItemDelegate commitData(int handle, int editor) -> void */
void phpqt_qabstractitemdelegate_commit_data(zval *p_handle, zval *p_editor);

/*@ast void closeEditor(QWidget * editor, QAbstractItemDelegate::EndEditHint hint) */
/*@zep Widgets\QAbstractItemDelegate closeEditor(int handle, int editor, var hint = null) -> void */
void phpqt_qabstractitemdelegate_close_editor(zval *p_handle, zval *p_editor, zval *p_hint);

/*@ast void sizeHintChanged(const QModelIndex &) */
/*@zep Widgets\QAbstractItemDelegate sizeHintChanged(int handle, int arg0) -> void */
void phpqt_qabstractitemdelegate_size_hint_changed(zval *p_handle, zval *p_arg0);

/*@reserved Widgets\QAbstractItemDelegate template QAbstractItemDelegate(QObjectPrivate &, QObject * parent) */
/*@override Widgets\QAbstractItemDelegate paint void paint(QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate sizeHint QSize sizeHint(const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate createEditor QWidget * createEditor(QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate destroyEditor void destroyEditor(QWidget * editor, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate setEditorData void setEditorData(QWidget * editor, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate setModelData void setModelData(QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate updateEditorGeometry void updateEditorGeometry(QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const */
/*@override Widgets\QAbstractItemDelegate editorEvent bool editorEvent(QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) */
/*@override Widgets\QAbstractItemDelegate helpEvent bool helpEvent(QHelpEvent * event, QAbstractItemView * view, const QStyleOptionViewItem & option, const QModelIndex & index) */
/*@override Widgets\QAbstractItemDelegate paintingRoles QList<int> paintingRoles() const */
/*@override Widgets\QAbstractItemDelegate event bool event(QEvent * event) */
/*@override Widgets\QAbstractItemDelegate eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Widgets\QAbstractItemDelegate timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QAbstractItemDelegate childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QAbstractItemDelegate customEvent void customEvent(QEvent * event) */
/*@override Widgets\QAbstractItemDelegate connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QAbstractItemDelegate disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
