/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qcoreevent.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtCore/qsize.h>
#include <QtGui/qevent.h>
#include <QtGui/qicon.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qpainter.h>
#include <QtWidgets/qabstractbutton.h>
#include <QtWidgets/qmenu.h>
#include <QtWidgets/qpushbutton.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qwidget.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQPushButton : public QPushButton {
public:
    PhpQtQPushButton(QWidget * p0) : QPushButton(p0) {}
    PhpQtQPushButton(const QString & p0, QWidget * p1) : QPushButton(p0, p1) {}
    PhpQtQPushButton(const QIcon & p0, const QString & p1, QWidget * p2) : QPushButton(p0, p1, p2) {}
    ~PhpQtQPushButton();
    QSize sizeHint() const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QPushButton::sizeHint())) override;
    QSize minimumSizeHint() const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QPushButton::minimumSizeHint())) override;
    bool event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QPushButton::event(std::declval<QEvent *>()))) override;
    void paintEvent(QPaintEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QPushButton::paintEvent(std::declval<QPaintEvent *>()))) override;
    void keyPressEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QPushButton::keyPressEvent(std::declval<QKeyEvent *>()))) override;
    void focusInEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QPushButton::focusInEvent(std::declval<QFocusEvent *>()))) override;
    void focusOutEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QPushButton::focusOutEvent(std::declval<QFocusEvent *>()))) override;
    void mouseMoveEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QPushButton::mouseMoveEvent(std::declval<QMouseEvent *>()))) override;
    void initStyleOption(QStyleOptionButton * p0) const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QPushButton::initStyleOption(std::declval<QStyleOptionButton *>()))) override;
    bool hitButton(const QPoint & p0) const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QPushButton::hitButton(std::declval<const QPoint &>()))) override;
    void checkStateSet() noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::checkStateSet())) override;
    void nextCheckState() noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::nextCheckState())) override;
    void keyReleaseEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::keyReleaseEvent(std::declval<QKeyEvent *>()))) override;
    void mousePressEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::mousePressEvent(std::declval<QMouseEvent *>()))) override;
    void mouseReleaseEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::mouseReleaseEvent(std::declval<QMouseEvent *>()))) override;
    void changeEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::changeEvent(std::declval<QEvent *>()))) override;
    void timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QAbstractButton::timerEvent(std::declval<QTimerEvent *>()))) override;
    int devType() const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::devType())) override;
    void setVisible(bool p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::setVisible(std::declval<bool>()))) override;
    int heightForWidth(int p0) const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::heightForWidth(std::declval<int>()))) override;
    bool hasHeightForWidth() const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::hasHeightForWidth())) override;
    QPaintEngine * paintEngine() const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::paintEngine())) override;
    void mouseDoubleClickEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::mouseDoubleClickEvent(std::declval<QMouseEvent *>()))) override;
    void wheelEvent(QWheelEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::wheelEvent(std::declval<QWheelEvent *>()))) override;
    void enterEvent(QEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::enterEvent(std::declval<QEnterEvent *>()))) override;
    void leaveEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::leaveEvent(std::declval<QEvent *>()))) override;
    void moveEvent(QMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::moveEvent(std::declval<QMoveEvent *>()))) override;
    void resizeEvent(QResizeEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::resizeEvent(std::declval<QResizeEvent *>()))) override;
    void closeEvent(QCloseEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::closeEvent(std::declval<QCloseEvent *>()))) override;
    void contextMenuEvent(QContextMenuEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::contextMenuEvent(std::declval<QContextMenuEvent *>()))) override;
    void tabletEvent(QTabletEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::tabletEvent(std::declval<QTabletEvent *>()))) override;
    void actionEvent(QActionEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::actionEvent(std::declval<QActionEvent *>()))) override;
    void dragEnterEvent(QDragEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::dragEnterEvent(std::declval<QDragEnterEvent *>()))) override;
    void dragMoveEvent(QDragMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::dragMoveEvent(std::declval<QDragMoveEvent *>()))) override;
    void dragLeaveEvent(QDragLeaveEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::dragLeaveEvent(std::declval<QDragLeaveEvent *>()))) override;
    void dropEvent(QDropEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::dropEvent(std::declval<QDropEvent *>()))) override;
    void showEvent(QShowEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::showEvent(std::declval<QShowEvent *>()))) override;
    void hideEvent(QHideEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::hideEvent(std::declval<QHideEvent *>()))) override;
    int metric(QPaintDevice::PaintDeviceMetric p0) const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::metric(std::declval<QPaintDevice::PaintDeviceMetric>()))) override;
    void initPainter(QPainter * p0) const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::initPainter(std::declval<QPainter *>()))) override;
    QPainter * sharedPainter() const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::sharedPainter())) override;
    void inputMethodEvent(QInputMethodEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::inputMethodEvent(std::declval<QInputMethodEvent *>()))) override;
    QVariant inputMethodQuery(Qt::InputMethodQuery p0) const noexcept(noexcept(std::declval<const PhpQtQPushButton &>().QWidget::inputMethodQuery(std::declval<Qt::InputMethodQuery>()))) override;
    bool focusNextPrevChild(bool p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QWidget::focusNextPrevChild(std::declval<bool>()))) override;
    bool eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QObject::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>()))) override;
    void childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QObject::childEvent(std::declval<QChildEvent *>()))) override;
    void customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QObject::customEvent(std::declval<QEvent *>()))) override;
    void connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QObject::connectNotify(std::declval<const QMetaMethod &>()))) override;
    void disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQPushButton &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>()))) override;
    bool phpqt_fwd_event(QEvent * p0) { return event(p0); }
    void phpqt_fwd_paintEvent(QPaintEvent * p0) { paintEvent(p0); }
    void phpqt_fwd_keyPressEvent(QKeyEvent * p0) { keyPressEvent(p0); }
    void phpqt_fwd_focusInEvent(QFocusEvent * p0) { focusInEvent(p0); }
    void phpqt_fwd_focusOutEvent(QFocusEvent * p0) { focusOutEvent(p0); }
    void phpqt_fwd_mouseMoveEvent(QMouseEvent * p0) { mouseMoveEvent(p0); }
    void phpqt_fwd_initStyleOption(QStyleOptionButton * p0) const { initStyleOption(p0); }
    bool phpqt_fwd_hitButton(const QPoint & p0) const { return hitButton(p0); }
    static const char *const kOverridable[];
};
