/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QGRAPHICSPROXYWIDGET_H
#define PHPQT_WIDGETS_QGRAPHICSPROXYWIDGET_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QGraphicsProxyWidget staticMetaObject() -> int */
zend_long phpqt_qgraphicsproxywidget_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QGraphicsProxyWidget tr(var s, var c = null, int n = -1) -> string */
void phpqt_qgraphicsproxywidget_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QGraphicsProxyWidget(QGraphicsItem * parent, Qt::WindowFlags wFlags) */
/*@zep Widgets\QGraphicsProxyWidget new(int parent = 0, var wFlags = null) -> int */
zend_long phpqt_qgraphicsproxywidget_new(zval *p_parent, zval *p_wFlags);

/*@ast void setWidget(QWidget * widget) */
/*@zep Widgets\QGraphicsProxyWidget setWidget(int handle, int widget) -> void */
void phpqt_qgraphicsproxywidget_set_widget(zval *p_handle, zval *p_widget);

/*@ast QWidget * widget() const */
/*@zep Widgets\QGraphicsProxyWidget widget(int handle) -> int */
zend_long phpqt_qgraphicsproxywidget_widget(zval *p_handle);

/*@ast QRectF subWidgetRect(const QWidget * widget) const */
/*@zep Widgets\QGraphicsProxyWidget subWidgetRect(int handle, int widget) -> array */
void phpqt_qgraphicsproxywidget_sub_widget_rect(zval *return_value, zval *p_handle, zval *p_widget);

/*@ast void setGeometry(const QRectF & rect) */
/*@zep Widgets\QGraphicsProxyWidget setGeometry(int handle, double rectX, double rectY, double rectWidth, double rectHeight) -> void */
void phpqt_qgraphicsproxywidget_set_geometry(zval *p_handle, zval *p_rectX, zval *p_rectY, zval *p_rectWidth, zval *p_rectHeight);

/*@ast void paint(QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) */
/*@zep Widgets\QGraphicsProxyWidget paint(int handle, int painter, int option, int widget) -> void */
void phpqt_qgraphicsproxywidget_paint(zval *p_handle, zval *p_painter, zval *p_option, zval *p_widget);

/*@ast int type() const */
/*@zep Widgets\QGraphicsProxyWidget type(int handle) -> int */
zend_long phpqt_qgraphicsproxywidget_type(zval *p_handle);

/*@ast QGraphicsProxyWidget * createProxyForChildWidget(QWidget * child) */
/*@zep Widgets\QGraphicsProxyWidget createProxyForChildWidget(int handle, int child) -> int */
zend_long phpqt_qgraphicsproxywidget_create_proxy_for_child_widget(zval *p_handle, zval *p_child);

/*@ast QVariant itemChange(QGraphicsItem::GraphicsItemChange change, const QVariant & value) */
/*@zep Widgets\QGraphicsProxyWidget itemChange(int handle, int change, var value) -> var */
void phpqt_qgraphicsproxywidget_item_change(zval *return_value, zval *p_handle, zval *p_change, zval *p_value);

/*@ast bool event(QEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget event(int handle, int event) -> bool */
zend_long phpqt_qgraphicsproxywidget_event(zval *p_handle, zval *p_event);

/*@ast bool eventFilter(QObject * object, QEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget eventFilter(int handle, int object, int event) -> bool */
zend_long phpqt_qgraphicsproxywidget_event_filter(zval *p_handle, zval *p_object, zval *p_event);

/*@ast void showEvent(QShowEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget showEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_show_event(zval *p_handle, zval *p_event);

/*@ast void hideEvent(QHideEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget hideEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_hide_event(zval *p_handle, zval *p_event);

/*@ast void contextMenuEvent(QGraphicsSceneContextMenuEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget contextMenuEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_context_menu_event(zval *p_handle, zval *p_event);

/*@ast void dragEnterEvent(QGraphicsSceneDragDropEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget dragEnterEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_drag_enter_event(zval *p_handle, zval *p_event);

/*@ast void dragLeaveEvent(QGraphicsSceneDragDropEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget dragLeaveEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_drag_leave_event(zval *p_handle, zval *p_event);

/*@ast void dragMoveEvent(QGraphicsSceneDragDropEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget dragMoveEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_drag_move_event(zval *p_handle, zval *p_event);

/*@ast void dropEvent(QGraphicsSceneDragDropEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget dropEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_drop_event(zval *p_handle, zval *p_event);

/*@ast void hoverEnterEvent(QGraphicsSceneHoverEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget hoverEnterEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_hover_enter_event(zval *p_handle, zval *p_event);

/*@ast void hoverLeaveEvent(QGraphicsSceneHoverEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget hoverLeaveEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_hover_leave_event(zval *p_handle, zval *p_event);

/*@ast void hoverMoveEvent(QGraphicsSceneHoverEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget hoverMoveEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_hover_move_event(zval *p_handle, zval *p_event);

/*@ast void grabMouseEvent(QEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget grabMouseEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_grab_mouse_event(zval *p_handle, zval *p_event);

/*@ast void ungrabMouseEvent(QEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget ungrabMouseEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_ungrab_mouse_event(zval *p_handle, zval *p_event);

/*@ast void mouseMoveEvent(QGraphicsSceneMouseEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget mouseMoveEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_mouse_move_event(zval *p_handle, zval *p_event);

/*@ast void mousePressEvent(QGraphicsSceneMouseEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget mousePressEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_mouse_press_event(zval *p_handle, zval *p_event);

/*@ast void mouseReleaseEvent(QGraphicsSceneMouseEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget mouseReleaseEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_mouse_release_event(zval *p_handle, zval *p_event);

/*@ast void mouseDoubleClickEvent(QGraphicsSceneMouseEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget mouseDoubleClickEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_mouse_double_click_event(zval *p_handle, zval *p_event);

/*@ast void wheelEvent(QGraphicsSceneWheelEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget wheelEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_wheel_event(zval *p_handle, zval *p_event);

/*@ast void keyPressEvent(QKeyEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget keyPressEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_key_press_event(zval *p_handle, zval *p_event);

/*@ast void keyReleaseEvent(QKeyEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget keyReleaseEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_key_release_event(zval *p_handle, zval *p_event);

/*@ast void focusInEvent(QFocusEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget focusInEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_focus_in_event(zval *p_handle, zval *p_event);

/*@ast void focusOutEvent(QFocusEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget focusOutEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_focus_out_event(zval *p_handle, zval *p_event);

/*@ast bool focusNextPrevChild(bool next) */
/*@zep Widgets\QGraphicsProxyWidget focusNextPrevChild(int handle, bool next) -> bool */
zend_long phpqt_qgraphicsproxywidget_focus_next_prev_child(zval *p_handle, zval *p_next);

/*@ast QVariant inputMethodQuery(Qt::InputMethodQuery query) const */
/*@zep Widgets\QGraphicsProxyWidget inputMethodQuery(int handle, int query) -> var */
void phpqt_qgraphicsproxywidget_input_method_query(zval *return_value, zval *p_handle, zval *p_query);

/*@ast void inputMethodEvent(QInputMethodEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget inputMethodEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_input_method_event(zval *p_handle, zval *p_event);

/*@ast QSizeF sizeHint(Qt::SizeHint which, const QSizeF & constraint) const */
/*@zep Widgets\QGraphicsProxyWidget sizeHint(int handle, int which, var constraintWidth = null, var constraintHeight = null) -> array */
void phpqt_qgraphicsproxywidget_size_hint(zval *return_value, zval *p_handle, zval *p_which, zval *p_constraintWidth, zval *p_constraintHeight);

/*@ast void resizeEvent(QGraphicsSceneResizeEvent * event) */
/*@zep Widgets\QGraphicsProxyWidget resizeEvent(int handle, int event) -> void */
void phpqt_qgraphicsproxywidget_resize_event(zval *p_handle, zval *p_event);

/*@ast QGraphicsProxyWidget * newProxyWidget(const QWidget *) */
/*@zep Widgets\QGraphicsProxyWidget newProxyWidget(int handle, int arg0) -> int */
zend_long phpqt_qgraphicsproxywidget_new_proxy_widget(zval *p_handle, zval *p_arg0);

/*@override Widgets\QGraphicsProxyWidget setGeometry void setGeometry(const QRectF & rect) */
/*@override Widgets\QGraphicsProxyWidget paint void paint(QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) */
/*@override Widgets\QGraphicsProxyWidget type int type() const */
/*@override Widgets\QGraphicsProxyWidget itemChange QVariant itemChange(QGraphicsItem::GraphicsItemChange change, const QVariant & value) */
/*@override Widgets\QGraphicsProxyWidget event bool event(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget eventFilter bool eventFilter(QObject * object, QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget showEvent void showEvent(QShowEvent * event) */
/*@override Widgets\QGraphicsProxyWidget hideEvent void hideEvent(QHideEvent * event) */
/*@override Widgets\QGraphicsProxyWidget contextMenuEvent void contextMenuEvent(QGraphicsSceneContextMenuEvent * event) */
/*@override Widgets\QGraphicsProxyWidget dragEnterEvent void dragEnterEvent(QGraphicsSceneDragDropEvent * event) */
/*@override Widgets\QGraphicsProxyWidget dragLeaveEvent void dragLeaveEvent(QGraphicsSceneDragDropEvent * event) */
/*@override Widgets\QGraphicsProxyWidget dragMoveEvent void dragMoveEvent(QGraphicsSceneDragDropEvent * event) */
/*@override Widgets\QGraphicsProxyWidget dropEvent void dropEvent(QGraphicsSceneDragDropEvent * event) */
/*@override Widgets\QGraphicsProxyWidget hoverEnterEvent void hoverEnterEvent(QGraphicsSceneHoverEvent * event) */
/*@override Widgets\QGraphicsProxyWidget hoverLeaveEvent void hoverLeaveEvent(QGraphicsSceneHoverEvent * event) */
/*@override Widgets\QGraphicsProxyWidget hoverMoveEvent void hoverMoveEvent(QGraphicsSceneHoverEvent * event) */
/*@override Widgets\QGraphicsProxyWidget grabMouseEvent void grabMouseEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget ungrabMouseEvent void ungrabMouseEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget mouseMoveEvent void mouseMoveEvent(QGraphicsSceneMouseEvent * event) */
/*@override Widgets\QGraphicsProxyWidget mousePressEvent void mousePressEvent(QGraphicsSceneMouseEvent * event) */
/*@override Widgets\QGraphicsProxyWidget mouseReleaseEvent void mouseReleaseEvent(QGraphicsSceneMouseEvent * event) */
/*@override Widgets\QGraphicsProxyWidget mouseDoubleClickEvent void mouseDoubleClickEvent(QGraphicsSceneMouseEvent * event) */
/*@override Widgets\QGraphicsProxyWidget wheelEvent void wheelEvent(QGraphicsSceneWheelEvent * event) */
/*@override Widgets\QGraphicsProxyWidget keyPressEvent void keyPressEvent(QKeyEvent * event) */
/*@override Widgets\QGraphicsProxyWidget keyReleaseEvent void keyReleaseEvent(QKeyEvent * event) */
/*@override Widgets\QGraphicsProxyWidget focusInEvent void focusInEvent(QFocusEvent * event) */
/*@override Widgets\QGraphicsProxyWidget focusOutEvent void focusOutEvent(QFocusEvent * event) */
/*@override Widgets\QGraphicsProxyWidget focusNextPrevChild bool focusNextPrevChild(bool next) */
/*@override Widgets\QGraphicsProxyWidget inputMethodQuery QVariant inputMethodQuery(Qt::InputMethodQuery query) const */
/*@override Widgets\QGraphicsProxyWidget inputMethodEvent void inputMethodEvent(QInputMethodEvent * event) */
/*@override Widgets\QGraphicsProxyWidget sizeHint QSizeF sizeHint(Qt::SizeHint which, const QSizeF & constraint) const */
/*@override Widgets\QGraphicsProxyWidget resizeEvent void resizeEvent(QGraphicsSceneResizeEvent * event) */
/*@reserved-override Widgets\QGraphicsProxyWidget raw-pointer void getContentsMargins(qreal * left, qreal * top, qreal * right, qreal * bottom) const */
/*@override Widgets\QGraphicsProxyWidget paintWindowFrame void paintWindowFrame(QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) */
/*@override Widgets\QGraphicsProxyWidget boundingRect QRectF boundingRect() const */
/*@override Widgets\QGraphicsProxyWidget shape QPainterPath shape() const */
/*@override Widgets\QGraphicsProxyWidget initStyleOption void initStyleOption(QStyleOption * option) const */
/*@override Widgets\QGraphicsProxyWidget updateGeometry void updateGeometry() */
/*@override Widgets\QGraphicsProxyWidget propertyChange QVariant propertyChange(const QString & propertyName, const QVariant & value) */
/*@override Widgets\QGraphicsProxyWidget sceneEvent bool sceneEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget windowFrameEvent bool windowFrameEvent(QEvent * e) */
/*@override Widgets\QGraphicsProxyWidget windowFrameSectionAt Qt::WindowFrameSection windowFrameSectionAt(const QPointF & pos) const */
/*@override Widgets\QGraphicsProxyWidget changeEvent void changeEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget closeEvent void closeEvent(QCloseEvent * event) */
/*@override Widgets\QGraphicsProxyWidget moveEvent void moveEvent(QGraphicsSceneMoveEvent * event) */
/*@override Widgets\QGraphicsProxyWidget polishEvent void polishEvent() */
/*@override Widgets\QGraphicsProxyWidget grabKeyboardEvent void grabKeyboardEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget ungrabKeyboardEvent void ungrabKeyboardEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget isEmpty bool isEmpty() const */
/*@override Widgets\QGraphicsProxyWidget timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QGraphicsProxyWidget childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QGraphicsProxyWidget customEvent void customEvent(QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QGraphicsProxyWidget disconnectNotify void disconnectNotify(const QMetaMethod & signal) */
/*@override Widgets\QGraphicsProxyWidget advance void advance(int phase) */
/*@override Widgets\QGraphicsProxyWidget contains bool contains(const QPointF & point) const */
/*@override Widgets\QGraphicsProxyWidget collidesWithItem bool collidesWithItem(const QGraphicsItem * other, Qt::ItemSelectionMode mode) const */
/*@override Widgets\QGraphicsProxyWidget collidesWithPath bool collidesWithPath(const QPainterPath & path, Qt::ItemSelectionMode mode) const */
/*@override Widgets\QGraphicsProxyWidget isObscuredBy bool isObscuredBy(const QGraphicsItem * item) const */
/*@override Widgets\QGraphicsProxyWidget opaqueArea QPainterPath opaqueArea() const */
/*@override Widgets\QGraphicsProxyWidget sceneEventFilter bool sceneEventFilter(QGraphicsItem * watched, QEvent * event) */
/*@override Widgets\QGraphicsProxyWidget supportsExtension bool supportsExtension(QGraphicsItem::Extension extension) const */
/*@override Widgets\QGraphicsProxyWidget setExtension void setExtension(QGraphicsItem::Extension extension, const QVariant & variant) */
/*@override Widgets\QGraphicsProxyWidget extension QVariant extension(const QVariant & variant) const */

#ifdef __cplusplus
}
#endif
#endif
