/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qcoreevent.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qsize.h>
#include <QtGui/qevent.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qpainter.h>
#include <QtWidgets/qframe.h>
#include <QtWidgets/qsplitter.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qwidget.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "widgets-qsplitter.h"
#include "widgets-qsplitter-shell.h"

extern "C" zend_long phpqt_qsplitter_static_meta_object(void)
{
    return phpqt::reg_copy(QSplitter::staticMetaObject, PHPQT_TAG_QMetaObject); /* native */
}

extern "C" void phpqt_qsplitter_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n)
{
    const char *a0 = phpqt::arg_cstr(p_s);
    const char *a1 = phpqt::arg_cstr(p_c);
    int a2 = static_cast<int>(phpqt::arg_long(p_n));
    phpqt::ret_qstring(return_value, QSplitter::tr(a0, a1, a2)); /* native */
}

extern "C" zend_long phpqt_qsplitter_new(zval *p_parent)
{
    QWidget *a0 = phpqt::as<QWidget>(p_parent, PHPQT_TAG_QWidget);
    auto *obj = new PhpQtQSplitter(a0); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QSplitter, true, true);
}

extern "C" zend_long phpqt_qsplitter_new_qt_orientation_q_widget(zval *p_arg0, zval *p_parent)
{
    Qt::Orientation a0 = static_cast<Qt::Orientation>(phpqt::arg_long(p_arg0));
    QWidget *a1 = phpqt::as<QWidget>(p_parent, PHPQT_TAG_QWidget);
    auto *obj = new PhpQtQSplitter(a0, a1); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QSplitter, true, true);
}

extern "C" void phpqt_qsplitter_add_widget(zval *p_handle, zval *p_widget)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::addWidget: handle is not a QSplitter"); return; }
    QWidget *a0 = phpqt::as<QWidget>(p_widget, PHPQT_TAG_QWidget);
    self->addWidget(a0); /* native */
}

extern "C" void phpqt_qsplitter_insert_widget(zval *p_handle, zval *p_index, zval *p_widget)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::insertWidget: handle is not a QSplitter"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    QWidget *a1 = phpqt::as<QWidget>(p_widget, PHPQT_TAG_QWidget);
    self->insertWidget(a0, a1); /* native */
}

extern "C" zend_long phpqt_qsplitter_replace_widget(zval *p_handle, zval *p_index, zval *p_widget)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::replaceWidget: handle is not a QSplitter"); return 0; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    QWidget *a1 = phpqt::as<QWidget>(p_widget, PHPQT_TAG_QWidget);
    return phpqt::reg_out(const_cast<QWidget *>(self->replaceWidget(a0, a1)), PHPQT_TAG_QWidget); /* native */
}

extern "C" void phpqt_qsplitter_set_orientation(zval *p_handle, zval *p_arg0)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setOrientation: handle is not a QSplitter"); return; }
    Qt::Orientation a0 = static_cast<Qt::Orientation>(phpqt::arg_long(p_arg0));
    self->setOrientation(a0); /* native */
}

extern "C" zend_long phpqt_qsplitter_orientation(zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::orientation: handle is not a QSplitter"); return 0; }
    return static_cast<zend_long>(self->orientation()); /* native */
}

extern "C" void phpqt_qsplitter_set_children_collapsible(zval *p_handle, zval *p_arg0)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setChildrenCollapsible: handle is not a QSplitter"); return; }
    bool a0 = phpqt::arg_bool(p_arg0);
    self->setChildrenCollapsible(a0); /* native */
}

extern "C" zend_long phpqt_qsplitter_children_collapsible(zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::childrenCollapsible: handle is not a QSplitter"); return 0; }
    return (self->childrenCollapsible()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qsplitter_set_collapsible(zval *p_handle, zval *p_index, zval *p_arg1)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setCollapsible: handle is not a QSplitter"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    bool a1 = phpqt::arg_bool(p_arg1);
    self->setCollapsible(a0, a1); /* native */
}

extern "C" zend_long phpqt_qsplitter_is_collapsible(zval *p_handle, zval *p_index)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::isCollapsible: handle is not a QSplitter"); return 0; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    return (self->isCollapsible(a0)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qsplitter_set_opaque_resize(zval *p_handle, zval *p_opaque)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setOpaqueResize: handle is not a QSplitter"); return; }
    bool a0 = phpqt::arg_bool(p_opaque);
    self->setOpaqueResize(a0); /* native */
}

extern "C" zend_long phpqt_qsplitter_opaque_resize(zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::opaqueResize: handle is not a QSplitter"); return 0; }
    return (self->opaqueResize()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qsplitter_refresh(zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::refresh: handle is not a QSplitter"); return; }
    self->refresh(); /* native */
}

extern "C" void phpqt_qsplitter_size_hint(zval *return_value, zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::sizeHint: handle is not a QSplitter"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->sizeHint()); /* native */
}

extern "C" void phpqt_qsplitter_minimum_size_hint(zval *return_value, zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::minimumSizeHint: handle is not a QSplitter"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->minimumSizeHint()); /* native */
}

extern "C" void phpqt_qsplitter_sizes(zval *return_value, zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::sizes: handle is not a QSplitter"); ZVAL_NULL(return_value); return; }
    phpqt::ret_seq(return_value, self->sizes(), [](zval *ez, const int &e) { ZVAL_LONG(ez, static_cast<zend_long>(e)); }); /* native */
}

extern "C" void phpqt_qsplitter_set_sizes(zval *p_handle, zval *p_list)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setSizes: handle is not a QSplitter"); return; }
    QList<int> a0 = phpqt::arg_seq<int>(p_list, [](zval *ev) -> int { return static_cast<int>(phpqt::arg_long(ev)); });
    self->setSizes(a0); /* native */
}

extern "C" void phpqt_qsplitter_save_state(zval *return_value, zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::saveState: handle is not a QSplitter"); ZVAL_NULL(return_value); return; }
    phpqt::ret_bytes(return_value, self->saveState()); /* native */
}

extern "C" zend_long phpqt_qsplitter_restore_state(zval *p_handle, zval *p_state)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::restoreState: handle is not a QSplitter"); return 0; }
    QByteArray a0 = phpqt::arg_bytes(p_state);
    return (self->restoreState(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qsplitter_handle_width(zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::handleWidth: handle is not a QSplitter"); return 0; }
    return static_cast<zend_long>(self->handleWidth()); /* native */
}

extern "C" void phpqt_qsplitter_set_handle_width(zval *p_handle, zval *p_arg0)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setHandleWidth: handle is not a QSplitter"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_arg0));
    self->setHandleWidth(a0); /* native */
}

extern "C" zend_long phpqt_qsplitter_index_of(zval *p_handle, zval *p_w)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::indexOf: handle is not a QSplitter"); return 0; }
    QWidget *a0 = phpqt::as<QWidget>(p_w, PHPQT_TAG_QWidget);
    return static_cast<zend_long>(self->indexOf(a0)); /* native */
}

extern "C" zend_long phpqt_qsplitter_widget(zval *p_handle, zval *p_index)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::widget: handle is not a QSplitter"); return 0; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    return phpqt::reg_out(const_cast<QWidget *>(self->widget(a0)), PHPQT_TAG_QWidget); /* native */
}

extern "C" zend_long phpqt_qsplitter_count(zval *p_handle)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::count: handle is not a QSplitter"); return 0; }
    return static_cast<zend_long>(self->count()); /* native */
}

extern "C" void phpqt_qsplitter_get_range(zval *return_value, zval *p_handle, zval *p_index, zval *p_arg1, zval *p_arg2)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::getRange: handle is not a QSplitter"); ZVAL_NULL(return_value); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    QList<int> a1_b = phpqt::arg_seq<int>(p_arg1, [](zval *ev) -> int { return static_cast<int>(phpqt::arg_long(ev)); });
    int *a1 = phpqt::is_null(p_arg1) ? nullptr : a1_b.data();
    QList<int> a2_b = phpqt::arg_seq<int>(p_arg2, [](zval *ev) -> int { return static_cast<int>(phpqt::arg_long(ev)); });
    int *a2 = phpqt::is_null(p_arg2) ? nullptr : a2_b.data();
    self->getRange(a0, a1, a2); /* native */
    array_init(return_value);
    { zval z; if (phpqt::is_null(p_arg1)) { ZVAL_NULL(&z); } else { phpqt::ret_seq(&z, a1_b, [](zval *ez, const int &e) { ZVAL_LONG(ez, static_cast<zend_long>(e)); }); } add_assoc_zval(return_value, "arg1", &z); }
    { zval z; if (phpqt::is_null(p_arg2)) { ZVAL_NULL(&z); } else { phpqt::ret_seq(&z, a2_b, [](zval *ez, const int &e) { ZVAL_LONG(ez, static_cast<zend_long>(e)); }); } add_assoc_zval(return_value, "arg2", &z); }
}

extern "C" zend_long phpqt_qsplitter_handle(zval *p_handle, zval *p_index)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::handle: handle is not a QSplitter"); return 0; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    return phpqt::reg_out(const_cast<QSplitterHandle *>(self->handle(a0)), PHPQT_TAG_QSplitterHandle); /* native */
}

extern "C" void phpqt_qsplitter_set_stretch_factor(zval *p_handle, zval *p_index, zval *p_stretch)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setStretchFactor: handle is not a QSplitter"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_index));
    int a1 = static_cast<int>(phpqt::arg_long(p_stretch));
    self->setStretchFactor(a0, a1); /* native */
}

extern "C" void phpqt_qsplitter_splitter_moved(zval *p_handle, zval *p_pos, zval *p_index)
{
    QSplitter *self = phpqt::as<QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::splitterMoved: handle is not a QSplitter"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_pos));
    int a1 = static_cast<int>(phpqt::arg_long(p_index));
    self->splitterMoved(a0, a1); /* native */
}

extern "C" zend_long phpqt_qsplitter_create_handle(zval *p_handle)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::createHandle: handle is not a QSplitter constructed through the extension"); return 0; }
    return phpqt::reg_out(const_cast<QSplitterHandle *>(self->phpqt_fwd_createHandle()), PHPQT_TAG_QSplitterHandle); /* native */
}

extern "C" void phpqt_qsplitter_child_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::childEvent: handle is not a QSplitter constructed through the extension"); return; }
    QChildEvent *a0 = phpqt::as<QChildEvent>(p_arg0, PHPQT_TAG_QChildEvent);
    self->phpqt_fwd_childEvent(a0); /* native */
}

extern "C" zend_long phpqt_qsplitter_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::event: handle is not a QSplitter constructed through the extension"); return 0; }
    QEvent *a0 = phpqt::as<QEvent>(p_arg0, PHPQT_TAG_QEvent);
    return (self->phpqt_fwd_event(a0)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qsplitter_resize_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::resizeEvent: handle is not a QSplitter constructed through the extension"); return; }
    QResizeEvent *a0 = phpqt::as<QResizeEvent>(p_arg0, PHPQT_TAG_QResizeEvent);
    self->phpqt_fwd_resizeEvent(a0); /* native */
}

extern "C" void phpqt_qsplitter_change_event(zval *p_handle, zval *p_arg0)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::changeEvent: handle is not a QSplitter constructed through the extension"); return; }
    QEvent *a0 = phpqt::as<QEvent>(p_arg0, PHPQT_TAG_QEvent);
    self->phpqt_fwd_changeEvent(a0); /* native */
}

extern "C" void phpqt_qsplitter_move_splitter(zval *p_handle, zval *p_pos, zval *p_index)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::moveSplitter: handle is not a QSplitter constructed through the extension"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_pos));
    int a1 = static_cast<int>(phpqt::arg_long(p_index));
    self->phpqt_fwd_moveSplitter(a0, a1); /* native */
}

extern "C" void phpqt_qsplitter_set_rubber_band(zval *p_handle, zval *p_position)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::setRubberBand: handle is not a QSplitter constructed through the extension"); return; }
    int a0 = static_cast<int>(phpqt::arg_long(p_position));
    self->phpqt_fwd_setRubberBand(a0); /* native */
}

extern "C" zend_long phpqt_qsplitter_closest_legal_position(zval *p_handle, zval *p_arg0, zval *p_arg1)
{
    PhpQtQSplitter *self = phpqt::as_shell<PhpQtQSplitter, QSplitter>(p_handle, PHPQT_TAG_QSplitter);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QSplitter::closestLegalPosition: handle is not a QSplitter constructed through the extension"); return 0; }
    int a0 = static_cast<int>(phpqt::arg_long(p_arg0));
    int a1 = static_cast<int>(phpqt::arg_long(p_arg1));
    return static_cast<zend_long>(self->phpqt_fwd_closestLegalPosition(a0, a1)); /* native */
}

