/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qcoreevent.h>
#include <QtCore/qflags.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
#include <QtGui/qcolor.h>
#include <QtGui/qevent.h>
#include <QtGui/qfont.h>
#include <QtGui/qpainter.h>
#include <QtGui/qpainterpath.h>
#include <QtGui/qtextcursor.h>
#include <QtGui/qtextdocument.h>
#include <QtWidgets/qgraphicsitem.h>
#include <QtWidgets/qgraphicssceneevent.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qwidget.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "widgets-qgraphicstextitem.h"
#include "widgets-qgraphicstextitem-shell.h"

extern "C" zend_long phpqt_qgraphicstextitem_static_meta_object(void)
{
    return phpqt::reg_copy(QGraphicsTextItem::staticMetaObject, PHPQT_TAG_QMetaObject); /* native */
}

extern "C" void phpqt_qgraphicstextitem_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n)
{
    const char *a0 = phpqt::arg_cstr(p_s);
    const char *a1 = phpqt::arg_cstr(p_c);
    int a2 = static_cast<int>(phpqt::arg_long(p_n));
    phpqt::ret_qstring(return_value, QGraphicsTextItem::tr(a0, a1, a2)); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_new(zval *p_parent)
{
    QGraphicsItem *a0 = phpqt::as<QGraphicsItem>(p_parent, PHPQT_TAG_QGraphicsItem);
    auto *obj = new PhpQtQGraphicsTextItem(a0); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QGraphicsTextItem, true, true);
}

extern "C" zend_long phpqt_qgraphicstextitem_new_q_string_q_graphics_item(zval *p_text, zval *p_parent)
{
    QString a0 = phpqt::arg_qstring(p_text);
    QGraphicsItem *a1 = phpqt::as<QGraphicsItem>(p_parent, PHPQT_TAG_QGraphicsItem);
    auto *obj = new PhpQtQGraphicsTextItem(a0, a1); /* native */
    return phpqt::reg(obj, PHPQT_TAG_QGraphicsTextItem, true, true);
}

extern "C" void phpqt_qgraphicstextitem_to_html(zval *return_value, zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::toHtml: handle is not a QGraphicsTextItem"); ZVAL_NULL(return_value); return; }
    phpqt::ret_qstring(return_value, self->toHtml()); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_html(zval *p_handle, zval *p_html)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setHtml: handle is not a QGraphicsTextItem"); return; }
    QString a0 = phpqt::arg_qstring(p_html);
    self->setHtml(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_to_plain_text(zval *return_value, zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::toPlainText: handle is not a QGraphicsTextItem"); ZVAL_NULL(return_value); return; }
    phpqt::ret_qstring(return_value, self->toPlainText()); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_plain_text(zval *p_handle, zval *p_text)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setPlainText: handle is not a QGraphicsTextItem"); return; }
    QString a0 = phpqt::arg_qstring(p_text);
    self->setPlainText(a0); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_font(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::font: handle is not a QGraphicsTextItem"); return 0; }
    return phpqt::reg(new QFont(self->font()), PHPQT_TAG_QFont, true); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_font(zval *p_handle, zval *p_font)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setFont: handle is not a QGraphicsTextItem"); return; }
    QFont *a0_p = phpqt::is_null(p_font) ? nullptr : phpqt::as<QFont>(p_font, PHPQT_TAG_QFont);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setFont: font is not a QFont handle"); return; }
    self->setFont(*a0_p); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_default_text_color(zval *p_handle, zval *p_c)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setDefaultTextColor: handle is not a QGraphicsTextItem"); return; }
    QColor *a0_p = phpqt::is_null(p_c) ? nullptr : phpqt::as<QColor>(p_c, PHPQT_TAG_QColor);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setDefaultTextColor: c is not a QColor handle"); return; }
    self->setDefaultTextColor(*a0_p); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_default_text_color(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::defaultTextColor: handle is not a QGraphicsTextItem"); return 0; }
    return phpqt::reg(new QColor(self->defaultTextColor()), PHPQT_TAG_QColor, true); /* native */
}

extern "C" void phpqt_qgraphicstextitem_bounding_rect(zval *return_value, zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::boundingRect: handle is not a QGraphicsTextItem"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->boundingRect()); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_shape(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::shape: handle is not a QGraphicsTextItem"); return 0; }
    return phpqt::reg(new QPainterPath(self->shape()), PHPQT_TAG_QPainterPath, true); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_contains(zval *p_handle, zval *p_pointX, zval *p_pointY)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::contains: handle is not a QGraphicsTextItem"); return 0; }
    QPointF a0 = QPointF(phpqt::arg_double(p_pointX), phpqt::arg_double(p_pointY));
    return (self->contains(a0)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qgraphicstextitem_paint(zval *p_handle, zval *p_painter, zval *p_option, zval *p_widget)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::paint: handle is not a QGraphicsTextItem"); return; }
    QPainter *a0 = phpqt::as<QPainter>(p_painter, PHPQT_TAG_QPainter);
    const QStyleOptionGraphicsItem *a1 = phpqt::as<QStyleOptionGraphicsItem>(p_option, PHPQT_TAG_QStyleOptionGraphicsItem);
    QWidget *a2 = phpqt::as<QWidget>(p_widget, PHPQT_TAG_QWidget);
    self->paint(a0, a1, a2); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_is_obscured_by(zval *p_handle, zval *p_item)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::isObscuredBy: handle is not a QGraphicsTextItem"); return 0; }
    const QGraphicsItem *a0 = phpqt::as<QGraphicsItem>(p_item, PHPQT_TAG_QGraphicsItem);
    return (self->isObscuredBy(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_opaque_area(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::opaqueArea: handle is not a QGraphicsTextItem"); return 0; }
    return phpqt::reg(new QPainterPath(self->opaqueArea()), PHPQT_TAG_QPainterPath, true); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_type(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::type: handle is not a QGraphicsTextItem"); return 0; }
    return static_cast<zend_long>(self->type()); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_text_width(zval *p_handle, zval *p_width)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setTextWidth: handle is not a QGraphicsTextItem"); return; }
    double a0 = static_cast<double>(phpqt::arg_double(p_width));
    self->setTextWidth(a0); /* native */
}

extern "C" double phpqt_qgraphicstextitem_text_width(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::textWidth: handle is not a QGraphicsTextItem"); return 0.0; }
    return static_cast<double>(self->textWidth()); /* native */
}

extern "C" void phpqt_qgraphicstextitem_adjust_size(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::adjustSize: handle is not a QGraphicsTextItem"); return; }
    self->adjustSize(); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_document(zval *p_handle, zval *p_document)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setDocument: handle is not a QGraphicsTextItem"); return; }
    QTextDocument *a0 = phpqt::as<QTextDocument>(p_document, PHPQT_TAG_QTextDocument);
    self->setDocument(a0); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_document(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::document: handle is not a QGraphicsTextItem"); return 0; }
    return phpqt::reg_out(const_cast<QTextDocument *>(self->document()), PHPQT_TAG_QTextDocument); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_text_interaction_flags(zval *p_handle, zval *p_flags)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setTextInteractionFlags: handle is not a QGraphicsTextItem"); return; }
    QFlags<Qt::TextInteractionFlag> a0 = QFlags<Qt::TextInteractionFlag>(QFlag(static_cast<int>(phpqt::arg_long(p_flags))));
    self->setTextInteractionFlags(a0); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_text_interaction_flags(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::textInteractionFlags: handle is not a QGraphicsTextItem"); return 0; }
    return static_cast<zend_long>((self->textInteractionFlags()).toInt()); /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_tab_changes_focus(zval *p_handle, zval *p_b)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setTabChangesFocus: handle is not a QGraphicsTextItem"); return; }
    bool a0 = phpqt::arg_bool(p_b);
    self->setTabChangesFocus(a0); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_tab_changes_focus(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::tabChangesFocus: handle is not a QGraphicsTextItem"); return 0; }
    return (self->tabChangesFocus()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_open_external_links(zval *p_handle, zval *p_open)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setOpenExternalLinks: handle is not a QGraphicsTextItem"); return; }
    bool a0 = phpqt::arg_bool(p_open);
    self->setOpenExternalLinks(a0); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_open_external_links(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::openExternalLinks: handle is not a QGraphicsTextItem"); return 0; }
    return (self->openExternalLinks()) ? 1 : 0; /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_text_cursor(zval *p_handle, zval *p_cursor)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setTextCursor: handle is not a QGraphicsTextItem"); return; }
    QTextCursor *a0_p = phpqt::is_null(p_cursor) ? nullptr : phpqt::as<QTextCursor>(p_cursor, PHPQT_TAG_QTextCursor);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setTextCursor: cursor is not a QTextCursor handle"); return; }
    self->setTextCursor(*a0_p); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_text_cursor(zval *p_handle)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::textCursor: handle is not a QGraphicsTextItem"); return 0; }
    return phpqt::reg(new QTextCursor(self->textCursor()), PHPQT_TAG_QTextCursor, true); /* native */
}

extern "C" void phpqt_qgraphicstextitem_link_activated(zval *p_handle, zval *p_arg0)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::linkActivated: handle is not a QGraphicsTextItem"); return; }
    QString a0 = phpqt::arg_qstring(p_arg0);
    self->linkActivated(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_link_hovered(zval *p_handle, zval *p_arg0)
{
    QGraphicsTextItem *self = phpqt::as<QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::linkHovered: handle is not a QGraphicsTextItem"); return; }
    QString a0 = phpqt::arg_qstring(p_arg0);
    self->linkHovered(a0); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_scene_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::sceneEvent: handle is not a QGraphicsTextItem constructed through the extension"); return 0; }
    QEvent *a0 = phpqt::as<QEvent>(p_event, PHPQT_TAG_QEvent);
    return (self->phpqt_fwd_sceneEvent(a0)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qgraphicstextitem_mouse_press_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::mousePressEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneMouseEvent *a0 = phpqt::as<QGraphicsSceneMouseEvent>(p_event, PHPQT_TAG_QGraphicsSceneMouseEvent);
    self->phpqt_fwd_mousePressEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_mouse_move_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::mouseMoveEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneMouseEvent *a0 = phpqt::as<QGraphicsSceneMouseEvent>(p_event, PHPQT_TAG_QGraphicsSceneMouseEvent);
    self->phpqt_fwd_mouseMoveEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_mouse_release_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::mouseReleaseEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneMouseEvent *a0 = phpqt::as<QGraphicsSceneMouseEvent>(p_event, PHPQT_TAG_QGraphicsSceneMouseEvent);
    self->phpqt_fwd_mouseReleaseEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_mouse_double_click_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::mouseDoubleClickEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneMouseEvent *a0 = phpqt::as<QGraphicsSceneMouseEvent>(p_event, PHPQT_TAG_QGraphicsSceneMouseEvent);
    self->phpqt_fwd_mouseDoubleClickEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_context_menu_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::contextMenuEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneContextMenuEvent *a0 = phpqt::as<QGraphicsSceneContextMenuEvent>(p_event, PHPQT_TAG_QGraphicsSceneContextMenuEvent);
    self->phpqt_fwd_contextMenuEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_key_press_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::keyPressEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QKeyEvent *a0 = phpqt::as<QKeyEvent>(p_event, PHPQT_TAG_QKeyEvent);
    self->phpqt_fwd_keyPressEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_key_release_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::keyReleaseEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QKeyEvent *a0 = phpqt::as<QKeyEvent>(p_event, PHPQT_TAG_QKeyEvent);
    self->phpqt_fwd_keyReleaseEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_focus_in_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::focusInEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QFocusEvent *a0 = phpqt::as<QFocusEvent>(p_event, PHPQT_TAG_QFocusEvent);
    self->phpqt_fwd_focusInEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_focus_out_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::focusOutEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QFocusEvent *a0 = phpqt::as<QFocusEvent>(p_event, PHPQT_TAG_QFocusEvent);
    self->phpqt_fwd_focusOutEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_drag_enter_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::dragEnterEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneDragDropEvent *a0 = phpqt::as<QGraphicsSceneDragDropEvent>(p_event, PHPQT_TAG_QGraphicsSceneDragDropEvent);
    self->phpqt_fwd_dragEnterEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_drag_leave_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::dragLeaveEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneDragDropEvent *a0 = phpqt::as<QGraphicsSceneDragDropEvent>(p_event, PHPQT_TAG_QGraphicsSceneDragDropEvent);
    self->phpqt_fwd_dragLeaveEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_drag_move_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::dragMoveEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneDragDropEvent *a0 = phpqt::as<QGraphicsSceneDragDropEvent>(p_event, PHPQT_TAG_QGraphicsSceneDragDropEvent);
    self->phpqt_fwd_dragMoveEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_drop_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::dropEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneDragDropEvent *a0 = phpqt::as<QGraphicsSceneDragDropEvent>(p_event, PHPQT_TAG_QGraphicsSceneDragDropEvent);
    self->phpqt_fwd_dropEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_input_method_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::inputMethodEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QInputMethodEvent *a0 = phpqt::as<QInputMethodEvent>(p_event, PHPQT_TAG_QInputMethodEvent);
    self->phpqt_fwd_inputMethodEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_hover_enter_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::hoverEnterEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneHoverEvent *a0 = phpqt::as<QGraphicsSceneHoverEvent>(p_event, PHPQT_TAG_QGraphicsSceneHoverEvent);
    self->phpqt_fwd_hoverEnterEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_hover_move_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::hoverMoveEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneHoverEvent *a0 = phpqt::as<QGraphicsSceneHoverEvent>(p_event, PHPQT_TAG_QGraphicsSceneHoverEvent);
    self->phpqt_fwd_hoverMoveEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_hover_leave_event(zval *p_handle, zval *p_event)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::hoverLeaveEvent: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    QGraphicsSceneHoverEvent *a0 = phpqt::as<QGraphicsSceneHoverEvent>(p_event, PHPQT_TAG_QGraphicsSceneHoverEvent);
    self->phpqt_fwd_hoverLeaveEvent(a0); /* native */
}

extern "C" void phpqt_qgraphicstextitem_input_method_query(zval *return_value, zval *p_handle, zval *p_query)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::inputMethodQuery: handle is not a QGraphicsTextItem constructed through the extension"); ZVAL_NULL(return_value); return; }
    Qt::InputMethodQuery a0 = static_cast<Qt::InputMethodQuery>(phpqt::arg_long(p_query));
    phpqt::ret_variant(return_value, self->phpqt_fwd_inputMethodQuery(a0)); /* native */
}

extern "C" zend_long phpqt_qgraphicstextitem_supports_extension(zval *p_handle, zval *p_extension)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::supportsExtension: handle is not a QGraphicsTextItem constructed through the extension"); return 0; }
    PhpQtQGraphicsTextItem::phpqt_QGraphicsItem_Extension a0 = static_cast<PhpQtQGraphicsTextItem::phpqt_QGraphicsItem_Extension>(phpqt::arg_long(p_extension));
    return (self->phpqt_fwd_supportsExtension(a0)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qgraphicstextitem_set_extension(zval *p_handle, zval *p_extension, zval *p_variant)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::setExtension: handle is not a QGraphicsTextItem constructed through the extension"); return; }
    PhpQtQGraphicsTextItem::phpqt_QGraphicsItem_Extension a0 = static_cast<PhpQtQGraphicsTextItem::phpqt_QGraphicsItem_Extension>(phpqt::arg_long(p_extension));
    QVariant a1 = phpqt::arg_variant(p_variant);
    self->phpqt_fwd_setExtension(a0, a1); /* native */
}

extern "C" void phpqt_qgraphicstextitem_extension(zval *return_value, zval *p_handle, zval *p_variant)
{
    PhpQtQGraphicsTextItem *self = phpqt::as_shell<PhpQtQGraphicsTextItem, QGraphicsTextItem>(p_handle, PHPQT_TAG_QGraphicsTextItem);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QGraphicsTextItem::extension: handle is not a QGraphicsTextItem constructed through the extension"); ZVAL_NULL(return_value); return; }
    QVariant a0 = phpqt::arg_variant(p_variant);
    phpqt::ret_variant(return_value, self->phpqt_fwd_extension(a0)); /* native */
}

