/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QAPPLICATION_H
#define PHPQT_WIDGETS_QAPPLICATION_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QApplication staticMetaObject() -> int */
zend_long phpqt_qapplication_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QApplication tr(var s, var c = null, int n = -1) -> string */
void phpqt_qapplication_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QApplication(int & argc, char * * argv, int) */
/*@zep Widgets\QApplication new(array argv, var arg0 = null) -> int */
zend_long phpqt_qapplication_new(zval *p_argv, zval *p_arg0);

/*@ast QStyle * style() */
/*@zep Widgets\QApplication style() -> int */
zend_long phpqt_qapplication_style(void);

/*@ast void setStyle(QStyle *) */
/*@zep Widgets\QApplication setStyle(int arg0) -> void */
void phpqt_qapplication_set_style(zval *p_arg0);

/*@ast QStyle * setStyle(const QString &) */
/*@zep Widgets\QApplication setStyleQString(string arg0) -> int */
zend_long phpqt_qapplication_set_style_q_string(zval *p_arg0);

/*@ast QPalette palette() */
/*@zep Widgets\QApplication palette() -> int */
zend_long phpqt_qapplication_palette(void);

/*@ast QPalette palette(const QWidget *) */
/*@zep Widgets\QApplication paletteQWidget(int arg0) -> int */
zend_long phpqt_qapplication_palette_q_widget(zval *p_arg0);

/*@ast QPalette palette(const char * className) */
/*@zep Widgets\QApplication paletteChar(var className) -> int */
zend_long phpqt_qapplication_palette_char(zval *p_className);

/*@ast void setPalette(const QPalette &, const char * className) */
/*@zep Widgets\QApplication setPalette(int arg0, var className = null) -> void */
void phpqt_qapplication_set_palette(zval *p_arg0, zval *p_className);

/*@ast QFont font() */
/*@zep Widgets\QApplication font() -> int */
zend_long phpqt_qapplication_font(void);

/*@ast QFont font(const QWidget *) */
/*@zep Widgets\QApplication fontQWidget(int arg0) -> int */
zend_long phpqt_qapplication_font_q_widget(zval *p_arg0);

/*@ast QFont font(const char * className) */
/*@zep Widgets\QApplication fontChar(var className) -> int */
zend_long phpqt_qapplication_font_char(zval *p_className);

/*@ast void setFont(const QFont &, const char * className) */
/*@zep Widgets\QApplication setFont(int arg0, var className = null) -> void */
void phpqt_qapplication_set_font(zval *p_arg0, zval *p_className);

/*@ast QWidgetList allWidgets() */
/*@zep Widgets\QApplication allWidgets() -> array */
void phpqt_qapplication_all_widgets(zval *return_value);

/*@ast QWidgetList topLevelWidgets() */
/*@zep Widgets\QApplication topLevelWidgets() -> array */
void phpqt_qapplication_top_level_widgets(zval *return_value);

/*@ast QWidget * activePopupWidget() */
/*@zep Widgets\QApplication activePopupWidget() -> int */
zend_long phpqt_qapplication_active_popup_widget(void);

/*@ast QWidget * activeModalWidget() */
/*@zep Widgets\QApplication activeModalWidget() -> int */
zend_long phpqt_qapplication_active_modal_widget(void);

/*@ast QWidget * focusWidget() */
/*@zep Widgets\QApplication focusWidget() -> int */
zend_long phpqt_qapplication_focus_widget(void);

/*@ast QWidget * activeWindow() */
/*@zep Widgets\QApplication activeWindow() -> int */
zend_long phpqt_qapplication_active_window(void);

/*@ast QWidget * widgetAt(const QPoint & p) */
/*@zep Widgets\QApplication widgetAt(int pX, int pY) -> int */
zend_long phpqt_qapplication_widget_at(zval *p_pX, zval *p_pY);

/*@ast QWidget * widgetAt(int x, int y) */
/*@zep Widgets\QApplication widgetAtIntInt(int x, int y) -> int */
zend_long phpqt_qapplication_widget_at_int_int(zval *p_x, zval *p_y);

/*@ast QWidget * topLevelAt(const QPoint & p) */
/*@zep Widgets\QApplication topLevelAt(int pX, int pY) -> int */
zend_long phpqt_qapplication_top_level_at(zval *p_pX, zval *p_pY);

/*@ast QWidget * topLevelAt(int x, int y) */
/*@zep Widgets\QApplication topLevelAtIntInt(int x, int y) -> int */
zend_long phpqt_qapplication_top_level_at_int_int(zval *p_x, zval *p_y);

/*@ast void beep() */
/*@zep Widgets\QApplication beep() -> void */
void phpqt_qapplication_beep(void);

/*@ast void alert(QWidget * widget, int duration) */
/*@zep Widgets\QApplication alert(int widget, int duration = 0) -> void */
void phpqt_qapplication_alert(zval *p_widget, zval *p_duration);

/*@ast void setCursorFlashTime(int) */
/*@zep Widgets\QApplication setCursorFlashTime(int arg0) -> void */
void phpqt_qapplication_set_cursor_flash_time(zval *p_arg0);

/*@ast int cursorFlashTime() */
/*@zep Widgets\QApplication cursorFlashTime() -> int */
zend_long phpqt_qapplication_cursor_flash_time(void);

/*@ast void setDoubleClickInterval(int) */
/*@zep Widgets\QApplication setDoubleClickInterval(int arg0) -> void */
void phpqt_qapplication_set_double_click_interval(zval *p_arg0);

/*@ast int doubleClickInterval() */
/*@zep Widgets\QApplication doubleClickInterval() -> int */
zend_long phpqt_qapplication_double_click_interval(void);

/*@ast void setKeyboardInputInterval(int) */
/*@zep Widgets\QApplication setKeyboardInputInterval(int arg0) -> void */
void phpqt_qapplication_set_keyboard_input_interval(zval *p_arg0);

/*@ast int keyboardInputInterval() */
/*@zep Widgets\QApplication keyboardInputInterval() -> int */
zend_long phpqt_qapplication_keyboard_input_interval(void);

/*@ast void setWheelScrollLines(int) */
/*@zep Widgets\QApplication setWheelScrollLines(int arg0) -> void */
void phpqt_qapplication_set_wheel_scroll_lines(zval *p_arg0);

/*@ast int wheelScrollLines() */
/*@zep Widgets\QApplication wheelScrollLines() -> int */
zend_long phpqt_qapplication_wheel_scroll_lines(void);

/*@ast void setStartDragTime(int ms) */
/*@zep Widgets\QApplication setStartDragTime(int ms) -> void */
void phpqt_qapplication_set_start_drag_time(zval *p_ms);

/*@ast int startDragTime() */
/*@zep Widgets\QApplication startDragTime() -> int */
zend_long phpqt_qapplication_start_drag_time(void);

/*@ast void setStartDragDistance(int l) */
/*@zep Widgets\QApplication setStartDragDistance(int l) -> void */
void phpqt_qapplication_set_start_drag_distance(zval *p_l);

/*@ast int startDragDistance() */
/*@zep Widgets\QApplication startDragDistance() -> int */
zend_long phpqt_qapplication_start_drag_distance(void);

/*@ast bool isEffectEnabled(Qt::UIEffect) */
/*@zep Widgets\QApplication isEffectEnabled(int arg0) -> bool */
zend_long phpqt_qapplication_is_effect_enabled(zval *p_arg0);

/*@ast void setEffectEnabled(Qt::UIEffect, bool enable) */
/*@zep Widgets\QApplication setEffectEnabled(int arg0, bool enable = true) -> void */
void phpqt_qapplication_set_effect_enabled(zval *p_arg0, zval *p_enable);

/*@ast int exec() */
/*@zep Widgets\QApplication exec() -> int */
zend_long phpqt_qapplication_exec(void);

/*@ast bool notify(QObject *, QEvent *) */
/*@zep Widgets\QApplication notify(int handle, int arg0, int arg1) -> bool */
zend_long phpqt_qapplication_notify(zval *p_handle, zval *p_arg0, zval *p_arg1);

/*@ast void focusChanged(QWidget * old, QWidget * now) */
/*@zep Widgets\QApplication focusChanged(int handle, int old, int now) -> void */
void phpqt_qapplication_focus_changed(zval *p_handle, zval *p_old, zval *p_now);

/*@ast QString styleSheet() const */
/*@zep Widgets\QApplication styleSheet(int handle) -> string */
void phpqt_qapplication_style_sheet(zval *return_value, zval *p_handle);

/*@ast bool autoSipEnabled() const */
/*@zep Widgets\QApplication autoSipEnabled(int handle) -> bool */
zend_long phpqt_qapplication_auto_sip_enabled(zval *p_handle);

/*@ast void setStyleSheet(const QString & sheet) */
/*@zep Widgets\QApplication setStyleSheet(int handle, string sheet) -> void */
void phpqt_qapplication_set_style_sheet(zval *p_handle, zval *p_sheet);

/*@ast void setAutoSipEnabled(const bool enabled) */
/*@zep Widgets\QApplication setAutoSipEnabled(int handle, bool enabled) -> void */
void phpqt_qapplication_set_auto_sip_enabled(zval *p_handle, zval *p_enabled);

/*@ast void closeAllWindows() */
/*@zep Widgets\QApplication closeAllWindows() -> void */
void phpqt_qapplication_close_all_windows(void);

/*@ast void aboutQt() */
/*@zep Widgets\QApplication aboutQt() -> void */
void phpqt_qapplication_about_qt(void);

/*@ast bool event(QEvent *) */
/*@zep Widgets\QApplication event(int handle, int arg0) -> bool */
zend_long phpqt_qapplication_event(zval *p_handle, zval *p_arg0);

/*@reserved Widgets\QApplication deprecated QFontMetrics fontMetrics() */
/*@reserved Widgets\QApplication deprecated void setActiveWindow(QWidget * act) */
/*@reserved Widgets\QApplication raw-pointer void * resolveInterface(const char * name, int revision) const */
/*@reserved Widgets\QApplication template bool compressEvent(QEvent *, QObject * receiver, QPostEventList *) */
/*@override Widgets\QApplication notify bool notify(QObject *, QEvent *) */
/*@override Widgets\QApplication event bool event(QEvent *) */
/*@reserved-override Widgets\QApplication template bool compressEvent(QEvent *, QObject * receiver, QPostEventList *) */
/*@override Widgets\QApplication eventFilter bool eventFilter(QObject * watched, QEvent * event) */
/*@override Widgets\QApplication timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QApplication childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QApplication customEvent void customEvent(QEvent * event) */
/*@override Widgets\QApplication connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QApplication disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
