/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#pragma once
#include <QtCore/qcoreevent.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtCore/qsize.h>
#include <QtGui/qevent.h>
#include <QtGui/qpaintdevice.h>
#include <QtGui/qpaintengine.h>
#include <QtGui/qpainter.h>
#include <QtWidgets/qabstractbutton.h>
#include <QtWidgets/qcheckbox.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qwidget.h>
#include "phpqt-support.h"
#include "phpqt-types.h"

class PhpQtQCheckBox : public QCheckBox {
public:
    PhpQtQCheckBox(QWidget * p0) : QCheckBox(p0) {}
    PhpQtQCheckBox(const QString & p0, QWidget * p1) : QCheckBox(p0, p1) {}
    ~PhpQtQCheckBox();
    QSize sizeHint() const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QCheckBox::sizeHint())) override;
    QSize minimumSizeHint() const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QCheckBox::minimumSizeHint())) override;
    bool event(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QCheckBox::event(std::declval<QEvent *>()))) override;
    bool hitButton(const QPoint & p0) const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QCheckBox::hitButton(std::declval<const QPoint &>()))) override;
    void checkStateSet() noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QCheckBox::checkStateSet())) override;
    void nextCheckState() noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QCheckBox::nextCheckState())) override;
    void paintEvent(QPaintEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QCheckBox::paintEvent(std::declval<QPaintEvent *>()))) override;
    void mouseMoveEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QCheckBox::mouseMoveEvent(std::declval<QMouseEvent *>()))) override;
    void initStyleOption(QStyleOptionButton * p0) const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QCheckBox::initStyleOption(std::declval<QStyleOptionButton *>()))) override;
    void keyPressEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::keyPressEvent(std::declval<QKeyEvent *>()))) override;
    void keyReleaseEvent(QKeyEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::keyReleaseEvent(std::declval<QKeyEvent *>()))) override;
    void mousePressEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::mousePressEvent(std::declval<QMouseEvent *>()))) override;
    void mouseReleaseEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::mouseReleaseEvent(std::declval<QMouseEvent *>()))) override;
    void focusInEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::focusInEvent(std::declval<QFocusEvent *>()))) override;
    void focusOutEvent(QFocusEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::focusOutEvent(std::declval<QFocusEvent *>()))) override;
    void changeEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::changeEvent(std::declval<QEvent *>()))) override;
    void timerEvent(QTimerEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QAbstractButton::timerEvent(std::declval<QTimerEvent *>()))) override;
    int devType() const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::devType())) override;
    void setVisible(bool p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::setVisible(std::declval<bool>()))) override;
    int heightForWidth(int p0) const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::heightForWidth(std::declval<int>()))) override;
    bool hasHeightForWidth() const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::hasHeightForWidth())) override;
    QPaintEngine * paintEngine() const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::paintEngine())) override;
    void mouseDoubleClickEvent(QMouseEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::mouseDoubleClickEvent(std::declval<QMouseEvent *>()))) override;
    void wheelEvent(QWheelEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::wheelEvent(std::declval<QWheelEvent *>()))) override;
    void enterEvent(QEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::enterEvent(std::declval<QEnterEvent *>()))) override;
    void leaveEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::leaveEvent(std::declval<QEvent *>()))) override;
    void moveEvent(QMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::moveEvent(std::declval<QMoveEvent *>()))) override;
    void resizeEvent(QResizeEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::resizeEvent(std::declval<QResizeEvent *>()))) override;
    void closeEvent(QCloseEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::closeEvent(std::declval<QCloseEvent *>()))) override;
    void contextMenuEvent(QContextMenuEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::contextMenuEvent(std::declval<QContextMenuEvent *>()))) override;
    void tabletEvent(QTabletEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::tabletEvent(std::declval<QTabletEvent *>()))) override;
    void actionEvent(QActionEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::actionEvent(std::declval<QActionEvent *>()))) override;
    void dragEnterEvent(QDragEnterEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::dragEnterEvent(std::declval<QDragEnterEvent *>()))) override;
    void dragMoveEvent(QDragMoveEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::dragMoveEvent(std::declval<QDragMoveEvent *>()))) override;
    void dragLeaveEvent(QDragLeaveEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::dragLeaveEvent(std::declval<QDragLeaveEvent *>()))) override;
    void dropEvent(QDropEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::dropEvent(std::declval<QDropEvent *>()))) override;
    void showEvent(QShowEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::showEvent(std::declval<QShowEvent *>()))) override;
    void hideEvent(QHideEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::hideEvent(std::declval<QHideEvent *>()))) override;
    int metric(QPaintDevice::PaintDeviceMetric p0) const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::metric(std::declval<QPaintDevice::PaintDeviceMetric>()))) override;
    void initPainter(QPainter * p0) const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::initPainter(std::declval<QPainter *>()))) override;
    QPainter * sharedPainter() const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::sharedPainter())) override;
    void inputMethodEvent(QInputMethodEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::inputMethodEvent(std::declval<QInputMethodEvent *>()))) override;
    QVariant inputMethodQuery(Qt::InputMethodQuery p0) const noexcept(noexcept(std::declval<const PhpQtQCheckBox &>().QWidget::inputMethodQuery(std::declval<Qt::InputMethodQuery>()))) override;
    bool focusNextPrevChild(bool p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QWidget::focusNextPrevChild(std::declval<bool>()))) override;
    bool eventFilter(QObject * p0, QEvent * p1) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QObject::eventFilter(std::declval<QObject *>(), std::declval<QEvent *>()))) override;
    void childEvent(QChildEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QObject::childEvent(std::declval<QChildEvent *>()))) override;
    void customEvent(QEvent * p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QObject::customEvent(std::declval<QEvent *>()))) override;
    void connectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QObject::connectNotify(std::declval<const QMetaMethod &>()))) override;
    void disconnectNotify(const QMetaMethod & p0) noexcept(noexcept(std::declval<PhpQtQCheckBox &>().QObject::disconnectNotify(std::declval<const QMetaMethod &>()))) override;
    bool phpqt_fwd_event(QEvent * p0) { return event(p0); }
    bool phpqt_fwd_hitButton(const QPoint & p0) const { return hitButton(p0); }
    void phpqt_fwd_checkStateSet() { checkStateSet(); }
    void phpqt_fwd_nextCheckState() { nextCheckState(); }
    void phpqt_fwd_paintEvent(QPaintEvent * p0) { paintEvent(p0); }
    void phpqt_fwd_mouseMoveEvent(QMouseEvent * p0) { mouseMoveEvent(p0); }
    void phpqt_fwd_initStyleOption(QStyleOptionButton * p0) const { initStyleOption(p0); }
    static const char *const kOverridable[];
};
