/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#ifndef PHPQT_WIDGETS_QFOCUSFRAME_H
#define PHPQT_WIDGETS_QFOCUSFRAME_H
#include "php.h"
#ifdef __cplusplus
extern "C" {
#endif

/*@ast const QMetaObject staticMetaObject */
/*@zep Widgets\QFocusFrame staticMetaObject() -> int */
zend_long phpqt_qfocusframe_static_meta_object(void);

/*@ast QString tr(const char * s, const char * c, int n) */
/*@zep Widgets\QFocusFrame tr(var s, var c = null, int n = -1) -> string */
void phpqt_qfocusframe_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n);

/*@ast QFocusFrame(QWidget * parent) */
/*@zep Widgets\QFocusFrame new(int parent = 0) -> int */
zend_long phpqt_qfocusframe_new(zval *p_parent);

/*@ast void setWidget(QWidget * widget) */
/*@zep Widgets\QFocusFrame setWidget(int handle, int widget) -> void */
void phpqt_qfocusframe_set_widget(zval *p_handle, zval *p_widget);

/*@ast QWidget * widget() const */
/*@zep Widgets\QFocusFrame widget(int handle) -> int */
zend_long phpqt_qfocusframe_widget(zval *p_handle);

/*@ast bool event(QEvent * e) */
/*@zep Widgets\QFocusFrame event(int handle, int e) -> bool */
zend_long phpqt_qfocusframe_event(zval *p_handle, zval *p_e);

/*@ast bool eventFilter(QObject *, QEvent *) */
/*@zep Widgets\QFocusFrame eventFilter(int handle, int arg0, int arg1) -> bool */
zend_long phpqt_qfocusframe_event_filter(zval *p_handle, zval *p_arg0, zval *p_arg1);

/*@ast void paintEvent(QPaintEvent *) */
/*@zep Widgets\QFocusFrame paintEvent(int handle, int arg0) -> void */
void phpqt_qfocusframe_paint_event(zval *p_handle, zval *p_arg0);

/*@ast void initStyleOption(QStyleOption * option) const */
/*@zep Widgets\QFocusFrame initStyleOption(int handle, int option) -> void */
void phpqt_qfocusframe_init_style_option(zval *p_handle, zval *p_option);

/*@override Widgets\QFocusFrame event bool event(QEvent * e) */
/*@override Widgets\QFocusFrame eventFilter bool eventFilter(QObject *, QEvent *) */
/*@override Widgets\QFocusFrame paintEvent void paintEvent(QPaintEvent *) */
/*@override Widgets\QFocusFrame initStyleOption void initStyleOption(QStyleOption * option) const */
/*@override Widgets\QFocusFrame devType int devType() const */
/*@override Widgets\QFocusFrame setVisible void setVisible(bool visible) */
/*@override Widgets\QFocusFrame sizeHint QSize sizeHint() const */
/*@override Widgets\QFocusFrame minimumSizeHint QSize minimumSizeHint() const */
/*@override Widgets\QFocusFrame heightForWidth int heightForWidth(int) const */
/*@override Widgets\QFocusFrame hasHeightForWidth bool hasHeightForWidth() const */
/*@override Widgets\QFocusFrame paintEngine QPaintEngine * paintEngine() const */
/*@override Widgets\QFocusFrame mousePressEvent void mousePressEvent(QMouseEvent * event) */
/*@override Widgets\QFocusFrame mouseReleaseEvent void mouseReleaseEvent(QMouseEvent * event) */
/*@override Widgets\QFocusFrame mouseDoubleClickEvent void mouseDoubleClickEvent(QMouseEvent * event) */
/*@override Widgets\QFocusFrame mouseMoveEvent void mouseMoveEvent(QMouseEvent * event) */
/*@override Widgets\QFocusFrame wheelEvent void wheelEvent(QWheelEvent * event) */
/*@override Widgets\QFocusFrame keyPressEvent void keyPressEvent(QKeyEvent * event) */
/*@override Widgets\QFocusFrame keyReleaseEvent void keyReleaseEvent(QKeyEvent * event) */
/*@override Widgets\QFocusFrame focusInEvent void focusInEvent(QFocusEvent * event) */
/*@override Widgets\QFocusFrame focusOutEvent void focusOutEvent(QFocusEvent * event) */
/*@override Widgets\QFocusFrame enterEvent void enterEvent(QEnterEvent * event) */
/*@override Widgets\QFocusFrame leaveEvent void leaveEvent(QEvent * event) */
/*@override Widgets\QFocusFrame moveEvent void moveEvent(QMoveEvent * event) */
/*@override Widgets\QFocusFrame resizeEvent void resizeEvent(QResizeEvent * event) */
/*@override Widgets\QFocusFrame closeEvent void closeEvent(QCloseEvent * event) */
/*@override Widgets\QFocusFrame contextMenuEvent void contextMenuEvent(QContextMenuEvent * event) */
/*@override Widgets\QFocusFrame tabletEvent void tabletEvent(QTabletEvent * event) */
/*@override Widgets\QFocusFrame actionEvent void actionEvent(QActionEvent * event) */
/*@override Widgets\QFocusFrame dragEnterEvent void dragEnterEvent(QDragEnterEvent * event) */
/*@override Widgets\QFocusFrame dragMoveEvent void dragMoveEvent(QDragMoveEvent * event) */
/*@override Widgets\QFocusFrame dragLeaveEvent void dragLeaveEvent(QDragLeaveEvent * event) */
/*@override Widgets\QFocusFrame dropEvent void dropEvent(QDropEvent * event) */
/*@override Widgets\QFocusFrame showEvent void showEvent(QShowEvent * event) */
/*@override Widgets\QFocusFrame hideEvent void hideEvent(QHideEvent * event) */
/*@reserved-override Widgets\QFocusFrame raw-pointer bool nativeEvent(const QByteArray & eventType, void * message, qintptr * result) */
/*@override Widgets\QFocusFrame changeEvent void changeEvent(QEvent *) */
/*@override Widgets\QFocusFrame metric int metric(QPaintDevice::PaintDeviceMetric) const */
/*@override Widgets\QFocusFrame initPainter void initPainter(QPainter * painter) const */
/*@reserved-override Widgets\QFocusFrame raw-pointer QPaintDevice * redirected(QPoint * offset) const */
/*@override Widgets\QFocusFrame sharedPainter QPainter * sharedPainter() const */
/*@override Widgets\QFocusFrame inputMethodEvent void inputMethodEvent(QInputMethodEvent *) */
/*@override Widgets\QFocusFrame inputMethodQuery QVariant inputMethodQuery(Qt::InputMethodQuery) const */
/*@override Widgets\QFocusFrame focusNextPrevChild bool focusNextPrevChild(bool next) */
/*@override Widgets\QFocusFrame timerEvent void timerEvent(QTimerEvent * event) */
/*@override Widgets\QFocusFrame childEvent void childEvent(QChildEvent * event) */
/*@override Widgets\QFocusFrame customEvent void customEvent(QEvent * event) */
/*@override Widgets\QFocusFrame connectNotify void connectNotify(const QMetaMethod & signal) */
/*@override Widgets\QFocusFrame disconnectNotify void disconnectNotify(const QMetaMethod & signal) */

#ifdef __cplusplus
}
#endif
#endif
