/* GENERATED by scripts/gen-src.php — DO NOT EDIT. */
#include <QtCore/qcoreevent.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qobject.h>
#include <QtCore/qobjectdefs.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
#include <QtWidgets/qscroller.h>
#include <QtWidgets/qscrollerproperties.h>
#include <optional>
#include <vector>
#include "phpqt-support.h"
#include "phpqt-types.h"
#include "widgets-qscroller.h"

extern "C" zend_long phpqt_qscroller_static_meta_object(void)
{
    return phpqt::reg_copy(QScroller::staticMetaObject, PHPQT_TAG_QMetaObject); /* native */
}

extern "C" void phpqt_qscroller_tr(zval *return_value, zval *p_s, zval *p_c, zval *p_n)
{
    const char *a0 = phpqt::arg_cstr(p_s);
    const char *a1 = phpqt::arg_cstr(p_c);
    int a2 = static_cast<int>(phpqt::arg_long(p_n));
    phpqt::ret_qstring(return_value, QScroller::tr(a0, a1, a2)); /* native */
}

extern "C" zend_long phpqt_qscroller_has_scroller(zval *p_target)
{
    QObject *a0 = phpqt::as<QObject>(p_target, PHPQT_TAG_QObject);
    return (QScroller::hasScroller(a0)) ? 1 : 0; /* native */
}

extern "C" zend_long phpqt_qscroller_scroller(zval *p_target)
{
    QObject *a0 = phpqt::as<QObject>(p_target, PHPQT_TAG_QObject);
    return phpqt::reg_out(const_cast<QScroller *>(QScroller::scroller(a0)), PHPQT_TAG_QScroller); /* native */
}

extern "C" zend_long phpqt_qscroller_grab_gesture(zval *p_target, zval *p_gestureType)
{
    QObject *a0 = phpqt::as<QObject>(p_target, PHPQT_TAG_QObject);
    QScroller::ScrollerGestureType a1 = phpqt::is_null(p_gestureType) ? static_cast<QScroller::ScrollerGestureType>(QScroller::TouchGesture) : static_cast<QScroller::ScrollerGestureType>(phpqt::arg_long(p_gestureType));
    return static_cast<zend_long>(QScroller::grabGesture(a0, a1)); /* native */
}

extern "C" zend_long phpqt_qscroller_grabbed_gesture(zval *p_target)
{
    QObject *a0 = phpqt::as<QObject>(p_target, PHPQT_TAG_QObject);
    return static_cast<zend_long>(QScroller::grabbedGesture(a0)); /* native */
}

extern "C" void phpqt_qscroller_ungrab_gesture(zval *p_target)
{
    QObject *a0 = phpqt::as<QObject>(p_target, PHPQT_TAG_QObject);
    QScroller::ungrabGesture(a0); /* native */
}

extern "C" void phpqt_qscroller_active_scrollers(zval *return_value)
{
    phpqt::ret_seq(return_value, QScroller::activeScrollers(), [](zval *ez, const QScroller *e) { ZVAL_LONG(ez, phpqt::reg_out(const_cast<QScroller *>(e), PHPQT_TAG_QScroller)); }); /* native */
}

extern "C" zend_long phpqt_qscroller_target(zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::target: handle is not a QScroller"); return 0; }
    return phpqt::reg_out(const_cast<QObject *>(self->target()), PHPQT_TAG_QObject); /* native */
}

extern "C" zend_long phpqt_qscroller_state(zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::state: handle is not a QScroller"); return 0; }
    return static_cast<zend_long>(self->state()); /* native */
}

extern "C" zend_long phpqt_qscroller_handle_input(zval *p_handle, zval *p_input, zval *p_positionX, zval *p_positionY, zval *p_timestamp)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::handleInput: handle is not a QScroller"); return 0; }
    QScroller::Input a0 = static_cast<QScroller::Input>(phpqt::arg_long(p_input));
    QPointF a1 = QPointF(phpqt::arg_double(p_positionX), phpqt::arg_double(p_positionY));
    long long int a2 = static_cast<long long int>(phpqt::arg_long(p_timestamp));
    return (self->handleInput(a0, a1, a2)) ? 1 : 0; /* native */
}

extern "C" void phpqt_qscroller_stop(zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::stop: handle is not a QScroller"); return; }
    self->stop(); /* native */
}

extern "C" void phpqt_qscroller_velocity(zval *return_value, zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::velocity: handle is not a QScroller"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->velocity()); /* native */
}

extern "C" void phpqt_qscroller_final_position(zval *return_value, zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::finalPosition: handle is not a QScroller"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->finalPosition()); /* native */
}

extern "C" void phpqt_qscroller_pixel_per_meter(zval *return_value, zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::pixelPerMeter: handle is not a QScroller"); ZVAL_NULL(return_value); return; }
    phpqt::ret_geom(return_value, self->pixelPerMeter()); /* native */
}

extern "C" zend_long phpqt_qscroller_scroller_properties(zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::scrollerProperties: handle is not a QScroller"); return 0; }
    return phpqt::reg(new QScrollerProperties(self->scrollerProperties()), PHPQT_TAG_QScrollerProperties, true); /* native */
}

extern "C" void phpqt_qscroller_set_snap_positions_x(zval *p_handle, zval *p_positions)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::setSnapPositionsX: handle is not a QScroller"); return; }
    QList<double> a0 = phpqt::arg_seq<double>(p_positions, [](zval *ev) -> double { return static_cast<double>(phpqt::arg_double(ev)); });
    self->setSnapPositionsX(a0); /* native */
}

extern "C" void phpqt_qscroller_set_snap_positions_x_qreal_qreal(zval *p_handle, zval *p_first, zval *p_interval)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::setSnapPositionsX: handle is not a QScroller"); return; }
    double a0 = static_cast<double>(phpqt::arg_double(p_first));
    double a1 = static_cast<double>(phpqt::arg_double(p_interval));
    self->setSnapPositionsX(a0, a1); /* native */
}

extern "C" void phpqt_qscroller_set_snap_positions_y(zval *p_handle, zval *p_positions)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::setSnapPositionsY: handle is not a QScroller"); return; }
    QList<double> a0 = phpqt::arg_seq<double>(p_positions, [](zval *ev) -> double { return static_cast<double>(phpqt::arg_double(ev)); });
    self->setSnapPositionsY(a0); /* native */
}

extern "C" void phpqt_qscroller_set_snap_positions_y_qreal_qreal(zval *p_handle, zval *p_first, zval *p_interval)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::setSnapPositionsY: handle is not a QScroller"); return; }
    double a0 = static_cast<double>(phpqt::arg_double(p_first));
    double a1 = static_cast<double>(phpqt::arg_double(p_interval));
    self->setSnapPositionsY(a0, a1); /* native */
}

extern "C" void phpqt_qscroller_set_scroller_properties(zval *p_handle, zval *p_prop)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::setScrollerProperties: handle is not a QScroller"); return; }
    QScrollerProperties *a0_p = phpqt::is_null(p_prop) ? nullptr : phpqt::as<QScrollerProperties>(p_prop, PHPQT_TAG_QScrollerProperties);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::setScrollerProperties: prop is not a QScrollerProperties handle"); return; }
    self->setScrollerProperties(*a0_p); /* native */
}

extern "C" void phpqt_qscroller_scroll_to(zval *p_handle, zval *p_posX, zval *p_posY)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::scrollTo: handle is not a QScroller"); return; }
    QPointF a0 = QPointF(phpqt::arg_double(p_posX), phpqt::arg_double(p_posY));
    self->scrollTo(a0); /* native */
}

extern "C" void phpqt_qscroller_scroll_to_q_point_f_int(zval *p_handle, zval *p_posX, zval *p_posY, zval *p_scrollTime)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::scrollTo: handle is not a QScroller"); return; }
    QPointF a0 = QPointF(phpqt::arg_double(p_posX), phpqt::arg_double(p_posY));
    int a1 = static_cast<int>(phpqt::arg_long(p_scrollTime));
    self->scrollTo(a0, a1); /* native */
}

extern "C" void phpqt_qscroller_ensure_visible(zval *p_handle, zval *p_rectX, zval *p_rectY, zval *p_rectWidth, zval *p_rectHeight, zval *p_xmargin, zval *p_ymargin)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::ensureVisible: handle is not a QScroller"); return; }
    QRectF a0 = QRectF(phpqt::arg_double(p_rectX), phpqt::arg_double(p_rectY), phpqt::arg_double(p_rectWidth), phpqt::arg_double(p_rectHeight));
    double a1 = static_cast<double>(phpqt::arg_double(p_xmargin));
    double a2 = static_cast<double>(phpqt::arg_double(p_ymargin));
    self->ensureVisible(a0, a1, a2); /* native */
}

extern "C" void phpqt_qscroller_ensure_visible_q_rect_f_qreal_qreal_int(zval *p_handle, zval *p_rectX, zval *p_rectY, zval *p_rectWidth, zval *p_rectHeight, zval *p_xmargin, zval *p_ymargin, zval *p_scrollTime)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::ensureVisible: handle is not a QScroller"); return; }
    QRectF a0 = QRectF(phpqt::arg_double(p_rectX), phpqt::arg_double(p_rectY), phpqt::arg_double(p_rectWidth), phpqt::arg_double(p_rectHeight));
    double a1 = static_cast<double>(phpqt::arg_double(p_xmargin));
    double a2 = static_cast<double>(phpqt::arg_double(p_ymargin));
    int a3 = static_cast<int>(phpqt::arg_long(p_scrollTime));
    self->ensureVisible(a0, a1, a2, a3); /* native */
}

extern "C" void phpqt_qscroller_resend_prepare_event(zval *p_handle)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::resendPrepareEvent: handle is not a QScroller"); return; }
    self->resendPrepareEvent(); /* native */
}

extern "C" void phpqt_qscroller_state_changed(zval *p_handle, zval *p_newstate)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::stateChanged: handle is not a QScroller"); return; }
    QScroller::State a0 = static_cast<QScroller::State>(phpqt::arg_long(p_newstate));
    self->stateChanged(a0); /* native */
}

extern "C" void phpqt_qscroller_scroller_properties_changed(zval *p_handle, zval *p_arg0)
{
    QScroller *self = phpqt::as<QScroller>(p_handle, PHPQT_TAG_QScroller);
    if (self == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::scrollerPropertiesChanged: handle is not a QScroller"); return; }
    QScrollerProperties *a0_p = phpqt::is_null(p_arg0) ? nullptr : phpqt::as<QScrollerProperties>(p_arg0, PHPQT_TAG_QScrollerProperties);
    if (a0_p == nullptr) { php_error_docref(NULL, E_WARNING, "QScroller::scrollerPropertiesChanged: arg0 is not a QScrollerProperties handle"); return; }
    self->scrollerPropertiesChanged(*a0_p); /* native */
}

