
extern zend_class_entry *qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader);

PHP_METHOD(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader, new_);
PHP_METHOD(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader, header);
PHP_METHOD(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader, setHeader);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_header, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_setheader, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_method_entry) {
	PHP_ME(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader, new_, arginfo_qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader, header, arginfo_qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_header, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QPluginMetaDataMagicHeader_QPluginMetaDataMagicHeader, setHeader, arginfo_qt_core_qpluginmetadatamagicheader_qpluginmetadatamagicheader_setheader, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
