
extern zend_class_entry *qt_widgets_qgesturefunctions_qgesturefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QGestureFunctions_QGestureFunctions);

PHP_METHOD(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_Qt__GestureState);
PHP_METHOD(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_Qt__GestureType);
PHP_METHOD(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_QPinchGesture__ChangeFlags);
PHP_METHOD(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_QGesture__GestureCancelPolicy);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qt__gesturestate, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qt__gesturetype, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qpinchgesture__changeflags, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qgesture__gesturecancelpolicy, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qgesturefunctions_qgesturefunctions_method_entry) {
	PHP_ME(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_Qt__GestureState, arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qt__gesturestate, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_Qt__GestureType, arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qt__gesturetype, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_QPinchGesture__ChangeFlags, arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qpinchgesture__changeflags, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QGestureFunctions_QGestureFunctions, qRegisterNormalizedMetaType_QGesture__GestureCancelPolicy, arginfo_qt_widgets_qgesturefunctions_qgesturefunctions_qregisternormalizedmetatype_qgesture__gesturecancelpolicy, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
