
extern zend_class_entry *qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_ce;

ZEPHIR_INIT_CLASS(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters);

PHP_METHOD(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, threadPool);
PHP_METHOD(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, setThreadPool);
PHP_METHOD(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, priority);
PHP_METHOD(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, setPriority);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_threadpool, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_setthreadpool, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_priority, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_setpriority, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_method_entry) {
	PHP_ME(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, threadPool, arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_threadpool, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, setThreadPool, arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_setthreadpool, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, priority, arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_priority, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentTaskStartParameters_QtConcurrentTaskStartParameters, setPriority, arginfo_qt_concurrent_qtconcurrenttaskstartparameters_qtconcurrenttaskstartparameters_setpriority, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
