
extern zend_class_entry *qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_ce;

ZEPHIR_INIT_CLASS(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase);

PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, new_);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, startSingleThreaded);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, startThread);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, isCanceled);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, waitForResume);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, isProgressReportingEnabled);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setProgressValue);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setProgressRange);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, acquireBarrierSemaphore);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, reportIfSuspensionDone);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, start);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, finish);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, threadFunction);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, shouldStartThread);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, shouldThrottleThread);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, futureInterface);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setFutureInterface);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, threadPool);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setThreadPool);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, barrier);
PHP_METHOD(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, mutex);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_new_, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pool, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_startsinglethreaded, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_startthread, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_iscanceled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_waitforresume, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_isprogressreportingenabled, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setprogressvalue, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, progress, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setprogressrange, 0, 3, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, minimum, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, maximum, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_acquirebarriersemaphore, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_reportifsuspensiondone, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_start, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_finish, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_threadfunction, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_shouldstartthread, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_shouldthrottlethread, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_futureinterface, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setfutureinterface, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_threadpool, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setthreadpool, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_barrier, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_mutex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_method_entry) {
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, new_, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, startSingleThreaded, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_startsinglethreaded, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, startThread, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_startthread, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, isCanceled, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_iscanceled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, waitForResume, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_waitforresume, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, isProgressReportingEnabled, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_isprogressreportingenabled, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setProgressValue, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setprogressvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setProgressRange, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setprogressrange, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, acquireBarrierSemaphore, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_acquirebarriersemaphore, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, reportIfSuspensionDone, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_reportifsuspensiondone, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, start, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_start, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, finish, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_finish, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, threadFunction, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_threadfunction, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, shouldStartThread, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_shouldstartthread, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, shouldThrottleThread, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_shouldthrottlethread, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, futureInterface, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_futureinterface, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setFutureInterface, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setfutureinterface, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, threadPool, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_threadpool, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, setThreadPool, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_setthreadpool, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, barrier, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_barrier, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentThreadEngineBase_QtConcurrentThreadEngineBase, mutex, arginfo_qt_concurrent_qtconcurrentthreadenginebase_qtconcurrentthreadenginebase_mutex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
