
extern zend_class_entry *qt_core_qalgorithmsfunctions_qalgorithmsfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions);

PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCount);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountQuint8);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountQuint16);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountQuint64);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountLongUnsignedInt);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBits);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsQuint8);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsQuint16);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsQuint64);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsLongUnsignedInt);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBits);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsQuint8);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsQuint16);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsQuint64);
PHP_METHOD(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsLongUnsignedInt);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcount, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountquint8, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountquint16, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountquint64, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountlongunsignedint, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobits, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitsquint8, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitsquint16, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitsquint64, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitslongunsignedint, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobits, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitsquint8, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitsquint16, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitsquint64, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitslongunsignedint, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, v, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qalgorithmsfunctions_qalgorithmsfunctions_method_entry) {
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCount, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcount, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountQuint8, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountquint8, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountQuint16, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountquint16, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountQuint64, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountquint64, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qPopulationCountLongUnsignedInt, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qpopulationcountlongunsignedint, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBits, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobits, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsQuint8, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitsquint8, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsQuint16, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitsquint16, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsQuint64, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitsquint64, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountTrailingZeroBitsLongUnsignedInt, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcounttrailingzerobitslongunsignedint, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBits, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobits, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsQuint8, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitsquint8, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsQuint16, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitsquint16, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsQuint64, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitsquint64, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QAlgorithmsFunctions_QAlgorithmsFunctions, qCountLeadingZeroBitsLongUnsignedInt, arginfo_qt_core_qalgorithmsfunctions_qalgorithmsfunctions_qcountleadingzerobitslongunsignedint, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
