
extern zend_class_entry *qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar);

PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, positionOfLine);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setPositionOfLine);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, positionWithinLine);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setPositionWithinLine);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, toolBarArea);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setToolBarArea);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, features);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setFeatures);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, lineWidth);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setLineWidth);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, midLineWidth);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setMidLineWidth);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, new_);
PHP_METHOD(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, newQStyleOptionToolBar);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_positionofline, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setpositionofline, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_positionwithinline, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setpositionwithinline, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_toolbararea, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_settoolbararea, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_features, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setfeatures, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_linewidth, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setlinewidth, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_midlinewidth, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setmidlinewidth, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_new_, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_newqstyleoptiontoolbar, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, other, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_method_entry) {
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, positionOfLine, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_positionofline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setPositionOfLine, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setpositionofline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, positionWithinLine, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_positionwithinline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setPositionWithinLine, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setpositionwithinline, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, toolBarArea, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_toolbararea, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setToolBarArea, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_settoolbararea, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, features, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_features, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setFeatures, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setfeatures, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, lineWidth, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_linewidth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setLineWidth, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setlinewidth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, midLineWidth, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_midlinewidth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, setMidLineWidth, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_setmidlinewidth, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, new_, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Widgets_QStyleOptionToolBar_QStyleOptionToolBar, newQStyleOptionToolBar, arginfo_qt_widgets_qstyleoptiontoolbar_qstyleoptiontoolbar_newqstyleoptiontoolbar, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
