
extern zend_class_entry *qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions);

PHP_METHOD(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions, qRegisterNormalizedMetaType_QSocketNotifier_Type);
PHP_METHOD(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions, qRegisterNormalizedMetaType_QSocketDescriptor);
PHP_METHOD(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions, comparesEqual);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_qregisternormalizedmetatype_qsocketnotifier_type, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_qregisternormalizedmetatype_qsocketdescriptor, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_method_entry) {
	PHP_ME(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions, qRegisterNormalizedMetaType_QSocketNotifier_Type, arginfo_qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_qregisternormalizedmetatype_qsocketnotifier_type, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions, qRegisterNormalizedMetaType_QSocketDescriptor, arginfo_qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_qregisternormalizedmetatype_qsocketdescriptor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QSocketnotifierFunctions_QSocketnotifierFunctions, comparesEqual, arginfo_qt_core_qsocketnotifierfunctions_qsocketnotifierfunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
