
extern zend_class_entry *qt_widgets_qscrollbarfunctions_qscrollbarfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Widgets_QScrollbarFunctions_QScrollbarFunctions);

PHP_METHOD(Qt_Widgets_QScrollbarFunctions_QScrollbarFunctions, qt_qscrollbarStyleOption);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_widgets_qscrollbarfunctions_qscrollbarfunctions_qt_qscrollbarstyleoption, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, scrollBar, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_widgets_qscrollbarfunctions_qscrollbarfunctions_method_entry) {
	PHP_ME(Qt_Widgets_QScrollbarFunctions_QScrollbarFunctions, qt_qscrollbarStyleOption, arginfo_qt_widgets_qscrollbarfunctions_qscrollbarfunctions_qt_qscrollbarstyleoption, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
