
extern zend_class_entry *qt_core_qjsonvaluefunctions_qjsonvaluefunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions);

PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, swap);
PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, qHash);
PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqual);
PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueConstRefQJsonValue);
PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueConstRefQJsonValueConstRef);
PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueRefQJsonValueConstRef);
PHP_METHOD(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueRefQJsonValueRef);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_qhash, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, seed, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequal, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvalueconstrefqjsonvalue, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvalueconstrefqjsonvalueconstref, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvaluerefqjsonvalueconstref, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvaluerefqjsonvalueref, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qjsonvaluefunctions_qjsonvaluefunctions_method_entry) {
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, swap, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, qHash, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_qhash, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqual, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequal, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueConstRefQJsonValue, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvalueconstrefqjsonvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueConstRefQJsonValueConstRef, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvalueconstrefqjsonvalueconstref, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueRefQJsonValueConstRef, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvaluerefqjsonvalueconstref, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QJsonvalueFunctions_QJsonvalueFunctions, comparesEqualQJsonValueRefQJsonValueRef, arginfo_qt_core_qjsonvaluefunctions_qjsonvaluefunctions_comparesequalqjsonvaluerefqjsonvalueref, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
