
extern zend_class_entry *qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface);

PHP_METHOD(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, anchor);
PHP_METHOD(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, anchorTarget);
PHP_METHOD(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, startIndex);
PHP_METHOD(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, endIndex);
PHP_METHOD(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, isValid);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_anchor, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_anchortarget, 0, 1, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_startindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_endindex, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_isvalid, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_method_entry) {
	PHP_ME(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, anchor, arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_anchor, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, anchorTarget, arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_anchortarget, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, startIndex, arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_startindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, endIndex, arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_endindex, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QAccessibleHyperlinkInterface_QAccessibleHyperlinkInterface, isValid, arginfo_qt_gui_qaccessiblehyperlinkinterface_qaccessiblehyperlinkinterface_isvalid, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
