
extern zend_class_entry *qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_ce;

ZEPHIR_INIT_CLASS(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager);

PHP_METHOD(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, new_);
PHP_METHOD(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, timeBeforeUser);
PHP_METHOD(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, timeAfterUser);
PHP_METHOD(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, blockSize);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_new_, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, pool, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, iterationCount, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_timebeforeuser, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_timeafteruser, 0, 1, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_blocksize, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, handle, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_method_entry) {
	PHP_ME(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, new_, arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_new_, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, timeBeforeUser, arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_timebeforeuser, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, timeAfterUser, arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_timeafteruser, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Concurrent_QtConcurrentBlockSizeManager_QtConcurrentBlockSizeManager, blockSize, arginfo_qt_concurrent_qtconcurrentblocksizemanager_qtconcurrentblocksizemanager_blocksize, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
