
extern zend_class_entry *qt_core_qoperatingsystemversionfunctions_qoperatingsystemversionfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QOperatingsystemversionFunctions_QOperatingsystemversionFunctions);

PHP_METHOD(Qt_Core_QOperatingsystemversionFunctions_QOperatingsystemversionFunctions, compareThreeWay);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qoperatingsystemversionfunctions_qoperatingsystemversionfunctions_comparethreeway, 0, 2, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, lhs, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, rhs, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qoperatingsystemversionfunctions_qoperatingsystemversionfunctions_method_entry) {
	PHP_ME(Qt_Core_QOperatingsystemversionFunctions_QOperatingsystemversionFunctions, compareThreeWay, arginfo_qt_core_qoperatingsystemversionfunctions_qoperatingsystemversionfunctions_comparethreeway, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
