
extern zend_class_entry *qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions);

PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qgetenv);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariable);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableCharQString);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qputenv);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qunsetenv);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableIsEmpty);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableIsSet);
PHP_METHOD(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableIntValue);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qgetenv, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, varName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariable, 0, 1, IS_STRING, 0)
	ZEND_ARG_INFO(0, varName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariablecharqstring, 0, 2, IS_STRING, 0)
	ZEND_ARG_INFO(0, varName)
	ZEND_ARG_TYPE_INFO(0, defaultValue, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qputenv, 0, 2, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, varName)
	ZEND_ARG_TYPE_INFO(0, value, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qunsetenv, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, varName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariableisempty, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, varName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariableisset, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_INFO(0, varName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariableintvalue, 0, 1, IS_ARRAY, 0)
	ZEND_ARG_INFO(0, varName)
	ZEND_ARG_INFO(0, ok)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_method_entry) {
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qgetenv, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qgetenv, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariable, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariable, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableCharQString, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariablecharqstring, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qputenv, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qputenv, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qunsetenv, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qunsetenv, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableIsEmpty, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariableisempty, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableIsSet, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariableisset, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Core_QTenvironmentvariablesFunctions_QTenvironmentvariablesFunctions, qEnvironmentVariableIntValue, arginfo_qt_core_qtenvironmentvariablesfunctions_qtenvironmentvariablesfunctions_qenvironmentvariableintvalue, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
