
extern zend_class_entry *qt_gui_qstatictextfunctions_qstatictextfunctions_ce;

ZEPHIR_INIT_CLASS(Qt_Gui_QStatictextFunctions_QStatictextFunctions);

PHP_METHOD(Qt_Gui_QStatictextFunctions_QStatictextFunctions, swap);
PHP_METHOD(Qt_Gui_QStatictextFunctions_QStatictextFunctions, qRegisterNormalizedMetaType_QStaticText);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qstatictextfunctions_qstatictextfunctions_swap, 0, 2, IS_VOID, 0)

	ZEND_ARG_TYPE_INFO(0, value1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, value2, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_qt_gui_qstatictextfunctions_qstatictextfunctions_qregisternormalizedmetatype_qstatictext, 0, 1, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, arg0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(qt_gui_qstatictextfunctions_qstatictextfunctions_method_entry) {
	PHP_ME(Qt_Gui_QStatictextFunctions_QStatictextFunctions, swap, arginfo_qt_gui_qstatictextfunctions_qstatictextfunctions_swap, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(Qt_Gui_QStatictextFunctions_QStatictextFunctions, qRegisterNormalizedMetaType_QStaticText, arginfo_qt_gui_qstatictextfunctions_qstatictextfunctions_qregisternormalizedmetatype_qstatictext, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_FE_END
};
